//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMutableCopying.h"

@class NSArray;

@interface AppCenterBoutiqueModel : NSObject <NSMutableCopying>
{
    NSArray *_app;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSArray *app; // @synthesize app=_app;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;

@end

