//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSMutableCopying.h"

@class NSString, WKRouterModel;

@interface AppCenterBoutiqueItemListModel : NSObject <NSMutableCopying>
{
    _Bool _selected;
    NSString *_apptitle;
    NSString *_appico;
    NSString *_baoming;
    NSString *_downurl;
    NSString *_appver;
    NSString *_appsize;
    NSString *_summary;
    NSString *_downloadNums;
    WKRouterModel *_router;
    unsigned long long _appstatus;
    NSString *_ranking;
}

@property(copy, nonatomic) NSString *ranking; // @synthesize ranking=_ranking;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) unsigned long long appstatus; // @synthesize appstatus=_appstatus;
@property(retain, nonatomic) WKRouterModel *router; // @synthesize router=_router;
@property(copy, nonatomic) NSString *downloadNums; // @synthesize downloadNums=_downloadNums;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *appsize; // @synthesize appsize=_appsize;
@property(copy, nonatomic) NSString *appver; // @synthesize appver=_appver;
@property(copy, nonatomic) NSString *downurl; // @synthesize downurl=_downurl;
@property(copy, nonatomic) NSString *baoming; // @synthesize baoming=_baoming;
@property(copy, nonatomic) NSString *appico; // @synthesize appico=_appico;
@property(copy, nonatomic) NSString *apptitle; // @synthesize apptitle=_apptitle;
- (void).cxx_destruct;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;

@end

