//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppManagerItem : NSObject
{
    NSString *_icnName;
    NSString *_title;
    NSString *_desc;
    long long _updateNum;
}

@property(nonatomic) long long updateNum; // @synthesize updateNum=_updateNum;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *icnName; // @synthesize icnName=_icnName;
- (void).cxx_destruct;

@end

