//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AppSwitchModel : NSObject
{
    NSString *_sw_mingpai;
    NSString *_sw_appstore;
    NSString *_sw_video;
    NSString *_sw_live;
}

@property(retain, nonatomic) NSString *sw_live; // @synthesize sw_live=_sw_live;
@property(retain, nonatomic) NSString *sw_video; // @synthesize sw_video=_sw_video;
@property(retain, nonatomic) NSString *sw_appstore; // @synthesize sw_appstore=_sw_appstore;
@property(retain, nonatomic) NSString *sw_mingpai; // @synthesize sw_mingpai=_sw_mingpai;
- (void).cxx_destruct;

@end

