//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaiduMobAdNative.h"

@class BaiduMobAdChuileiSlot, NSString;

@interface BaiduMobAdChuilei : BaiduMobAdNative
{
    BaiduMobAdChuileiSlot *_slot;
}

@property(retain, nonatomic) BaiduMobAdChuileiSlot *slot; // @synthesize slot=_slot;
- (void).cxx_destruct;
- (void)callbackAdFailLoad:(int)arg1;
- (void)callbackAdObjectsSuccessLoad:(id)arg1;
- (void)requestAds;
- (id)init;

// Remaining properties
@property(copy, nonatomic) NSString *adId; // @dynamic adId;
@property(nonatomic) id <BaiduMobAdChuileiAdDelegate> delegate; // @dynamic delegate;
@property(copy, nonatomic) NSString *publisherId; // @dynamic publisherId;

@end

