//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, NSNumber, NSString;

@interface BaiduMobAdInstance : NSObject
{
    int _actionType;
    int _videoDuration;
    NSDictionary *_adData;
    NSString *_adType;
    NSString *_clickURL;
    NSString *_resourseCachePath;
    NSString *_chargeLogURL;
    NSString *_showLogURL;
    NSString *_resoureURL;
    NSString *_iconURL;
    NSString *_winLog;
    NSString *_thirdClick;
    NSString *_thirdShow;
    NSString *_publishId;
    NSString *_htmlString;
    NSString *_tid;
    NSString *_adid;
    NSString *_videoURL;
    NSString *_title;
    NSString *_adDescription;
    NSString *_queryKey;
    NSString *_appName;
    NSArray *_nwinLog;
    NSArray *_morePics;
    NSString *_phone;
    NSDictionary *_apo;
    NSString *_apoPage;
    NSString *_fallback;
    NSNumber *_fallbackAct;
    NSDictionary *_monitors;
    NSArray *_monVShowArray;
    NSArray *_monVStartArray;
    NSArray *_monVClickArray;
    NSArray *_monVCloseArray;
    NSArray *_monVSkipArray;
    NSArray *_monShowEndCardArray;
    NSArray *_monClickEndCardArray;
    double _adStartTime;
}

@property double adStartTime; // @synthesize adStartTime=_adStartTime;
@property(retain, nonatomic) NSArray *monClickEndCardArray; // @synthesize monClickEndCardArray=_monClickEndCardArray;
@property(retain, nonatomic) NSArray *monShowEndCardArray; // @synthesize monShowEndCardArray=_monShowEndCardArray;
@property(retain, nonatomic) NSArray *monVSkipArray; // @synthesize monVSkipArray=_monVSkipArray;
@property(retain, nonatomic) NSArray *monVCloseArray; // @synthesize monVCloseArray=_monVCloseArray;
@property(retain, nonatomic) NSArray *monVClickArray; // @synthesize monVClickArray=_monVClickArray;
@property(retain, nonatomic) NSArray *monVStartArray; // @synthesize monVStartArray=_monVStartArray;
@property(retain, nonatomic) NSArray *monVShowArray; // @synthesize monVShowArray=_monVShowArray;
@property(retain, nonatomic) NSDictionary *monitors; // @synthesize monitors=_monitors;
@property(retain, nonatomic) NSNumber *fallbackAct; // @synthesize fallbackAct=_fallbackAct;
@property(retain, nonatomic) NSString *fallback; // @synthesize fallback=_fallback;
@property(retain, nonatomic) NSString *apoPage; // @synthesize apoPage=_apoPage;
@property(retain, nonatomic) NSDictionary *apo; // @synthesize apo=_apo;
@property(retain, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) NSArray *morePics; // @synthesize morePics=_morePics;
@property(retain, nonatomic) NSArray *nwinLog; // @synthesize nwinLog=_nwinLog;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(copy, nonatomic) NSString *queryKey; // @synthesize queryKey=_queryKey;
@property(copy, nonatomic) NSString *adDescription; // @synthesize adDescription=_adDescription;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int videoDuration; // @synthesize videoDuration=_videoDuration;
@property(copy, nonatomic) NSString *videoURL; // @synthesize videoURL=_videoURL;
@property(copy, nonatomic) NSString *adid; // @synthesize adid=_adid;
@property(copy, nonatomic) NSString *tid; // @synthesize tid=_tid;
@property(copy, nonatomic) NSString *htmlString; // @synthesize htmlString=_htmlString;
@property(copy, nonatomic) NSString *publishId; // @synthesize publishId=_publishId;
@property(copy, nonatomic) NSString *thirdShow; // @synthesize thirdShow=_thirdShow;
@property(copy, nonatomic) NSString *thirdClick; // @synthesize thirdClick=_thirdClick;
@property(copy, nonatomic) NSString *winLog; // @synthesize winLog=_winLog;
@property(copy, nonatomic) NSString *iconURL; // @synthesize iconURL=_iconURL;
@property(copy, nonatomic) NSString *resoureURL; // @synthesize resoureURL=_resoureURL;
@property(copy, nonatomic) NSString *showLogURL; // @synthesize showLogURL=_showLogURL;
@property(copy, nonatomic) NSString *chargeLogURL; // @synthesize chargeLogURL=_chargeLogURL;
@property(copy, nonatomic) NSString *resourseCachePath; // @synthesize resourseCachePath=_resourseCachePath;
@property(copy, nonatomic) NSString *clickURL; // @synthesize clickURL=_clickURL;
@property(nonatomic) int actionType; // @synthesize actionType=_actionType;
@property(copy, nonatomic) NSString *adType; // @synthesize adType=_adType;
@property(retain, nonatomic) NSDictionary *adData; // @synthesize adData=_adData;
- (id)handleEmptyValue:(id)arg1 withDefaut:(id)arg2;
- (id)objectFromDict:(id)arg1 withKey:(id)arg2 withDefault:(id)arg3;
- (id)initWithDictonary:(id)arg1;
- (void)dealloc;

@end

