//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class BaiduMobAdImageDownloadQueue, BaiduMobAdRendererHelper, NSString, UIButton, UIView;

@interface BaiduMobAdRenderer : NSObject
{
    double _duration;
    double _playheadTime;
    BaiduMobAdRendererHelper *_rendererHelper;
    UIView *_rendererBaseView;
    double _rendererWidth;
    double _rendererHeight;
    NSString *_resourceUrl;
    double _startTimeStamp;
    double _containerBeforeCreatedTimeStamp;
    double _containerAfterCreatedTimeStamp;
    double _startLoadHtmlTimeStamp;
    BaiduMobAdImageDownloadQueue *_imageDownloadQueue;
    UIButton *_imageAdButton;
    UIButton *_imageBaiduIconButton;
}

@property(retain, nonatomic) UIButton *imageBaiduIconButton; // @synthesize imageBaiduIconButton=_imageBaiduIconButton;
@property(retain, nonatomic) UIButton *imageAdButton; // @synthesize imageAdButton=_imageAdButton;
@property(retain, nonatomic) BaiduMobAdImageDownloadQueue *imageDownloadQueue; // @synthesize imageDownloadQueue=_imageDownloadQueue;
@property(nonatomic) double startLoadHtmlTimeStamp; // @synthesize startLoadHtmlTimeStamp=_startLoadHtmlTimeStamp;
@property(nonatomic) double containerAfterCreatedTimeStamp; // @synthesize containerAfterCreatedTimeStamp=_containerAfterCreatedTimeStamp;
@property(nonatomic) double containerBeforeCreatedTimeStamp; // @synthesize containerBeforeCreatedTimeStamp=_containerBeforeCreatedTimeStamp;
@property(nonatomic) double startTimeStamp; // @synthesize startTimeStamp=_startTimeStamp;
@property(copy, nonatomic) NSString *resourceUrl; // @synthesize resourceUrl=_resourceUrl;
@property(nonatomic) double rendererHeight; // @synthesize rendererHeight=_rendererHeight;
@property(nonatomic) double rendererWidth; // @synthesize rendererWidth=_rendererWidth;
@property(nonatomic) UIView *rendererBaseView; // @synthesize rendererBaseView=_rendererBaseView;
@property(retain, nonatomic) BaiduMobAdRendererHelper *rendererHelper; // @synthesize rendererHelper=_rendererHelper;
- (void)pressImageBaiduIconButtonToShowWangmeng;
- (void)pressImageAdToShowIcon;
- (void)configImageBaiduIconWithImage:(id)arg1 frame:(struct CGRect)arg2 targetView:(id)arg3;
- (void)configImageAdWithImage:(id)arg1 frame:(struct CGRect)arg2 targetView:(id)arg3;
- (void)addLogoRecommendOnTargetView:(id)arg1;
- (void)didAdClickedForWeb;
- (void)didAdImpressedForWeb;
- (void)failedAdDisplayForWeb:(int)arg1;
- (void)willAdDisplayForWeb;
- (void)didReceiveFailForWeb;
- (void)didReceiveSuccessForWeb;
- (double)playheadTime;
- (double)duration;
- (void)didVideoFinishWithResult:(id)arg1;
- (void)playInterstitialVideo;
- (void)playVideoForVideoSdk:(id)arg1;
- (id)adView;
- (void)onAdPlayEnd;
- (void)stop;
- (void)reload;
- (void)resume;
- (void)pause;
- (void)start;
- (void)load;
- (id)initWithAdRendererHelper:(id)arg1;
- (void)dealloc;

@end

