//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "NJKWebViewProgressDelegate.h"
#import "UIWebViewDelegate.h"
#import "WKWebViewJSToolsDeleagete.h"
#import "WKWebViewToolbarDelegate.h"

@class JSContext, NJKWebViewProgress, NJKWebViewProgressView, NSString, UIBarButtonItem, UIButton, UIWebView, WKWebViewJSTools, WKWebViewToolbar;

@interface BaseWebPageViewController : WKBaseSubViewController <UIWebViewDelegate, WKWebViewJSToolsDeleagete, WKWebViewToolbarDelegate, NJKWebViewProgressDelegate>
{
    WKWebViewToolbar *_webviewToolbar;
    NSString *_fromPage;
    _Bool _hasHome;
    _Bool _shouldIntercept;
    UIWebView *webpageView;
    NSString *title;
    UIButton *_shareButton;
    JSContext *_context;
    NSString *_webUrl;
    WKWebViewJSTools *_webviewJSTools;
    CDUnknownBlockType _loadFinishBlock;
    CDUnknownBlockType _willStartLoadBlock;
    NJKWebViewProgressView *_progressView;
    NJKWebViewProgress *_progressProxy;
    UIBarButtonItem *_closeBarButtonItem;
}

+ (id)webPageWithUrl:(id)arg1 fromPage:(id)arg2 title:(id)arg3;
@property(retain, nonatomic) UIBarButtonItem *closeBarButtonItem; // @synthesize closeBarButtonItem=_closeBarButtonItem;
@property(nonatomic) _Bool shouldIntercept; // @synthesize shouldIntercept=_shouldIntercept;
@property(retain, nonatomic) NJKWebViewProgress *progressProxy; // @synthesize progressProxy=_progressProxy;
@property(retain, nonatomic) NJKWebViewProgressView *progressView; // @synthesize progressView=_progressView;
@property(copy, nonatomic) CDUnknownBlockType willStartLoadBlock; // @synthesize willStartLoadBlock=_willStartLoadBlock;
@property(copy, nonatomic) CDUnknownBlockType loadFinishBlock; // @synthesize loadFinishBlock=_loadFinishBlock;
@property(retain, nonatomic) WKWebViewJSTools *webviewJSTools; // @synthesize webviewJSTools=_webviewJSTools;
@property(copy, nonatomic) NSString *webUrl; // @synthesize webUrl=_webUrl;
@property(retain, nonatomic) JSContext *context; // @synthesize context=_context;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(nonatomic) _Bool hasHome; // @synthesize hasHome=_hasHome;
@property(retain, nonatomic) NSString *title; // @synthesize title;
@property(retain, nonatomic) UIWebView *webpageView; // @synthesize webpageView;
- (void).cxx_destruct;
- (void)playVideo;
- (void)home;
- (void)onWebViewJSToolsTurnPlayBtn:(_Bool)arg1;
- (void)onWebViewJSToolsTurnNavibar:(_Bool)arg1;
- (void)onWebViewJSToolsSetShareIconVisibility:(_Bool)arg1;
- (void)onWebViewJSToolsFinishViewController;
- (void)webViewHistoryDidChange:(id)arg1;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)backButtonClicked;
- (void)shareButtonClicked;
- (void)webViewProgress:(id)arg1 updateProgress:(float)arg2;
- (void)initProgressView;
- (void)initWebviewToolbar;
- (void)closeWebView;
- (void)goBackClick;
- (void)createNavItem;
- (void)viewDidLoad;
- (void)refreshWebViewWithUrl:(id)arg1;
- (id)init;
- (id)initWithUrl:(id)arg1 withFromPage:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

