//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

#import "CAAnimationDelegate.h"

@class NSString;

@interface BoardView : UIButton <CAAnimationDelegate>
{
    struct CGPoint _beginPoint;
    struct CGPoint _selfBeginCenter;
    int _direction;
    _Bool _isAnimation;
    float _currentDegree;
    long long _shakeCount;
    _Bool _selfBoardOpen;
    _Bool _moving;
}

@property(readonly, nonatomic) _Bool moving; // @synthesize moving=_moving;
@property(nonatomic) _Bool selfBoardOpen; // @synthesize selfBoardOpen=_selfBoardOpen;
- (int)velocityByPoint:(struct CGPoint)arg1 andPoint:(struct CGPoint)arg2;
- (int)directByPoint:(struct CGPoint)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)dealloc;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)stopAnimation;
- (void)startAnimation;
- (_Bool)isAnimation;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

