//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class IFlyPcmPlayer;

#pragma mark Function Pointers and Blocks

typedef void (*CDUnknownFunctionPointerType)(void); // return type and parameters are unknown

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct AdSize {
    int _field1;
    int _field2;
};

struct AudioQueueBuffer;

struct AudioQueueLevelMeterState;

struct AudioStreamBasicDescription {
    double mSampleRate;
    unsigned int mFormatID;
    unsigned int mFormatFlags;
    unsigned int mBytesPerPacket;
    unsigned int mFramesPerPacket;
    unsigned int mBytesPerFrame;
    unsigned int mChannelsPerFrame;
    unsigned int mBitsPerChannel;
    unsigned int mReserved;
};

struct CGAffineTransform {
    double a;
    double b;
    double c;
    double d;
    double tx;
    double ty;
};

struct CGPoint {
    double x;
    double y;
};

struct CGRect {
    struct CGPoint origin;
    struct CGSize size;
};

struct CGSize {
    double width;
    double height;
};

struct CLLocationCoordinate2D {
    double latitude;
    double longitude;
};

struct GDTMobJKConstBuffer {
    struct GDTMobJKConstPtrRange _field1;
};

struct GDTMobJKConstPtrRange {
    char *_field1;
    unsigned long long _field2;
};

struct GDTMobJKEncodeCache {
    id _field1;
    unsigned long long _field2;
    unsigned long long _field3;
};

struct GDTMobJKEncodeState {
    struct GDTMobJKManagedBuffer _field1;
    struct GDTMobJKManagedBuffer _field2;
    unsigned long long _field3;
    struct GDTMobJKFastClassLookup _field4;
    struct GDTMobJKEncodeCache _field5[1024];
    unsigned long long _field6;
    unsigned long long _field7;
    unsigned long long _field8;
    id _field9;
    id _field10;
    SEL _field11;
    CDUnknownFunctionPointerType _field12;
    CDUnknownBlockType _field13;
};

struct GDTMobJKFastClassLookup {
    void *_field1;
    void *_field2;
    void *_field3;
    void *_field4;
    void *_field5;
};

struct GDTMobJKHashTableEntry {
    unsigned long long _field1;
    id _field2;
    id _field3;
};

struct GDTMobJKManagedBuffer {
    struct GDTMobJKPtrRange _field1;
    unsigned long long _field2;
    unsigned long long _field3;
};

struct GDTMobJKObjCImpCache {
    Class _field1;
    CDUnknownFunctionPointerType _field2;
    CDUnknownFunctionPointerType _field3;
};

struct GDTMobJKObjectStack {
    void **_field1;
    void **_field2;
    unsigned long long *_field3;
    unsigned long long _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    unsigned long long _field7;
};

struct GDTMobJKParseState {
    unsigned long long _field1;
    struct GDTMobJKConstBuffer _field2;
    unsigned long long _field3;
    unsigned long long _field4;
    unsigned long long _field5;
    unsigned long long _field6;
    unsigned long long _field7;
    unsigned long long _field8;
    struct GDTMobJKParseToken _field9;
    struct GDTMobJKObjectStack _field10;
    struct GDTMobJKTokenCache _field11;
    struct GDTMobJKObjCImpCache _field12;
    id _field13;
    int _field14;
    _Bool _field15;
};

struct GDTMobJKParseToken {
    struct GDTMobJKConstPtrRange _field1;
    unsigned long long _field2;
    struct GDTMobJKTokenValue _field3;
    struct GDTMobJKManagedBuffer _field4;
};

struct GDTMobJKPtrRange {
    char *_field1;
    unsigned long long _field2;
};

struct GDTMobJKTokenCache {
    struct GDTMobJKTokenCacheItem *_field1;
    unsigned long long _field2;
    unsigned int _field3;
    unsigned char _field4[1024];
};

struct GDTMobJKTokenCacheItem;

struct GDTMobJKTokenValue {
    struct GDTMobJKConstPtrRange _field1;
    unsigned long long _field2;
    unsigned long long _field3;
    union {
        long long _field1;
        unsigned long long _field2;
        double _field3;
    } _field4;
    struct GDTMobJKTokenCacheItem *_field5;
};

struct IFlyAQCallBackStruct {
    struct OpaqueAudioQueue *queue;
    unsigned int frameCount;
    struct AudioQueueBuffer *mBuffers[3];
    struct AudioStreamBasicDescription mDataFormat;
    unsigned int sampleLen;
    unsigned int playPtr;
    IFlyPcmPlayer *player;
    struct *bufferQueue;
};

struct MiPushDDListNode {
    void *_field1;
    struct MiPushDDListNode *_field2;
    struct MiPushDDListNode *_field3;
};

struct MiPushGCDMulticastDelegateListNode {
    id _field1;
    struct dispatch_queue_s *_field2;
    struct MiPushGCDMulticastDelegateListNode *_field3;
    struct MiPushGCDMulticastDelegateListNode *_field4;
    int _field5;
};

struct NSMutableArray {
    Class _field1;
};

struct OpaqueAudioFileID;

struct OpaqueAudioQueue;

struct UIEdgeInsets {
    double top;
    double left;
    double bottom;
    double right;
};

struct _DDRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

struct __sFILE {
    char *_field1;
    int _field2;
    int _field3;
    short _field4;
    short _field5;
    struct __sbuf _field6;
    int _field7;
    void *_field8;
    CDUnknownFunctionPointerType _field9;
    CDUnknownFunctionPointerType _field10;
    CDUnknownFunctionPointerType _field11;
    CDUnknownFunctionPointerType _field12;
    struct __sbuf _field13;
    struct __sFILEX *_field14;
    int _field15;
    unsigned char _field16[3];
    unsigned char _field17[1];
    struct __sbuf _field18;
    int _field19;
    long long _field20;
};

struct __sbuf {
    char *_field1;
    int _field2;
};

struct _miPushXmlKind {
    void *_field1;
    int _field2;
};

struct _miPushXmlStd {
    void *_field1;
    int _field2;
    char *_field3;
    struct _xmlNode *_field4;
    struct _xmlNode *_field5;
    struct _xmlNode *_field6;
    struct _miPushXmlStd *_field7;
    struct _miPushXmlStd *_field8;
    struct _xmlDoc *_field9;
};

struct _xmlAttr {
    void *_field1;
    int _field2;
    char *_field3;
    struct _xmlNode *_field4;
    struct _xmlNode *_field5;
    struct _xmlNode *_field6;
    struct _xmlAttr *_field7;
    struct _xmlAttr *_field8;
    struct _xmlDoc *_field9;
    struct _xmlNs *_field10;
    int _field11;
    void *_field12;
};

struct _xmlDict;

struct _xmlDoc {
    void *_field1;
    int _field2;
    char *_field3;
    struct _xmlNode *_field4;
    struct _xmlNode *_field5;
    struct _xmlNode *_field6;
    struct _xmlNode *_field7;
    struct _xmlNode *_field8;
    struct _xmlDoc *_field9;
    int _field10;
    int _field11;
    struct _xmlDtd *_field12;
    struct _xmlDtd *_field13;
    struct _xmlNs *_field14;
    char *_field15;
    char *_field16;
    void *_field17;
    void *_field18;
    char *_field19;
    int _field20;
    struct _xmlDict *_field21;
    void *_field22;
    int _field23;
    int _field24;
};

struct _xmlDtd;

struct _xmlHashTable;

struct _xmlNode {
    void *_field1;
    int _field2;
    char *_field3;
    struct _xmlNode *_field4;
    struct _xmlNode *_field5;
    struct _xmlNode *_field6;
    struct _xmlNode *_field7;
    struct _xmlNode *_field8;
    struct _xmlDoc *_field9;
    struct _xmlNs *_field10;
    char *_field11;
    struct _xmlAttr *_field12;
    struct _xmlNs *_field13;
    void *_field14;
    unsigned short _field15;
    unsigned short _field16;
};

struct _xmlNs {
    struct _xmlNs *_field1;
    int _field2;
    char *_field3;
    char *_field4;
    void *_field5;
    struct _xmlDoc *_field6;
};

struct _xmlParserInput;

struct _xmlParserNodeInfo;

struct _xmlValidState;

struct dispatch_queue_s;

struct fd_set {
    int fds_bits[32];
};

struct in6_addr {
    union {
        unsigned char _field1[16];
        unsigned short _field2[8];
        unsigned int _field3[4];
    } _field1;
};

struct in_addr {
    unsigned int _field1;
};

struct internal_state;

struct sockaddr {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[14];
};

struct sockaddr_in {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    struct in_addr _field4;
    char _field5[8];
};

struct sockaddr_in6 {
    unsigned char _field1;
    unsigned char _field2;
    unsigned short _field3;
    unsigned int _field4;
    struct in6_addr _field5;
    unsigned int _field6;
};

struct sockaddr_un {
    unsigned char _field1;
    unsigned char _field2;
    char _field3[104];
};

struct tm {
    int tm_sec;
    int tm_min;
    int tm_hour;
    int tm_mday;
    int tm_mon;
    int tm_year;
    int tm_wday;
    int tm_yday;
    int tm_isdst;
    long long tm_gmtoff;
    char *tm_zone;
};

struct z_stream_s {
    char *next_in;
    unsigned int avail_in;
    unsigned long long total_in;
    char *next_out;
    unsigned int avail_out;
    unsigned long long total_out;
    char *msg;
    struct internal_state *state;
    CDUnknownFunctionPointerType zalloc;
    CDUnknownFunctionPointerType zfree;
    void *opaque;
    int data_type;
    unsigned long long adler;
    unsigned long long reserved;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned long long _field1;
    id *_field2;
    unsigned long long *_field3;
    unsigned long long _field4[5];
} CDStruct_70511ce9;

typedef struct {
    void *_field1;
    unsigned int _field2;
} CDStruct_f8bc7150;

typedef struct {
    unsigned int dataSourceMenuItem:1;
    unsigned int dataSourceMenuTitles:1;
    unsigned int dataSourceViewController:1;
    unsigned int viewControllerDidAppear:1;
    unsigned int viewControllerDidDisappear:1;
    unsigned int shouldManualForwardAppearanceMethods:1;
} CDStruct_68530ea8;

typedef struct {
    double red;
    double green;
    double blue;
    double alph;
} CDStruct_106e0edc;

typedef struct {
    long long version;
    void *info;
    CDUnknownFunctionPointerType retain;
    CDUnknownFunctionPointerType release;
    CDUnknownFunctionPointerType copyDescription;
} CDStruct_4210025a;

typedef struct {
    long long _field1;
    int _field2;
} CDStruct_87dc826d;

