//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseWebPageViewController.h"

@interface CIBNPurchaseWebViewController : BaseWebPageViewController
{
}

+ (id)purchaseWebPage;
- (void)notifyStateWith:(id)arg1;

@end

