//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CleanCacheProgressEvent : NSObject
{
    NSString *_filePath;
    long long _size;
    long long _status;
    long long _speed;
}

+ (id)eventWithFilePath:(id)arg1 size:(long long)arg2 status:(long long)arg3 speed:(long long)arg4;
@property(nonatomic) long long speed; // @synthesize speed=_speed;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) long long size; // @synthesize size=_size;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
- (void).cxx_destruct;
- (id)initWithFilePath:(id)arg1 size:(long long)arg2 status:(long long)arg3 speed:(long long)arg4;

@end

