//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DataTransformer : NSObject
{
}

+ (void)showDefaultDurationWariningTitle:(id)arg1;
+ (void)showToastWithTitle:(id)arg1 duration:(double)arg2;
+ (void)showWariningTitle:(id)arg1 andCheatsheet:(id)arg2 andDuration:(double)arg3;
+ (void)showWariningTitle:(id)arg1 andCheatsheet:(id)arg2;
+ (id)convertNumberToStringIfNumber:(id)arg1;
+ (id)getStringObj:(id)arg1 byName:(id)arg2;
+ (id)getNumberObj:(id)arg1 byName:(id)arg2;
+ (id)getDeviceFromSetting:(id)arg1;
+ (id)getAppVersion:(id)arg1;
+ (id)getAppSort:(id)arg1;
+ (id)getAppType:(id)arg1;
+ (id)getAppName:(id)arg1;
+ (id)getAppPKG:(id)arg1;
+ (id)getAppDir:(id)arg1;

@end

