//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "Reachability.h"

@interface FakeReachability : Reachability
{
    long long _currentReachabilityStatus;
}

@property(nonatomic) long long currentReachabilityStatus; // @synthesize currentReachabilityStatus=_currentReachabilityStatus;

@end

