//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "SDCycleScrollViewDelegate.h"

@class NSString, SDCycleScrollView, WKVideoFindModel;

@interface FindScrollBannerTableViewCell : UITableViewCell <SDCycleScrollViewDelegate>
{
    id <WKViedoFindViewControllerBannerActionDelegate> _findviewControllerBannerActionDelegate;
    SDCycleScrollView *_bannerView;
    WKVideoFindModel *_wkVideoFindModel;
}

@property(retain, nonatomic) WKVideoFindModel *wkVideoFindModel; // @synthesize wkVideoFindModel=_wkVideoFindModel;
@property(retain, nonatomic) SDCycleScrollView *bannerView; // @synthesize bannerView=_bannerView;
@property(nonatomic) __weak id <WKViedoFindViewControllerBannerActionDelegate> findviewControllerBannerActionDelegate; // @synthesize findviewControllerBannerActionDelegate=_findviewControllerBannerActionDelegate;
- (void).cxx_destruct;
- (void)cycleScrollView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)setDataModel:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

