//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface FindLatticeCollectionViewCell : UICollectionViewCell
{
    UIImageView *_coverImageView;
    UILabel *_markLabel;
    UILabel *_desLabel;
    UILabel *_nameLabel;
    NSLayoutConstraint *_coverImageViewConstraint;
}

@property(nonatomic) __weak NSLayoutConstraint *coverImageViewConstraint; // @synthesize coverImageViewConstraint=_coverImageViewConstraint;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *desLabel; // @synthesize desLabel=_desLabel;
@property(nonatomic) __weak UILabel *markLabel; // @synthesize markLabel=_markLabel;
@property(nonatomic) __weak UIImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

