//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSTimer, UIImageView, UILabel, UIView, WKDianboChosenModel, WKVideoFindModel;

@interface FindTipsTableViewCell : UITableViewCell
{
    UILabel *_tipOneLabel;
    UILabel *_tipTwoLabel;
    UIView *_tipView;
    UIImageView *_tipRightImageView;
    UIImageView *_tipLeftImageVIew;
    UIView *_tipsContentView;
    id <FindTipsTableViewCellDelegate> _findTipstableViewCellDelegate;
    NSTimer *_timer;
    WKVideoFindModel *_findModel;
    WKDianboChosenModel *_currentChoseModel;
    long long _count;
    long long _arrayIndex;
}

@property(nonatomic) long long arrayIndex; // @synthesize arrayIndex=_arrayIndex;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(retain, nonatomic) WKDianboChosenModel *currentChoseModel; // @synthesize currentChoseModel=_currentChoseModel;
@property(retain, nonatomic) WKVideoFindModel *findModel; // @synthesize findModel=_findModel;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) __weak id <FindTipsTableViewCellDelegate> findTipstableViewCellDelegate; // @synthesize findTipstableViewCellDelegate=_findTipstableViewCellDelegate;
@property(nonatomic) __weak UIView *tipsContentView; // @synthesize tipsContentView=_tipsContentView;
@property(nonatomic) __weak UIImageView *tipLeftImageVIew; // @synthesize tipLeftImageVIew=_tipLeftImageVIew;
@property(nonatomic) __weak UIImageView *tipRightImageView; // @synthesize tipRightImageView=_tipRightImageView;
@property(retain, nonatomic) UIView *tipView; // @synthesize tipView=_tipView;
@property(retain, nonatomic) UILabel *tipTwoLabel; // @synthesize tipTwoLabel=_tipTwoLabel;
@property(retain, nonatomic) UILabel *tipOneLabel; // @synthesize tipOneLabel=_tipOneLabel;
- (void).cxx_destruct;
- (void)tipTapAction:(id)arg1;
- (void)animationAction;
- (void)setDataModel:(id)arg1;
- (void)awakeFromNib;

@end

