//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class NSMutableArray, StyledPageControl;

@interface GCPagedScrollView : UIScrollView
{
    NSMutableArray *views;
    StyledPageControl *pageControl;
    id <GCPagedScrollDelegate> _gcdelegate;
}

@property(nonatomic) __weak id <GCPagedScrollDelegate> gcdelegate; // @synthesize gcdelegate=_gcdelegate;
@property(retain, nonatomic) StyledPageControl *pageControl; // @synthesize pageControl;
- (void).cxx_destruct;
- (void)setPage:(unsigned long long)arg1 animated:(_Bool)arg2;
@property(nonatomic) unsigned long long page;
@property(readonly, nonatomic) NSMutableArray *views; // @synthesize views;
- (void)setContentOffset:(struct CGPoint)arg1;
- (void)changePage:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutSubviews;
- (void)updateViewPositionAndPageControl;
- (void)removeAllContentSubviews;
- (void)removeContentSubviewAtIndex:(unsigned long long)arg1;
- (void)removeContentSubview:(id)arg1;
- (void)addContentSubviewsFromArray:(id)arg1;
- (void)addContentSubview:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addContentSubview:(id)arg1;
- (void)setPagingEnabled:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withPageControl:(_Bool)arg2;

@end

