//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSTimer, NewVideoInfoModel, UIImageView, UILabel;

@interface GlobalRecommendVideoTableViewCell : UITableViewCell
{
    NSTimer *_timer;
    int _counter;
    NewVideoInfoModel *_leftModel;
    NewVideoInfoModel *_centerModel;
    NewVideoInfoModel *_rightModel;
    UIImageView *_leftBannerImg;
    UIImageView *_centerBannerImg;
    UIImageView *_rightBannerImg;
    UILabel *_leftTitleLabel;
    UILabel *_centerTitleLabel;
    UILabel *_rightTitleLabel;
}

@property(nonatomic) __weak UILabel *rightTitleLabel; // @synthesize rightTitleLabel=_rightTitleLabel;
@property(nonatomic) __weak UILabel *centerTitleLabel; // @synthesize centerTitleLabel=_centerTitleLabel;
@property(nonatomic) __weak UILabel *leftTitleLabel; // @synthesize leftTitleLabel=_leftTitleLabel;
@property(nonatomic) __weak UIImageView *rightBannerImg; // @synthesize rightBannerImg=_rightBannerImg;
@property(nonatomic) __weak UIImageView *centerBannerImg; // @synthesize centerBannerImg=_centerBannerImg;
@property(nonatomic) __weak UIImageView *leftBannerImg; // @synthesize leftBannerImg=_leftBannerImg;
- (void).cxx_destruct;
- (void)imageViewTap:(id)arg1;
- (void)startTimer:(double)arg1;
- (void)resetCounter;
- (void)setCellDataSource:(id)arg1 withCenter:(id)arg2 withRight:(id)arg3;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setImageViewGesture;
- (void)awakeFromNib;

@end

