//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface IbKey : NSObject
{
    _Bool _needCheckIbVer;
    int _androidValue;
    int _ibVal;
    int _index;
    int _action;
    IbKey *UP;
    IbKey *DOWN;
    IbKey *LEFT;
    IbKey *RIGHT;
    IbKey *ENTER;
    IbKey *ESC;
    IbKey *HOME;
    IbKey *MENU;
    IbKey *POWER;
    IbKey *VOLDOWN;
    IbKey *VOLUP;
    NSString *_keyName;
}

+ (int)getProtocolKeyCodeForAndroidKeyCode:(int)arg1;
+ (id)initWithName:(id)arg1 withIndex:(int)arg2 withIbValue:(int)arg3 withAndroidValue:(int)arg4 withAction:(int)arg5 withCheck:(_Bool)arg6;
@property(nonatomic) _Bool needCheckIbVer; // @synthesize needCheckIbVer=_needCheckIbVer;
@property(nonatomic) int action; // @synthesize action=_action;
@property(nonatomic) int index; // @synthesize index=_index;
@property(nonatomic) int ibVal; // @synthesize ibVal=_ibVal;
@property(nonatomic) int androidValue; // @synthesize androidValue=_androidValue;
@property(retain, nonatomic) NSString *keyName; // @synthesize keyName=_keyName;
@property(retain, nonatomic) IbKey *VOLUP; // @synthesize VOLUP;
@property(retain, nonatomic) IbKey *VOLDOWN; // @synthesize VOLDOWN;
@property(retain, nonatomic) IbKey *POWER; // @synthesize POWER;
@property(retain, nonatomic) IbKey *MENU; // @synthesize MENU;
@property(retain, nonatomic) IbKey *HOME; // @synthesize HOME;
@property(retain, nonatomic) IbKey *ESC; // @synthesize ESC;
@property(retain, nonatomic) IbKey *ENTER; // @synthesize ENTER;
@property(retain, nonatomic) IbKey *RIGHT; // @synthesize RIGHT;
@property(retain, nonatomic) IbKey *LEFT; // @synthesize LEFT;
@property(retain, nonatomic) IbKey *DOWN; // @synthesize DOWN;
@property(retain, nonatomic) IbKey *UP; // @synthesize UP;
- (void).cxx_destruct;

@end

