//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIScrollViewDelegate.h"

@class GCPagedScrollView, NSArray, NSString, UIButton;

@interface IntroViewController : UIViewController <UIScrollViewDelegate>
{
    GCPagedScrollView *pagedScrollView;
    NSArray *scrollImageArray;
    UIButton *checkButton;
}

@property(retain, nonatomic) UIButton *checkButton; // @synthesize checkButton;
@property(retain, nonatomic) NSArray *scrollImageArray; // @synthesize scrollImageArray;
@property(retain, nonatomic) GCPagedScrollView *pagedScrollView; // @synthesize pagedScrollView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)skipAction;
- (void)scrollViewDidScroll:(id)arg1;
- (void)initScrollView;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

