//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GCDAsyncSocket, WKDeviceItem;

@interface KonkaTCPWriteThread : NSObject
{
    GCDAsyncSocket *_socket;
    WKDeviceItem *_currentDevice;
    CDUnknownBlockType _successBlock;
}

- (void).cxx_destruct;
- (void)disConnect;
- (_Bool)isSocketConnected;
- (_Bool)needChange:(id)arg1;
- (void)onSocket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)onSocket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)sendMsg:(id)arg1;
- (void)willWorkWithDevice:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)releaseResources;
- (void)onWillEnterForground;
- (void)onEnterBackground;
- (void)dealloc;
- (id)init;

@end

