//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSNumber, NSString;

@interface MessageCenter : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *bannerUrlString; // @dynamic bannerUrlString;
@property(copy, nonatomic) NSString *desc; // @dynamic desc;
@property(copy, nonatomic) NSNumber *indexTag; // @dynamic indexTag;
@property(copy, nonatomic) NSNumber *messageType; // @dynamic messageType;
@property(copy, nonatomic) NSString *notifyId; // @dynamic notifyId;
@property(copy, nonatomic) NSString *showid; // @dynamic showid;
@property(copy, nonatomic) NSString *time; // @dynamic time;
@property(copy, nonatomic) NSNumber *timestamp; // @dynamic timestamp;
@property(copy, nonatomic) NSString *title; // @dynamic title;
@property(copy, nonatomic) NSNumber *unRead; // @dynamic unRead;
@property(copy, nonatomic) NSString *webUri; // @dynamic webUri;

@end

