//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MiPushServerSDKController : NSObject
{
    id <MiPushServerSDKDelegate> iDelegate;
    struct dispatch_queue_s *objTaskQueue;
}

+ (id)sharedMiPushServerSDKSingleton;
- (void)appendPlatform:(id)arg1 message:(id)arg2;
- (void)miPushServerRequestResult:(int)arg1 selector:(id)arg2 data:(id)arg3;
- (void)getSendStatsWithStart:(id)arg1 end:(id)arg2;
- (void)sendWithTopic:(id)arg1 message:(id)arg2;
- (void)sendWithAliasList:(id)arg1 message:(id)arg2;
- (void)sendWithAlias:(id)arg1 message:(id)arg2;
- (void)sendWithRegidList:(id)arg1 message:(id)arg2;
- (void)sendWithRegid:(id)arg1 message:(id)arg2;
- (void)syncSDKFlag;
- (struct dispatch_queue_s *)getTaskQueue;
- (void)setDelegate:(id)arg1;
- (void)dealloc;

@end

