//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MiPushXMPPModule.h"

@class MiPushXMPPJID, MiPushXMPPPing, NSString;

@interface MiPushXMPPAutoPing : MiPushXMPPModule
{
    double pingInterval;
    double pingTimeout;
    MiPushXMPPJID *targetJID;
    NSString *targetJIDStr;
    double lastReceiveTime;
    struct dispatch_source_s *pingIntervalTimer;
    _Bool awaitingPingResponse;
    MiPushXMPPPing *xmppPing;
}

- (void)xmppStreamDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)xmppStream:(id)arg1 didReceivePresence:(id)arg2;
- (void)xmppStream:(id)arg1 didReceiveMessage:(id)arg2;
- (_Bool)xmppStream:(id)arg1 didReceiveIQ:(id)arg2;
- (void)xmppStreamDidAuthenticate:(id)arg1;
- (void)xmppPing:(id)arg1 didNotReceivePong:(id)arg2 dueToTimeout:(double)arg3;
- (void)xmppPing:(id)arg1 didReceivePong:(id)arg2 withRTT:(double)arg3;
- (void)stopPingIntervalTimer;
- (void)startPingIntervalTimer;
- (void)updatePingIntervalTimer;
- (void)handlePingIntervalTimerFire;
@property(readonly) double lastReceiveTime;
@property(retain) MiPushXMPPJID *targetJID;
@property double pingTimeout;
@property double pingInterval;
- (void)dealloc;
- (void)deactivate;
- (_Bool)activate:(id)arg1;
- (id)initWithDispatchQueue:(struct dispatch_queue_s *)arg1;
- (id)init;

@end

