//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MiPushServerSDK : NSObject
{
}

+ (void)getSendStatsWithStart:(id)arg1 end:(id)arg2;
+ (void)sendWithTopic:(id)arg1 message:(id)arg2;
+ (void)sendWithAliases:(id)arg1 message:(id)arg2;
+ (void)sendWithAlias:(id)arg1 message:(id)arg2;
+ (void)sendWithRegids:(id)arg1 message:(id)arg2;
+ (void)sendWithRegid:(id)arg1 message:(id)arg2;
+ (void)registerMiPushServer:(id)arg1;

@end

