//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MiPushSDKPreferenceUtil : NSObject
{
}

+ (id)getDictionaryWithKey:(id)arg1;
+ (void)setKey:(id)arg1 dictionaryValue:(id)arg2;
+ (id)getArrayWithKey:(id)arg1;
+ (void)setKey:(id)arg1 removeArrayItem:(id)arg2;
+ (void)setKey:(id)arg1 appendArrayItem:(id)arg2;
+ (void)setKey:(id)arg1 arrayValue:(id)arg2;
+ (double)getDoubleWithKey:(id)arg1;
+ (void)setKey:(id)arg1 doubleValue:(double)arg2;
+ (id)getStringWithKey:(id)arg1;
+ (void)setKey:(id)arg1 stringValue:(id)arg2;

@end

