//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSManagedObjectContext;

@interface ModelHelper : NSObject
{
    NSManagedObjectContext *_managedObjectContext;
}

+ (id)sharedHelper;
@property(retain, nonatomic) NSManagedObjectContext *managedObjectContext; // @synthesize managedObjectContext=_managedObjectContext;
- (void).cxx_destruct;
- (id)findAllDataWithEntityName:(id)arg1;
- (void)checkHasUnreadMessage;
- (void)removeAllMessageHistory;
- (_Bool)findMessageBynotifyId:(id)arg1;
- (_Bool)findMessageAndRemoveByMessageUrl:(id)arg1;
- (_Bool)updateMessageStatus:(id)arg1;
- (id)findAllMessageHistory;
- (void)addMessageHistory:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)getAllTodayExtensionApp;
- (_Bool)removeTodayExtensionAppWithPkg:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)addTodayExtensionApp:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)removeAllSearchHistory;
- (id)findAllSearchHistory;
- (long long)findLastSearchSort:(id)arg1;
- (_Bool)findHistoryAndRemoveByText:(id)arg1;
- (void)checkHistoryFreeCount;
- (void)addSearchHistory:(id)arg1 withSearchType:(id)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void)pushVodHistory:(id)arg1 withModel:(id)arg2;
- (void)populateVodHistory:(id)arg1 withDict:(id)arg2;
- (void)removeVodHistoryBySort:(long long)arg1;
- (void)removeAllVodHistory;
- (id)findHistoryByVid:(id)arg1;
- (_Bool)findVodAndRemoveByVid:(id)arg1;
- (long long)findLastVodSort;
- (id)findAllVodHistory;
- (id)findAllWebSearchHistory;
- (id)addWebSearchHistory:(id)arg1 type:(long long)arg2;
- (void)addVodHistory:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)findAllZhiboHistoryByType:(id)arg1;
- (long long)findLastZhiboSortByType:(id)arg1;
- (void)removeZhiBoHistoryBySort:(long long)arg1;
- (_Bool)findZhiboHistoryAndUpdateByName:(id)arg1;
- (void)pushZhiBoHistory:(id)arg1 withModel:(id)arg2;
- (void)populateZhiboHistory:(id)arg1 withDict:(id)arg2;
- (void)checkHDLiveHistoryCount;
- (void)addZhiboHistory:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)updateSettingWithDevice:(id)arg1;
- (void)populateSetting:(id)arg1 withDevice:(id)arg2;
- (id)findOnlySetting;
- (void)populateApp:(id)arg1 withDict:(id)arg2;
- (void)deletaUpAppByPKG:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)populateHiddenApp:(id)arg1 withDict:(id)arg2;
- (id)findHiddenStatusByPKG:(id)arg1;
- (void)deleteHiddenAppByPKG:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)addHiddenAppByAppData:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)findAllHiddenAppsByType:(id)arg1;
- (void)addUpAppByAppData:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)findUpStatusByPKG:(id)arg1;
- (long long)findLastAppsSortByType:(id)arg1;
- (long long)findLastHiddenAppsSortByType:(id)arg1;
- (id)findAllAppsByType:(id)arg1;

@end

