//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIImage;

@interface NewVideoInfoModel : NSObject
{
    NSString *_name;
    NSString *_subhead;
    NSString *_cover;
    NSString *_wkid;
    NSString *_definition;
    NSString *_grade;
    NSString *_updateto;
    NSString *_from;
    NSString *_intent;
    NSString *_icon;
    NSString *_df_icon;
    NSString *_ad;
    NSString *_director;
    NSString *_showtime;
    NSString *_area;
    NSString *_type;
    NSString *_tag;
    NSString *_unum;
    NSString *_starring;
    UIImage *_presetImage;
    NSString *_openType;
    NSString *_webUrl;
}

@property(retain, nonatomic) NSString *webUrl; // @synthesize webUrl=_webUrl;
@property(retain, nonatomic) NSString *openType; // @synthesize openType=_openType;
@property(retain, nonatomic) UIImage *presetImage; // @synthesize presetImage=_presetImage;
@property(retain, nonatomic) NSString *starring; // @synthesize starring=_starring;
@property(retain, nonatomic) NSString *unum; // @synthesize unum=_unum;
@property(retain, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *area; // @synthesize area=_area;
@property(retain, nonatomic) NSString *showtime; // @synthesize showtime=_showtime;
@property(retain, nonatomic) NSString *director; // @synthesize director=_director;
@property(retain, nonatomic) NSString *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) NSString *df_icon; // @synthesize df_icon=_df_icon;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *intent; // @synthesize intent=_intent;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *updateto; // @synthesize updateto=_updateto;
@property(retain, nonatomic) NSString *grade; // @synthesize grade=_grade;
@property(retain, nonatomic) NSString *definition; // @synthesize definition=_definition;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(retain, nonatomic) NSString *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) NSString *subhead; // @synthesize subhead=_subhead;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)pushVideoDetailController;

@end

