//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseControlView.h"

@class UIImageView, UILabel;

@interface OmnidirectionalControl : WKBaseControlView
{
    struct CGPoint _startTouch;
    struct CGPoint _endTouch;
    UIImageView *_touchView;
    UIImageView *_bgView;
    UILabel *_fristTipLbl;
    UILabel *_secTipLbl;
}

@property(retain, nonatomic) UILabel *secTipLbl; // @synthesize secTipLbl=_secTipLbl;
@property(retain, nonatomic) UILabel *fristTipLbl; // @synthesize fristTipLbl=_fristTipLbl;
- (void).cxx_destruct;
- (long long)getContrlKeyCodeFromDirection:(long long)arg1;
- (void)bgAnimation:(long long)arg1;
- (void)tapDoubleAction:(id)arg1;
- (void)tapSingleAction:(id)arg1;
- (void)panGesture:(id)arg1;
- (void)initView:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

