//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString;

@interface PushMetaInfo : NSObject <NSCoding>
{
    NSString *__id;
    long long __messageTs;
    NSString *__topic;
    NSString *__title;
    NSString *__description;
    int __notifyType;
    NSString *__url;
    int __passThrough;
    int __notifyId;
    NSDictionary *__extra;
    _Bool __id_isset;
    _Bool __messageTs_isset;
    _Bool __topic_isset;
    _Bool __title_isset;
    _Bool __description_isset;
    _Bool __notifyType_isset;
    _Bool __url_isset;
    _Bool __passThrough_isset;
    _Bool __notifyId_isset;
    _Bool __extra_isset;
}

- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetExtra;
- (_Bool)extraIsSet;
@property(retain, nonatomic, getter=extra, setter=setExtra:) NSDictionary *extra;
- (void)unsetNotifyId;
- (_Bool)notifyIdIsSet;
@property(nonatomic, getter=notifyId, setter=setNotifyId:) int notifyId;
- (void)unsetPassThrough;
- (_Bool)passThroughIsSet;
@property(nonatomic, getter=passThrough, setter=setPassThrough:) int passThrough;
- (void)unsetUrl;
- (_Bool)urlIsSet;
@property(retain, nonatomic, getter=url, setter=setUrl:) NSString *url;
- (void)unsetNotifyType;
- (_Bool)notifyTypeIsSet;
@property(nonatomic, getter=notifyType, setter=setNotifyType:) int notifyType;
- (void)unsetDescription;
- (_Bool)descriptionIsSet;
@property(retain, nonatomic, getter=description, setter=setDescription:) NSString *description;
- (void)unsetTitle;
- (_Bool)titleIsSet;
@property(retain, nonatomic, getter=title, setter=setTitle:) NSString *title;
- (void)unsetTopic;
- (_Bool)topicIsSet;
@property(retain, nonatomic, getter=topic, setter=setTopic:) NSString *topic;
- (void)unsetMessageTs;
- (_Bool)messageTsIsSet;
@property(nonatomic, getter=messageTs, setter=setMessageTs:) long long messageTs;
- (void)unsetId;
- (_Bool)idIsSet;
@property(retain, nonatomic, getter=id, setter=setId:) NSString *id;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithId:(id)arg1 messageTs:(long long)arg2 topic:(id)arg3 title:(id)arg4 description:(id)arg5 notifyType:(int)arg6 url:(id)arg7 passThrough:(int)arg8 notifyId:(int)arg9 extra:(id)arg10;

@end

