//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "SettingSwitchCellViewDelegate.h"

@class NSString, UILabel, UISwitch;

@interface SettingSwitchCellView : UITableViewCell <SettingSwitchCellViewDelegate>
{
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UISwitch *_theSwitch;
    id <SettingSwitchCellViewDelegate> _delegate;
}

@property(nonatomic) __weak id <SettingSwitchCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cellViewClicked:(id)arg1;
- (void)switchChanged:(id)arg1;
- (void)setContentWithData:(id)arg1;
- (void)setCellViewDataSource:(id)arg1;
- (void)initCellView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

