//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class CAAnimation, NSMutableArray, NSString, SGSheetMenu, UITapGestureRecognizer;

@interface SGActionView : UIView <UIGestureRecognizerDelegate>
{
    SGSheetMenu *singleMenu;
    long long _style;
    NSMutableArray *_menus;
    CAAnimation *_showMenuAnimation;
    CAAnimation *_dismissMenuAnimation;
    CAAnimation *_dimingAnimation;
    CAAnimation *_lightingAnimation;
    UITapGestureRecognizer *_tapGesture;
}

+ (void)showGridMenuWithTitle:(id)arg1 itemTitles:(id)arg2 images:(id)arg3 selectedHandle:(CDUnknownBlockType)arg4;
+ (void)showSheetWithTitle:(id)arg1 itemTitles:(id)arg2 itemSubTitles:(id)arg3 selectedIndex:(long long)arg4 selectedHandle:(CDUnknownBlockType)arg5;
+ (void)showSheetWithTitle:(id)arg1 itemTitles:(id)arg2 selectedIndex:(long long)arg3 selectedHandle:(CDUnknownBlockType)arg4;
+ (void)showAlertWithTitle:(id)arg1 message:(id)arg2 leftButtonTitle:(id)arg3 rightButtonTitle:(id)arg4 selectedHandle:(CDUnknownBlockType)arg5;
+ (void)showAlertWithTitle:(id)arg1 message:(id)arg2 buttonTitle:(id)arg3 selectedHandle:(CDUnknownBlockType)arg4;
+ (id)sharedSheetMenu;
+ (id)sharedActionView;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) CAAnimation *lightingAnimation; // @synthesize lightingAnimation=_lightingAnimation;
@property(retain, nonatomic) CAAnimation *dimingAnimation; // @synthesize dimingAnimation=_dimingAnimation;
@property(retain, nonatomic) CAAnimation *dismissMenuAnimation; // @synthesize dismissMenuAnimation=_dismissMenuAnimation;
@property(retain, nonatomic) CAAnimation *showMenuAnimation; // @synthesize showMenuAnimation=_showMenuAnimation;
@property(retain, nonatomic) NSMutableArray *menus; // @synthesize menus=_menus;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) SGSheetMenu *singleMenu; // @synthesize singleMenu;
- (void).cxx_destruct;
- (void)setOneMenuAnimation:(_Bool)arg1;
- (void)showSheetWithTitle:(id)arg1 itemTitles:(id)arg2 selectedIndex:(long long)arg3 selectedHandle:(CDUnknownBlockType)arg4;
- (void)updateSheetTitles:(id)arg1;
- (void)dismissMenu:(id)arg1 Animated:(_Bool)arg2;
- (void)setMenu:(id)arg1 animation:(_Bool)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)tapAction:(id)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

