//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SGBaseMenu.h"

@class NSMutableArray, UILabel;

@interface SGAlertMenu : SGBaseMenu
{
    UILabel *_titleLabel;
    UILabel *_messageLabel;
    NSMutableArray *_actionButtons;
    CDUnknownBlockType _actionHandle;
}

@property(copy, nonatomic) CDUnknownBlockType actionHandle; // @synthesize actionHandle=_actionHandle;
@property(retain, nonatomic) NSMutableArray *actionButtons; // @synthesize actionButtons=_actionButtons;
@property(retain, nonatomic) UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)tapAction:(id)arg1;
- (void)triggerSelectedAction:(CDUnknownBlockType)arg1;
- (void)layoutSubviews;
- (void)setStyle:(long long)arg1;
- (void)setupWithTitle:(id)arg1 message:(id)arg2 actionTitles:(id)arg3;
- (id)initWithTitle:(id)arg1 message:(id)arg2 buttonTitles:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

