//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface SGBaseMenu : UIView
{
    long long _style;
    _Bool _roundedCorner;
}

@property(nonatomic) _Bool roundedCorner; // @synthesize roundedCorner=_roundedCorner;
@property(nonatomic) long long style; // @synthesize style=_style;
- (_Bool)nicePerformance;
- (id)initWithFrame:(struct CGRect)arg1;

@end

