//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseControlView.h"

@class SlidingMouseSubView;

@interface SlidingMouseView : WKBaseControlView
{
    SlidingMouseSubView *_slidingView;
}

- (void).cxx_destruct;
- (void)slidingDownGesture:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

