//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TTransport.h"

@class NSMutableData, NSString;

@interface TFramedTransport : NSObject <TTransport>
{
    id <TTransport> mTransport;
    NSMutableData *writeBuffer;
    NSMutableData *readBuffer;
    unsigned long long readOffset;
    unsigned char dummy_header[4];
}

- (void).cxx_destruct;
- (void)ensureReadBufferHasLength:(unsigned long long)arg1;
- (void)readFrame;
- (unsigned long long)readAll:(char *)arg1 offset:(unsigned long long)arg2 length:(unsigned long long)arg3;
- (void)write:(const char *)arg1 offset:(unsigned long long)arg2 length:(unsigned long long)arg3;
- (void)flush;
- (void)dealloc;
- (id)initWithTransport:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

