//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (NoDataPlaceholderView)
- (id)wrapNoResultView:(id)arg1 bgSize:(struct CGSize)arg2;
- (void)showNoResultView:(_Bool)arg1;
- (void)showNoResultView:(_Bool)arg1 frameInSuperView:(struct CGRect)arg2;
- (void)hideNoResultViewWithFrameInSuperView:(struct CGRect)arg1;
- (void)hideNoResultView;
- (void)showNoResultView;
- (void)setupNoResultView:(id)arg1 yOffset:(double)arg2 bgSize:(struct CGSize)arg3;
- (void)setupNoResultView:(id)arg1 yOffset:(double)arg2;
- (void)setupNoResultView:(id)arg1;
- (void)setNoResuleViewYOffset:(double)arg1;
- (double)noResuleViewYOffset;
- (void)setNoResultView:(id)arg1;
- (id)noResultView;
@end

