//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSManagedObject.h"

@class NSNumber, NSString;

@interface VideoHistory : NSManagedObject
{
}

+ (id)fetchRequest;

// Remaining properties
@property(copy, nonatomic) NSString *contentType; // @dynamic contentType;
@property(copy, nonatomic) NSString *cover; // @dynamic cover;
@property(copy, nonatomic) NSString *episode; // @dynamic episode;
@property(copy, nonatomic) NSString *intent; // @dynamic intent;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *psid; // @dynamic psid;
@property(copy, nonatomic) NSNumber *sort; // @dynamic sort;
@property(copy, nonatomic) NSString *src; // @dynamic src;
@property(copy, nonatomic) NSString *ssid; // @dynamic ssid;
@property(copy, nonatomic) NSString *subhead; // @dynamic subhead;
@property(copy, nonatomic) NSString *time; // @dynamic time;
@property(copy, nonatomic) NSNumber *timearea; // @dynamic timearea;
@property(copy, nonatomic) NSNumber *videosrc; // @dynamic videosrc;
@property(copy, nonatomic) NSString *wkid; // @dynamic wkid;

@end

