//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "NSURLConnectionDataDelegate.h"
#import "UIScrollViewDelegate.h"
#import "UIWebViewDelegate.h"
#import "VTMagicViewDataSource.h"
#import "VTMagicViewDelegate.h"

@class AppCenterBoutiqueViewController, NSArray, NSString, VTMagicController, WKAppManagerViewController, WKCategoryViewController;

@interface WebInstallViewController : BaseViewController <UIWebViewDelegate, UIScrollViewDelegate, NSURLConnectionDataDelegate, VTMagicViewDelegate, VTMagicViewDataSource>
{
    AppCenterBoutiqueViewController *_vc1;
    WKCategoryViewController *_vc2;
    WKAppManagerViewController *_vc3;
    VTMagicController *_pagerController;
    NSArray *_titleArray;
}

@property(retain, nonatomic) NSArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) VTMagicController *pagerController; // @synthesize pagerController=_pagerController;
@property(retain, nonatomic) WKAppManagerViewController *vc3; // @synthesize vc3=_vc3;
@property(retain, nonatomic) WKCategoryViewController *vc2; // @synthesize vc2=_vc2;
@property(retain, nonatomic) AppCenterBoutiqueViewController *vc1; // @synthesize vc1=_vc1;
- (void).cxx_destruct;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)magicView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2;
- (id)magicView:(id)arg1 viewControllerAtPage:(unsigned long long)arg2;
- (id)magicView:(id)arg1 menuItemAtIndex:(unsigned long long)arg2;
- (id)menuTitlesForMagicView:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

