//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubFirstViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSLayoutConstraint, NSMutableArray, NSString, UIButton, UICollectionView, UIImageView, UILabel, UIProgressView, WKDeviceInfoModel;

@interface WKAppManagerViewController : WKBaseSubFirstViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    UIImageView *_deviceImageV;
    UILabel *_deviceNameLbl;
    UILabel *_sizeTitleLbl;
    UILabel *_sizeDetailLbl;
    UIProgressView *_sizeProgressView;
    WKDeviceInfoModel *_deviceModel;
    UICollectionView *_collectionView;
    UILabel *_noConnectLbl;
    UIButton *_goSearchBtn;
    NSMutableArray *_myAppArr;
    NSMutableArray *_updateAppArr;
    NSMutableArray *_dataArr;
    NSLayoutConstraint *_deviceImageCenterYOffset;
    NSLayoutConstraint *_deviceImageHeight;
    NSLayoutConstraint *_deviceNameTop;
}

@property(nonatomic) __weak NSLayoutConstraint *deviceNameTop; // @synthesize deviceNameTop=_deviceNameTop;
@property(nonatomic) __weak NSLayoutConstraint *deviceImageHeight; // @synthesize deviceImageHeight=_deviceImageHeight;
@property(nonatomic) __weak NSLayoutConstraint *deviceImageCenterYOffset; // @synthesize deviceImageCenterYOffset=_deviceImageCenterYOffset;
@property(retain, nonatomic) NSMutableArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) NSMutableArray *updateAppArr; // @synthesize updateAppArr=_updateAppArr;
@property(retain, nonatomic) NSMutableArray *myAppArr; // @synthesize myAppArr=_myAppArr;
@property(nonatomic) __weak UIButton *goSearchBtn; // @synthesize goSearchBtn=_goSearchBtn;
@property(nonatomic) __weak UILabel *noConnectLbl; // @synthesize noConnectLbl=_noConnectLbl;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) WKDeviceInfoModel *deviceModel; // @synthesize deviceModel=_deviceModel;
@property(nonatomic) __weak UIProgressView *sizeProgressView; // @synthesize sizeProgressView=_sizeProgressView;
@property(nonatomic) __weak UILabel *sizeDetailLbl; // @synthesize sizeDetailLbl=_sizeDetailLbl;
@property(nonatomic) __weak UILabel *sizeTitleLbl; // @synthesize sizeTitleLbl=_sizeTitleLbl;
@property(nonatomic) __weak UILabel *deviceNameLbl; // @synthesize deviceNameLbl=_deviceNameLbl;
@property(nonatomic) __weak UIImageView *deviceImageV; // @synthesize deviceImageV=_deviceImageV;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)serverAppupdatelistArrived:(id)arg1;
- (void)serverApplistArrived:(id)arg1;
- (void)getServerAppUpdateList;
- (id)transformedValue:(double)arg1;
- (void)updateProgress;
- (void)updateDevieceName;
- (void)updateDeviceInfo;
- (void)goSearchDevice:(id)arg1;
- (void)loadData;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

