//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface WKAppDetailModel : NSObject
{
    NSString *_apptitle;
    NSString *_baoming;
    NSString *_appico;
    NSString *_downurl;
    NSString *_appver;
    NSString *_appsize;
    NSString *_version_code;
    NSString *_summary;
    NSString *_score;
    NSString *_piclist;
    NSArray *_mark;
}

@property(retain, nonatomic) NSArray *mark; // @synthesize mark=_mark;
@property(copy, nonatomic) NSString *piclist; // @synthesize piclist=_piclist;
@property(copy, nonatomic) NSString *score; // @synthesize score=_score;
@property(copy, nonatomic) NSString *summary; // @synthesize summary=_summary;
@property(copy, nonatomic) NSString *version_code; // @synthesize version_code=_version_code;
@property(copy, nonatomic) NSString *appsize; // @synthesize appsize=_appsize;
@property(copy, nonatomic) NSString *appver; // @synthesize appver=_appver;
@property(copy, nonatomic) NSString *downurl; // @synthesize downurl=_downurl;
@property(copy, nonatomic) NSString *appico; // @synthesize appico=_appico;
@property(copy, nonatomic) NSString *baoming; // @synthesize baoming=_baoming;
@property(copy, nonatomic) NSString *apptitle; // @synthesize apptitle=_apptitle;
- (void).cxx_destruct;
- (void)sendOpenAppMsg;
- (void)sendInstallAppMsg;

@end

