//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseProtocol.h"

@interface WKBaoFengProtocol : WKBaseProtocol
{
    long long _firstAction;
}

@property(nonatomic) long long firstAction; // @synthesize firstAction=_firstAction;
- (void)releaseResources;
- (void)openServerApp:(CDUnknownBlockType)arg1;
- (void)autoInstallServerApp:(CDUnknownBlockType)arg1;
- (_Bool)canAutoInstallServer;
- (_Bool)needChange:(id)arg1;
- (id)createKeyEvent:(int)arg1 and:(int)arg2;
- (id)getKeyEvent:(int)arg1 and:(int)arg2;
- (void)executeKeyEvent:(int)arg1 and:(int)arg2 withSuccessBlock:(CDUnknownBlockType)arg3;
- (void)sendLongKeyWithKey:(int)arg1 withAction:(int)arg2;
- (void)send:(int)arg1 withAction:(int)arg2;
- (void)sendProtocolKey:(int)arg1;
- (_Bool)willWorkWithKey:(int)arg1;
- (void)willWorkWithDevice:(id)arg1 WithSuccessBlock:(CDUnknownBlockType)arg2;

@end

