//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionView.h"

@class NSString;

@interface WKBaseVideoCollectionView : UICollectionView
{
    NSString *_videoType;
}

@property(copy, nonatomic) NSString *videoType; // @synthesize videoType=_videoType;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1 collectionViewLayout:(id)arg2;
- (void)setVideoModel:(id)arg1;

@end

