//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKBigTreeADParamModel : NSObject
{
    NSString *_adid;
    NSString *_sid;
    NSString *_w;
    NSString *_h;
    NSString *_appv;
    NSString *_idfa;
    NSString *_osv;
    NSString *_devtype;
    NSString *_vendor;
    NSString *_model;
    NSString *_ip;
    NSString *_conntype;
    NSString *_carrier;
    NSString *_sw;
    NSString *_sh;
    NSString *_v;
}

+ (id)sharedBigTreeADParamModel;
@property(copy, nonatomic) NSString *v; // @synthesize v=_v;
@property(copy, nonatomic) NSString *sh; // @synthesize sh=_sh;
@property(copy, nonatomic) NSString *sw; // @synthesize sw=_sw;
@property(copy, nonatomic) NSString *carrier; // @synthesize carrier=_carrier;
@property(copy, nonatomic) NSString *conntype; // @synthesize conntype=_conntype;
@property(copy, nonatomic) NSString *ip; // @synthesize ip=_ip;
@property(copy, nonatomic) NSString *model; // @synthesize model=_model;
@property(copy, nonatomic) NSString *vendor; // @synthesize vendor=_vendor;
@property(copy, nonatomic) NSString *devtype; // @synthesize devtype=_devtype;
@property(copy, nonatomic) NSString *osv; // @synthesize osv=_osv;
@property(copy, nonatomic) NSString *idfa; // @synthesize idfa=_idfa;
@property(copy, nonatomic) NSString *appv; // @synthesize appv=_appv;
@property(copy, nonatomic) NSString *h; // @synthesize h=_h;
@property(copy, nonatomic) NSString *w; // @synthesize w=_w;
@property(copy, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(copy, nonatomic) NSString *adid; // @synthesize adid=_adid;
- (void).cxx_destruct;
- (id)randomAdid;
- (id)paramDict;

@end

