//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface WKBigTreeCooperationADModel : NSObject
{
    _Bool _hasTracked;
    NSString *_adid;
    NSString *_type;
    NSString *_clickurl;
    NSString *_action;
    NSArray *_imptracker;
    NSArray *_imageurl;
}

+ (void)getBigTreeCooperationAD:(CDUnknownBlockType)arg1;
+ (id)generateBigTreeCooperationADUrl;
@property(nonatomic) _Bool hasTracked; // @synthesize hasTracked=_hasTracked;
@property(retain, nonatomic) NSArray *imageurl; // @synthesize imageurl=_imageurl;
@property(retain, nonatomic) NSArray *imptracker; // @synthesize imptracker=_imptracker;
@property(copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *clickurl; // @synthesize clickurl=_clickurl;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *adid; // @synthesize adid=_adid;
- (void).cxx_destruct;
- (void)trackADClick;
- (void)trackADShown;
- (void)routeWithClickUrl;

@end

