//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface WKCheckButton : UIButton
{
    _Bool _checked;
    id _userInfo;
    id <WKCheckBoxDelegate> _delegate;
}

@property(retain, nonatomic) id userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) _Bool checked; // @synthesize checked=_checked;
@property(nonatomic) id <WKCheckBoxDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGRect)titleRectForContentRect:(struct CGRect)arg1;
- (struct CGRect)imageRectForContentRect:(struct CGRect)arg1;
- (void)checkboxBtnChecked;
- (id)initWithDelegate:(id)arg1;

@end

