//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WKCIBNVipVideoSubDataItemModel;

@interface WKCIBNVipVideoItemModel : NSObject
{
    WKCIBNVipVideoSubDataItemModel *_data;
    NSString *_videoType;
}

@property(copy, nonatomic) NSString *videoType; // @synthesize videoType=_videoType;
@property(retain, nonatomic) WKCIBNVipVideoSubDataItemModel *data; // @synthesize data=_data;
- (void).cxx_destruct;

@end

