//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, WKCIBNVipVideoMoreModel, WKCIBNVipVideoTitleModel;

@interface WKCIBNVipVideoSubDataItemModel : NSObject
{
    WKCIBNVipVideoTitleModel *_title;
    WKCIBNVipVideoMoreModel *_more;
    NSArray *_list;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(retain, nonatomic) WKCIBNVipVideoMoreModel *more; // @synthesize more=_more;
@property(retain, nonatomic) WKCIBNVipVideoTitleModel *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

