//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, WKCIBNVipVideoBannerModel;

@interface WKCIBNVipVideoModel : NSObject
{
    WKCIBNVipVideoBannerModel *_banner;
    NSArray *_item;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSArray *item; // @synthesize item=_item;
@property(retain, nonatomic) WKCIBNVipVideoBannerModel *banner; // @synthesize banner=_banner;
- (void).cxx_destruct;

@end

