//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WKCIBNHelper : NSObject
{
    _Bool _isInit;
}

+ (id)sharedHelper;
@property(nonatomic) _Bool isInit; // @synthesize isInit=_isInit;
- (_Bool)reqVideoWithProductID:(id)arg1 programCode:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (_Bool)reqTrailVideoWithProductID:(id)arg1 seriesCode:(id)arg2 programCode:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (_Bool)requestPayWithProductID:(id)arg1 seriesCode:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (_Bool)videoAuthWithProductID:(id)arg1 seriesCode:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (_Bool)logIn:(CDUnknownBlockType)arg1;
- (_Bool)SDKinit:(CDUnknownBlockType)arg1;

@end

