//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel, UIView;

@interface WKCIBNDetailDiscussCell : UITableViewCell
{
    UILabel *_discussTitleLabel;
    UILabel *_discussTitleRightLabel;
    UIView *_discussionsContainerView;
}

@property(nonatomic) __weak UIView *discussionsContainerView; // @synthesize discussionsContainerView=_discussionsContainerView;
@property(nonatomic) __weak UILabel *discussTitleRightLabel; // @synthesize discussTitleRightLabel=_discussTitleRightLabel;
@property(nonatomic) __weak UILabel *discussTitleLabel; // @synthesize discussTitleLabel=_discussTitleLabel;
- (void).cxx_destruct;
- (void)configCellWithModel:(id)arg1;
- (void)awakeFromNib;

@end

