//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UILabel;

@interface WKCIBNEpisodeCollectionViewCell : UICollectionViewCell
{
    UILabel *_episodeLbl;
}

@property(nonatomic) __weak UILabel *episodeLbl; // @synthesize episodeLbl=_episodeLbl;
- (void).cxx_destruct;
- (void)updateSelectedCell:(_Bool)arg1;
- (void)setEpisodeCount:(id)arg1;
- (void)awakeFromNib;

@end

