//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WKCIBNVipVideoRouterModel;

@interface WKCIBNVipVideoMoreModel : NSObject
{
    NSString *_name;
    NSString *_rightName;
    WKCIBNVipVideoRouterModel *_router;
}

@property(retain, nonatomic) WKCIBNVipVideoRouterModel *router; // @synthesize router=_router;
@property(copy, nonatomic) NSString *rightName; // @synthesize rightName=_rightName;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

