//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WKClientUrlUtil : NSObject
{
}

+ (id)getAppstoreJingpinModelApp;
+ (id)getCIBNSearchResultWithKey:(id)arg1;
+ (id)getAppStoreJingPin;
+ (id)getCIBNHotSearch;
+ (id)getAppAdConfigUrl;
+ (id)getCIBNVipVideoDetailUrlWithWKID:(id)arg1 userId:(id)arg2;
+ (id)getCIBNVipVideoUrl;
+ (id)getDianBoSpecialUrl;
+ (id)getVideoByTypesUrl;
+ (id)getVideoTypesUrl;
+ (id)getVideoFindUrl;
+ (id)getDianboChosenUrl;
+ (id)getMyVideoHistoryUrlWithAction:(long long)arg1;
+ (id)getMyCollectUrl;
+ (id)getCollectVideoUrlWKid:(id)arg1 isCollect:(_Bool)arg2;
+ (id)getCancelDianzanUrlWithCid:(id)arg1;
+ (id)getDianZanUrlWithCid:(id)arg1;
+ (id)getAllChildCommentUrlWithWkid:(id)arg1 cid:(id)arg2;
+ (id)getSendCommentUrl;
+ (id)getCommentUrlWkid:(id)arg1;
+ (_Bool)isUrl:(id)arg1;
+ (id)getSplashADUrl;
+ (id)getStayTunnedUrl;
+ (id)getMeiNvPicUrl;
+ (id)getQuestionUrl;
+ (id)getOnlineTVUrl;
+ (id)getVideoDetectionUrl;
+ (id)getVideoFeedbackUrl:(id)arg1 withSrc:(id)arg2 withName:(id)arg3 withWKID:(id)arg4 withError:(id)arg5;
+ (id)getUPaiYunImageUrl:(id)arg1;
+ (id)getUriEndParamsWithV:(_Bool)arg1;
+ (id)getUriEndParams;
+ (id)getPlayVideoM3U8Url:(id)arg1;
+ (id)getPlayVideoIntentInterfaceUrl:(id)arg1 withAutoInstall:(_Bool)arg2;
+ (id)getPushWebPageUrl;
+ (id)getMyTVRecommendList;
+ (id)getMyTVWhiteAndBlackList;
+ (id)getAbnormalMingPaiUrl;
+ (id)getPromotionMingPaiUrl;
+ (id)getServerInstallUrlWithAction:(id)arg1;
+ (id)getServerInstallUrl;
+ (id)getQQqunUrlWithQQnumber:(id)arg1;
+ (id)getAppStoreUrl;
+ (id)getVoiceCloudUrlS4:(id)arg1;
+ (id)decodeString:(id)arg1;
+ (id)URLencode:(id)arg1 stringEncoding:(unsigned long long)arg2;
+ (id)getRouterJSUrl;
+ (id)getJoinUsUrl;
+ (id)getBBSUrl;
+ (id)getHasDeviceUrl;
+ (id)getBuyBuyBuyUrl;
+ (id)getLogoutUrlWithUid:(id)arg1;
+ (id)getLogonUrl;
+ (id)getAppInitUrllV2;
+ (id)getVoiceTipsURLV2;
+ (id)getSubCategoryVideoUrl:(id)arg1 withVideoSubType:(id)arg2;
+ (id)getSubCategoryVideoV3Url:(id)arg1 withVideoSubType:(id)arg2;
+ (id)getVideoFilterRequestUrl:(id)arg1;
+ (id)getVideoFilterUrl:(id)arg1;
+ (id)getDianBoDetailV4;
+ (id)commentDropallnotice;
+ (id)commentDropnotice;
+ (id)getCommentMynotice;
+ (id)getZhiBoIntent;
+ (id)subscribeCancelSubscribe;
+ (id)subscribeAddsubscribe;
+ (id)getZhiBoFind;
+ (id)getZhiBoGsURLV2:(id)arg1;
+ (id)getZhiBoTrailerURLV2;
+ (id)getSubscribelist;
+ (id)getZhiBoMainURLV2;
+ (id)getNeedUpdateURLV2;
+ (id)getAppDetailURLV2:(id)arg1;
+ (id)getSubCategoryURLV2:(id)arg1 withIndex:(long long)arg2;
+ (id)getAppStorePageUrl:(id)arg1 pageIndex:(long long)arg2;
+ (id)getAppStoreNewURLV2;
+ (id)getAppStoreHotURLV2;
+ (id)getAppstoreSubURLV2;
+ (id)getDianBoMainURLV2;
+ (id)basicUrl:(id)arg1 withSrc:(_Bool)arg2 isNeedUid:(_Bool)arg3 isNeedServerVersion:(_Bool)arg4;
+ (id)basicUrl:(id)arg1 withSrc:(_Bool)arg2 isNeedUid:(_Bool)arg3;
+ (id)basicUrl:(id)arg1 withSrc:(_Bool)arg2 andChannel:(_Bool)arg3 andOptional:(id)arg4 needV:(_Bool)arg5;
+ (id)basicUrl:(id)arg1 withSrc:(_Bool)arg2 andChannel:(_Bool)arg3 andOptional:(id)arg4;
+ (id)getShareUrl;
+ (id)getNoDeviceHelpUrl;
+ (id)getInstallServerHelpPage;
+ (id)getInputWebviewPageUrlWithIme:(id)arg1;

@end

