//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface WKCollectModel : NSObject
{
    NSMutableArray *_collect;
    NSMutableArray *_subscribe;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSMutableArray *subscribe; // @synthesize subscribe=_subscribe;
@property(retain, nonatomic) NSMutableArray *collect; // @synthesize collect=_collect;
- (void).cxx_destruct;

@end

