//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "CommonHelpClickedDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "WKBaseControlDelegate.h"
#import "WKCleanButtonViewDelegate.h"
#import "WKOperationManagerViewDelegate.h"
#import "WKPluginPlayerViewDelegate.h"
#import "WKRemoteTopButtonDelegate.h"

@class NSLayoutConstraint, NSString, OmnidirectionalControl, SlidingMouseView, UIButton, UIColor, UIImageView, WKCleanButton, WKDirectionKeyView, WKDirectionView, WKKeyBoardView, WKOperationManagerView, WKPluginPlayerView, WKReloadActivityButton, WKRemoteTopButton;

@interface WKControlView : UIView <WKOperationManagerViewDelegate, CommonHelpClickedDelegate, WKBaseControlDelegate, WKRemoteTopButtonDelegate, WKCleanButtonViewDelegate, UIGestureRecognizerDelegate, WKPluginPlayerViewDelegate>
{
    _Bool _isAnimation;
    struct CGPoint _startTouch;
    _Bool _mingPaiTipsRunning;
    _Bool _sunBoardButtonRunning;
    _Bool _isShow;
    WKPluginPlayerView *miniPlayer;
    WKOperationManagerView *managerView;
    WKDirectionView *directionView;
    WKKeyBoardView *keyBoradView;
    SlidingMouseView *slidingMouseView;
    UIImageView *slidingDownTipsImageView;
    OmnidirectionalControl *omnidirectionalControlView;
    UIButton *_closeBtn;
    UIButton *_selectModeBtn;
    WKDirectionKeyView *_directionKeyView;
    UIButton *_backButton;
    UIButton *_voiceButton;
    UIView *_opertationView;
    WKCleanButton *_cleanButton;
    UIView *_slideingHiddenView;
    WKRemoteTopButton *_remoteTopButton;
    WKReloadActivityButton *_titleButton;
    UIImageView *_keyBordNotWorkImage;
    UIView *_bottomView;
    NSLayoutConstraint *_bottomViewBottom;
    NSLayoutConstraint *_operationViewTop;
    NSLayoutConstraint *_operationViewBottom;
    UIColor *_currentColor;
}

@property(retain, nonatomic) UIColor *currentColor; // @synthesize currentColor=_currentColor;
@property(nonatomic) __weak NSLayoutConstraint *operationViewBottom; // @synthesize operationViewBottom=_operationViewBottom;
@property(nonatomic) __weak NSLayoutConstraint *operationViewTop; // @synthesize operationViewTop=_operationViewTop;
@property(nonatomic) __weak NSLayoutConstraint *bottomViewBottom; // @synthesize bottomViewBottom=_bottomViewBottom;
@property(nonatomic) __weak UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(nonatomic) __weak UIImageView *keyBordNotWorkImage; // @synthesize keyBordNotWorkImage=_keyBordNotWorkImage;
@property(nonatomic) __weak WKReloadActivityButton *titleButton; // @synthesize titleButton=_titleButton;
@property(nonatomic) __weak WKRemoteTopButton *remoteTopButton; // @synthesize remoteTopButton=_remoteTopButton;
@property(nonatomic) __weak UIView *slideingHiddenView; // @synthesize slideingHiddenView=_slideingHiddenView;
@property(nonatomic) __weak WKCleanButton *cleanButton; // @synthesize cleanButton=_cleanButton;
@property(nonatomic) __weak UIView *opertationView; // @synthesize opertationView=_opertationView;
@property(nonatomic) __weak UIButton *voiceButton; // @synthesize voiceButton=_voiceButton;
@property(nonatomic) __weak UIButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) WKDirectionKeyView *directionKeyView; // @synthesize directionKeyView=_directionKeyView;
@property(nonatomic) __weak UIButton *selectModeBtn; // @synthesize selectModeBtn=_selectModeBtn;
@property(nonatomic) __weak UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(retain, nonatomic) OmnidirectionalControl *omnidirectionalControlView; // @synthesize omnidirectionalControlView;
@property(retain, nonatomic) UIImageView *slidingDownTipsImageView; // @synthesize slidingDownTipsImageView;
@property(retain, nonatomic) SlidingMouseView *slidingMouseView; // @synthesize slidingMouseView;
@property(retain, nonatomic) WKKeyBoardView *keyBoradView; // @synthesize keyBoradView;
@property(retain, nonatomic) WKDirectionView *directionView; // @synthesize directionView;
@property(retain, nonatomic) WKOperationManagerView *managerView; // @synthesize managerView;
@property(retain, nonatomic) WKPluginPlayerView *miniPlayer; // @synthesize miniPlayer;
- (void).cxx_destruct;
- (void)keyBordNotWorkAction;
- (void)startPauseBtnClicked;
- (void)dealloc;
- (void)onRemoteTopButtonClicked:(id)arg1;
- (void)sendKeyCodeAction:(long long)arg1;
- (void)onBaseControlDelegateWithKeyCode:(long long)arg1;
- (void)controlKeyCodeAction:(id)arg1;
- (id)getSelectedView:(long long)arg1;
- (void)showKeyBordNotWorkedView;
- (void)showControlView:(_Bool)arg1;
- (void)showControlView:(_Bool)arg1 anmialed:(_Bool)arg2;
- (void)onCommonHelpClickedDelegate;
- (void)showAlertForSlideMouse;
- (void)removeOperationModeView;
- (void)showTouchHelpView;
- (double)cleaButtonButtonOffset;
- (void)refreshSlidingViews;
- (void)refreshOperationView;
- (void)layoutSubviews;
- (void)onOperationManagerViewSelected:(long long)arg1;
- (void)setupLastModeView;
- (void)showManagerOperationView:(_Bool)arg1;
- (void)controlModeButtonClick:(id)arg1;
- (void)closeButtonClick:(id)arg1;
- (void)onCleanButtonViewSwiped;
- (void)onCleanButtonViewClicked;
- (void)updateTitle;
- (void)onChangeDeviceNotification:(id)arg1;
- (void)onRecvVideoControlErrorData:(id)arg1;
- (void)onRecvVideoControlStop:(id)arg1;
- (void)onRecvVideoControlSync:(id)arg1;
- (void)longPressGesture:(id)arg1;
- (void)slidingDownGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)titleButtonClick:(id)arg1;
- (void)tapHiddenControlView;
- (void)registerNotification;
- (void)addViewGestures;
- (void)buildUI;
- (void)awakeFromNib;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

