//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SimplePingDelegate.h"

@class NSDate, NSMutableArray, NSOperationQueue, NSString, NSTimer, WKDeviceItem, WKScanOperation;

@interface WKDeviceManager : NSObject <SimplePingDelegate>
{
    NSDate *_startTime;
    NSString *_tempDeviceIp;
    WKDeviceItem *_lastDevice;
    WKScanOperation *_scanOperation;
    CDUnknownBlockType _callBackBlock;
    _Bool _elevateStop;
    _Bool _elevating;
    NSOperationQueue *operationQueue;
    NSMutableArray *netStatusArray;
    NSTimer *pingTimer;
    NSString *loadLastDeviceIP;
}

+ (_Bool)isHDLiveMingPai;
+ (long long)shouldShowPlateView;
+ (id)shareInstances;
@property(nonatomic) _Bool elevating; // @synthesize elevating=_elevating;
@property(nonatomic) _Bool elevateStop; // @synthesize elevateStop=_elevateStop;
@property(retain, nonatomic) NSString *loadLastDeviceIP; // @synthesize loadLastDeviceIP;
@property(retain, nonatomic) NSTimer *pingTimer; // @synthesize pingTimer;
@property(retain, nonatomic) NSMutableArray *netStatusArray; // @synthesize netStatusArray;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stopElevateLoop;
- (void)elevateLoop;
- (void)startElevateLoop;
- (void)resetDetetion;
- (void)disposeTimedout;
- (void)simplePing:(id)arg1 didReceiveUnexpectedPacket:(id)arg2;
- (void)simplePing:(id)arg1 didReceivePingResponsePacket:(id)arg2 sequenceNumber:(unsigned short)arg3;
- (void)simplePing:(id)arg1 didFailToSendPacket:(id)arg2 sequenceNumber:(unsigned short)arg3 error:(id)arg4;
- (void)simplePing:(id)arg1 didSendPacket:(id)arg2 sequenceNumber:(unsigned short)arg3;
- (void)simplePing:(id)arg1 didFailWithError:(id)arg2;
- (void)simplePing:(id)arg1 didStartWithAddress:(id)arg2;
- (void)loopSendPingData;
- (void)detectionNetworkStatus;
- (void)saveTempDeviceIp;
- (void)saveLastDeviceIp:(id)arg1;
- (void)discoverDevices;
- (void)cancelScanDevices;
- (void)discoverDevice;
- (void)scanDevice;
- (void)scanDevicesWithResultBlock:(CDUnknownBlockType)arg1;
- (void)serverIsUp:(id)arg1;
- (void)onUdpDeviceArrived:(id)arg1;
- (void)resetHDLiveLabel;
- (void)setCurrentDevices:(id)arg1;
- (void)chooseDevice:(id)arg1;
- (void)onNetWrokChange:(id)arg1;
- (void)onCurrentLaunchAppChanged;
- (void)onAppWillEnterForeground;
- (void)onAppEnterBackground;
- (void)registerNoticationCenter;
- (id)init;
- (unsigned long long)netWorkStatus:(double)arg1;
- (double)computeAverageTime;
- (void)setNetStatusArrayDataWithDurationTime:(float)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

