//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseControlView.h"

@class NSTimer, UIImage, UILabel;

@interface WKDirectionKeyView : WKBaseControlView
{
    UIImage *_bgImg;
    UIImage *_upImg;
    UIImage *_leftImg;
    UIImage *_downImg;
    UIImage *_rightImg;
    UIImage *_centerImg;
    double _scale;
    unsigned long long _currentType;
    NSTimer *_longPressTimer;
    UILabel *_channelUpLbl;
    UILabel *_channelDownLbl;
    UILabel *_volUpLbl;
    UILabel *_volDownLbl;
}

@property(retain, nonatomic) UILabel *volDownLbl; // @synthesize volDownLbl=_volDownLbl;
@property(retain, nonatomic) UILabel *volUpLbl; // @synthesize volUpLbl=_volUpLbl;
@property(retain, nonatomic) UILabel *channelDownLbl; // @synthesize channelDownLbl=_channelDownLbl;
@property(retain, nonatomic) UILabel *channelUpLbl; // @synthesize channelUpLbl=_channelUpLbl;
@property(retain, nonatomic) NSTimer *longPressTimer; // @synthesize longPressTimer=_longPressTimer;
@property(nonatomic) unsigned long long currentType; // @synthesize currentType=_currentType;
@property(nonatomic) double scale; // @synthesize scale=_scale;
@property(retain, nonatomic) UIImage *centerImg; // @synthesize centerImg=_centerImg;
@property(retain, nonatomic) UIImage *rightImg; // @synthesize rightImg=_rightImg;
@property(retain, nonatomic) UIImage *downImg; // @synthesize downImg=_downImg;
@property(retain, nonatomic) UIImage *leftImg; // @synthesize leftImg=_leftImg;
@property(retain, nonatomic) UIImage *upImg; // @synthesize upImg=_upImg;
@property(retain, nonatomic) UIImage *bgImg; // @synthesize bgImg=_bgImg;
- (void).cxx_destruct;
- (void)bulidHDLbl;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)slidingDownGesture:(id)arg1;
- (void)sendKeyCodeByTapGesture:(id)arg1;
- (void)sendKeyCodeAction:(id)arg1;
- (void)stopLongPressTimer:(int)arg1;
- (void)startLongPressTimer:(long long)arg1;
- (void)longPressGestureAction:(id)arg1;
- (unsigned long long)getDirectionTypeWithPoint:(struct CGPoint)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)hideHDliveTitle:(_Bool)arg1;
- (void)onRecvHdLiveStop;
- (void)onRecvHdLiveStart;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

