//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UITableView, WKPlayControlModel, WKVideoEpisodeModel;

@interface WKEpisodeViewController : UIView <UITableViewDelegate, UITableViewDataSource>
{
    UIView *_hiddenView;
    unsigned long long _viewCount;
    long long _currentTag;
    unsigned long long _sectionCount;
    WKVideoEpisodeModel *_episodeModel;
    UIView *hiddenView;
    id <WKEpisodeViewDelegate> _delegate;
    WKPlayControlModel *_playControlModel;
    NSArray *_dataArr;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NSArray *dataArr; // @synthesize dataArr=_dataArr;
@property(retain, nonatomic) WKPlayControlModel *playControlModel; // @synthesize playControlModel=_playControlModel;
@property(nonatomic) __weak id <WKEpisodeViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIView *hiddenView; // @synthesize hiddenView;
- (void).cxx_destruct;
- (void)showOrHiddenEpisodeView:(_Bool)arg1 playControlModel:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)buildEpisodeButtons:(id)arg1;
- (void)buildTableView;
- (void)closeButtonClicked;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

