//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UILabel, UIView;

@interface WKEpisodeCollectionViewCell : UICollectionViewCell
{
    UIView *_topLine;
    UIView *_leftLine;
    UIView *_rightLine;
    UIView *_bottomLine;
    UILabel *_episodeLbl;
}

@property(nonatomic) __weak UILabel *episodeLbl; // @synthesize episodeLbl=_episodeLbl;
@property(nonatomic) __weak UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(nonatomic) __weak UIView *rightLine; // @synthesize rightLine=_rightLine;
@property(nonatomic) __weak UIView *leftLine; // @synthesize leftLine=_leftLine;
@property(nonatomic) __weak UIView *topLine; // @synthesize topLine=_topLine;
- (void).cxx_destruct;
- (void)configCellWith:(id)arg1 lineType:(long long)arg2;
- (void)awakeFromNib;

@end

