//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "SearchHistoryTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKBannerAdViewDelegate.h"
#import "WKGlobalSearchKeyWordTableViewCellDelegate.h"
#import "WKTableSectionHeaderViewDelegate.h"

@class NSString, UIView, WKGlobalSearchRecommendTableModel;

@interface WKGlobalSearchRecommendTableView : UITableView <UITableViewDataSource, UITableViewDelegate, SearchHistoryTableViewCellDelegate, WKTableSectionHeaderViewDelegate, WKBannerAdViewDelegate, WKGlobalSearchKeyWordTableViewCellDelegate>
{
    WKGlobalSearchRecommendTableModel *_recommendModel;
    UIView *bannerAdView;
    id <WKGlobalSearchRecommendTableViewDelegate> _clickDelegate;
}

@property(nonatomic) __weak id <WKGlobalSearchRecommendTableViewDelegate> clickDelegate; // @synthesize clickDelegate=_clickDelegate;
@property(retain, nonatomic) UIView *bannerAdView; // @synthesize bannerAdView;
- (void).cxx_destruct;
- (void)adViewWillClose:(id)arg1;
- (void)adDataDidReceived:(id)arg1;
- (void)onGlobalSearchKeyWordTableViewCellScrollViewDelegateOffset:(struct CGPoint)arg1;
- (void)onGlobalSearchKeyWordTableViewCellSelectRowRequestType:(id)arg1 index:(unsigned long long)arg2;
- (void)onTableSectionHeaderViewDelegate:(long long)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onSearchHistoryButtonClickedWithTag:(long long)arg1;
- (void)setRecommendTableViewDataSources:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

