//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKGlobalSearchRecommendHotKeyWordModel : NSObject
{
    NSString *_word;
    NSString *_markicon;
}

@property(retain, nonatomic) NSString *markicon; // @synthesize markicon=_markicon;
@property(retain, nonatomic) NSString *word; // @synthesize word=_word;
- (void).cxx_destruct;

@end

