//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseProtocol.h"

@class NSObject<OS_dispatch_queue>;

@interface WKHaierProtocol : WKBaseProtocol
{
    _Bool _fromMainThread;
    NSObject<OS_dispatch_queue> *_httpQueue;
}

- (void).cxx_destruct;
- (void)releaseResources;
- (void)openServerApp:(CDUnknownBlockType)arg1;
- (void)autoInstallServerApp:(CDUnknownBlockType)arg1;
- (_Bool)canAutoInstallServer;
- (id)getKeyString:(long long)arg1;
- (_Bool)needChange:(id)arg1;
- (void)sendProtocolKey:(int)arg1;
- (_Bool)willWorkWithKey:(int)arg1;
- (void)willWorkWithDevice:(id)arg1 WithSuccessBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

