//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface WKHDLiveTonightListListModel : NSObject
{
    _Bool _isOnLive;
    NSString *_showid;
    NSString *_showname;
    NSString *_cover;
    NSNumber *_start;
    NSNumber *_end;
    NSString *_is_subscribe;
    NSString *_wkid;
}

@property(nonatomic) _Bool isOnLive; // @synthesize isOnLive=_isOnLive;
@property(copy, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(copy, nonatomic) NSString *is_subscribe; // @synthesize is_subscribe=_is_subscribe;
@property(retain, nonatomic) NSNumber *end; // @synthesize end=_end;
@property(retain, nonatomic) NSNumber *start; // @synthesize start=_start;
@property(copy, nonatomic) NSString *cover; // @synthesize cover=_cover;
@property(copy, nonatomic) NSString *showname; // @synthesize showname=_showname;
@property(copy, nonatomic) NSString *showid; // @synthesize showid=_showid;
- (void).cxx_destruct;
- (void)cancelSubscribe:(CDUnknownBlockType)arg1 faiture:(CDUnknownBlockType)arg2;
- (void)addSubscribe:(CDUnknownBlockType)arg1 failture:(CDUnknownBlockType)arg2;

@end

