//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSArray, NSString, UICollectionView;

@interface WKHDLiveFindHeaderCollectionView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    UICollectionView *_headerCollectionView;
    NSArray *_headerCollectionViewDataSource;
}

@property(retain, nonatomic) NSArray *headerCollectionViewDataSource; // @synthesize headerCollectionViewDataSource=_headerCollectionViewDataSource;
@property(retain, nonatomic) UICollectionView *headerCollectionView; // @synthesize headerCollectionView=_headerCollectionView;
- (void).cxx_destruct;
- (void)setDatasource:(id)arg1;
- (void)collectionView:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

