//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKHDLiveFindGirdViewModel : NSObject
{
    NSString *_title;
    NSString *_titlecolor;
    NSString *_des;
    NSString *_weburl;
    NSString *_bannercover;
}

@property(retain, nonatomic) NSString *bannercover; // @synthesize bannercover=_bannercover;
@property(retain, nonatomic) NSString *weburl; // @synthesize weburl=_weburl;
@property(retain, nonatomic) NSString *des; // @synthesize des=_des;
@property(retain, nonatomic) NSString *titlecolor; // @synthesize titlecolor=_titlecolor;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)horizontalViewModelAction;

@end

