//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UIButton, UILabel, UIView;

@interface WKIntroTableViewCell : UITableViewCell
{
    UILabel *_introTextView;
    UIButton *_foldButton;
    NSString *_introText;
    _Bool _isShowArrow;
    UIView *_bottomLine;
}

@property(nonatomic) _Bool isShowArrow; // @synthesize isShowArrow=_isShowArrow;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setIntroTextViewDataSources:(id)arg1 isShowArrow:(_Bool)arg2;
- (void)initSubView;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

