//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface WKIntent : NSObject
{
    NSMutableDictionary *_intentDic;
    NSString *_intentStr;
}

+ (id)intentWithString:(id)arg1;
@property(copy, nonatomic) NSString *intentStr; // @synthesize intentStr=_intentStr;
@property(retain, nonatomic) NSMutableDictionary *intentDic; // @synthesize intentDic=_intentDic;
- (void).cxx_destruct;
- (id)getValueByKey:(id)arg1;
- (void)parseIntentStr;

@end

