//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class UITextView, UIWebView;

@interface WKIOS10NetErrorHeperViewController : UIViewController
{
    UIWebView *_webview;
    UITextView *_textView;
}

@property(nonatomic) __weak UITextView *textView; // @synthesize textView=_textView;
@property(nonatomic) __weak UIWebView *webview; // @synthesize webview=_webview;
- (void).cxx_destruct;
- (id)getHtmlString;
- (void)onclick:(id)arg1;
- (void)viewDidLoad;

@end

