//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface WKMessageCenterMsgModel : NSObject
{
    _Bool _unRead;
    NSString *_time;
    NSString *_title;
    NSString *_desc;
    NSString *_webUri;
    NSNumber *_indexTag;
    NSString *_bannerUrlString;
    NSNumber *_messageType;
    NSString *_showid;
    NSNumber *_timestamp;
    NSString *_notifyId;
}

@property(retain, nonatomic) NSString *notifyId; // @synthesize notifyId=_notifyId;
@property(retain, nonatomic) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSString *showid; // @synthesize showid=_showid;
@property(retain, nonatomic) NSNumber *messageType; // @synthesize messageType=_messageType;
@property(retain, nonatomic) NSString *bannerUrlString; // @synthesize bannerUrlString=_bannerUrlString;
@property(retain, nonatomic) NSNumber *indexTag; // @synthesize indexTag=_indexTag;
@property(retain, nonatomic) NSString *webUri; // @synthesize webUri=_webUri;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(nonatomic) _Bool unRead; // @synthesize unRead=_unRead;
- (void).cxx_destruct;
- (void)messageModelAction;

@end

