//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKMessageZhiBoModel : NSObject
{
    NSString *_dsj;
    NSString *_vst;
    NSString *_dsm;
    NSString *_use;
    NSString *_name;
    NSString *_intent;
}

@property(copy, nonatomic) NSString *intent; // @synthesize intent=_intent;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *use; // @synthesize use=_use;
@property(copy, nonatomic) NSString *dsm; // @synthesize dsm=_dsm;
@property(copy, nonatomic) NSString *vst; // @synthesize vst=_vst;
@property(copy, nonatomic) NSString *dsj; // @synthesize dsj=_dsj;
- (void).cxx_destruct;

@end

