//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class WKAutoRunLabel;

@interface WKMingPaiLabelView : UIButton
{
    WKAutoRunLabel *label;
}

@property(retain, nonatomic) WKAutoRunLabel *label; // @synthesize label;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setTextColor:(id)arg1;
- (void)setText:(id)arg1;
- (id)text;
- (id)initWithFrame:(struct CGRect)arg1;

@end

