//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKAppTableViewCellOperationButtonClickDelegate.h"
#import "WKMyAppHeaderViewDelegate.h"

@class NSMutableArray, NSString;

@interface WKMyAppView : UITableView <UITableViewDataSource, UITableViewDelegate, WKMyAppHeaderViewDelegate, WKAppTableViewCellOperationButtonClickDelegate>
{
    NSMutableArray *needUpdateArray;
    NSMutableArray *_appListArr;
    NSMutableArray *_dataSoureArray;
}

@property(retain, nonatomic) NSMutableArray *dataSoureArray; // @synthesize dataSoureArray=_dataSoureArray;
@property(retain, nonatomic) NSMutableArray *appListArr; // @synthesize appListArr=_appListArr;
- (void).cxx_destruct;
- (void)onAppTableViewCellOperationButtonClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)updateAllApp;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)showNoResultViewIfNeed;
- (void)serverAppupdatelistArrived:(id)arg1;
- (void)serverApplistArrived:(id)arg1;
- (void)dealloc;
- (void)initTableView;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

