//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GDTNativeAdDelegate.h"

@class GDTNativeAd, GDTNativeAdData, NSString, WKNativeAdView;

@interface WKNativeAd : NSObject <GDTNativeAdDelegate>
{
    CDUnknownBlockType _adviewsuccessBlock;
    CDUnknownBlockType _adviewfailtureBlock;
    WKNativeAdView *_adView;
    GDTNativeAd *_nativeAd;
    GDTNativeAdData *_anData;
}

@property(retain, nonatomic) GDTNativeAdData *anData; // @synthesize anData=_anData;
@property(retain, nonatomic) GDTNativeAd *nativeAd; // @synthesize nativeAd=_nativeAd;
@property(retain, nonatomic) WKNativeAdView *adView; // @synthesize adView=_adView;
@property(copy, nonatomic) CDUnknownBlockType adviewfailtureBlock; // @synthesize adviewfailtureBlock=_adviewfailtureBlock;
@property(copy, nonatomic) CDUnknownBlockType adviewsuccessBlock; // @synthesize adviewsuccessBlock=_adviewsuccessBlock;
- (void).cxx_destruct;
- (void)nativeAdFailToLoad:(id)arg1;
- (void)nativeAdSuccessToLoad:(id)arg1;
- (void)createNativeAd:(id)arg1 adType:(id)arg2 adId:(id)arg3 Vc:(id)arg4 success:(CDUnknownBlockType)arg5 faiture:(CDUnknownBlockType)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

