//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, UIButton, UIImageView, UILabel;

@interface WKNoResultView : UIView
{
    UIImageView *_ivNoResult;
    UILabel *_lblTitle;
    UILabel *_lblDesc;
    UIButton *_btnNoResult;
    NSString *_imageName;
    NSString *_title;
    NSString *_desc;
    NSString *_btnTitle;
    CDUnknownBlockType _didPressBtn;
}

+ (id)noResultWithTitle:(id)arg1 desc:(id)arg2 imageName:(id)arg3 btnTitle:(id)arg4 didPressBtn:(CDUnknownBlockType)arg5;
@property(copy, nonatomic) CDUnknownBlockType didPressBtn; // @synthesize didPressBtn=_didPressBtn;
@property(retain, nonatomic) NSString *btnTitle; // @synthesize btnTitle=_btnTitle;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(retain, nonatomic) UIButton *btnNoResult; // @synthesize btnNoResult=_btnNoResult;
@property(retain, nonatomic) UILabel *lblDesc; // @synthesize lblDesc=_lblDesc;
@property(retain, nonatomic) UILabel *lblTitle; // @synthesize lblTitle=_lblTitle;
@property(retain, nonatomic) UIImageView *ivNoResult; // @synthesize ivNoResult=_ivNoResult;
- (void).cxx_destruct;
- (void)didPressedButton:(id)arg1;
- (id)init;

@end

