//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@interface WKPaddingLabel : UILabel
{
    struct UIEdgeInsets _padding;
}

@property(nonatomic) struct UIEdgeInsets padding; // @synthesize padding=_padding;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1 limitedToNumberOfLines:(long long)arg2;
- (void)drawTextInRect:(struct CGRect)arg1;

@end

