//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UISearchBarDelegate.h"
#import "WKWebPageViewDeleagete.h"

@class NSString, WKPushWebPageModel, WKWebPageView;

@interface WKPushWebPageSearchViewController : WKBaseSubViewController <WKWebPageViewDeleagete, UISearchBarDelegate>
{
    WKPushWebPageModel *_pageModel;
    WKWebPageView *_webPageView;
}

@property(retain, nonatomic) WKWebPageView *webPageView; // @synthesize webPageView=_webPageView;
- (void).cxx_destruct;
- (void)searchVideo:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithWebPageModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

