//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface WKRemoteTopButton : UIButton
{
    UIButton *_volumeDown;
    UIButton *_volumeUp;
    UIButton *_volumeCenter;
    UIButton *_homeButton;
    UIButton *_menuButton;
    double _homeX;
    id <WKRemoteTopButtonDelegate> _delegate;
}

@property(nonatomic) __weak id <WKRemoteTopButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) double homeX; // @synthesize homeX=_homeX;
- (void).cxx_destruct;
- (void)keyCodeAction:(id)arg1;
- (void)initVolumeButton;
- (id)init;
- (void)awakeFromNib;

@end

