//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSArray, NSMutableDictionary, NSString;

@interface WKScanOperation : NSOperation
{
    NSMutableDictionary *_fdExtraInfoDict;
    NSString *_ipAddress;
    NSArray *_scanPorts;
    int _maxFd;
    struct fd_set _connectFdSet;
}

- (void).cxx_destruct;
- (void)ConfirmLeshiDevice:(id)arg1;
- (void)ConfirmBaiduDevice:(id)arg1;
- (void)ConfirmHonorDevice:(id)arg1;
- (void)ConfirmHaierDevice:(id)arg1;
- (void)ConfirmHimediaDevice:(id)arg1;
- (void)ConfirmTCLDevice:(id)arg1;
- (void)connectTCLDevicesStartAdb:(id)arg1;
- (void)markingDevicesByIP:(id)arg1 andPort:(int)arg2;
- (void)main;
- (void)startScan:(id)arg1 withPorts:(id)arg2;
- (void)finishAllSockets;
- (void)finishSocket:(id)arg1;
- (void)connectSocket:(id)arg1 andPort:(int)arg2 nextIndex:(int)arg3;
- (void)keepFdSetUpdated;
- (int)nonBlockConnect:(id)arg1 andPort:(int)arg2;
- (id)initWithAddressAndPortList:(id)arg1 scanPorts:(id)arg2;

@end

