//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString;

@interface WKSDKVideoSourceModel : NSObject
{
    int _currentEpisode;
    int _durationSeconds;
    int _progressSeconds;
    int _resolution;
    int _status;
    int _supportResolutionFlag;
    int _volume;
    int _volumeMax;
    int _videoType;
    long long _episodeNum;
    NSString *_from;
    NSString *_title;
    NSString *_privateId;
    NSString *_posterImageUrl;
    NSArray *_episodeNames;
    NSMutableArray *_definetionArray;
    NSMutableArray *_definetionTitleArray;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSMutableArray *definetionTitleArray; // @synthesize definetionTitleArray=_definetionTitleArray;
@property(retain, nonatomic) NSMutableArray *definetionArray; // @synthesize definetionArray=_definetionArray;
@property(retain, nonatomic) NSArray *episodeNames; // @synthesize episodeNames=_episodeNames;
@property(retain, nonatomic) NSString *posterImageUrl; // @synthesize posterImageUrl=_posterImageUrl;
@property(retain, nonatomic) NSString *privateId; // @synthesize privateId=_privateId;
@property(nonatomic) int videoType; // @synthesize videoType=_videoType;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(nonatomic) int volumeMax; // @synthesize volumeMax=_volumeMax;
@property(nonatomic) int volume; // @synthesize volume=_volume;
@property(nonatomic) int supportResolutionFlag; // @synthesize supportResolutionFlag=_supportResolutionFlag;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) int resolution; // @synthesize resolution=_resolution;
@property(nonatomic) int progressSeconds; // @synthesize progressSeconds=_progressSeconds;
@property(nonatomic) int durationSeconds; // @synthesize durationSeconds=_durationSeconds;
@property(nonatomic) int currentEpisode; // @synthesize currentEpisode=_currentEpisode;
@property(nonatomic) long long episodeNum; // @synthesize episodeNum=_episodeNum;
- (void).cxx_destruct;
- (void)disposeDefinetion;

@end

