//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKSDKPlayControlHeartBeatMsg : NSObject
{
    int _durationSeconds;
    int _progressSeconds;
    int _resolution;
    int _status;
    int _volume;
    int _currentEpisode;
    int _videoType;
    NSString *_title;
    NSString *_privateId;
}

@property(copy, nonatomic) NSString *privateId; // @synthesize privateId=_privateId;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) int videoType; // @synthesize videoType=_videoType;
@property(nonatomic) int currentEpisode; // @synthesize currentEpisode=_currentEpisode;
@property(nonatomic) int volume; // @synthesize volume=_volume;
@property(nonatomic) int status; // @synthesize status=_status;
@property(nonatomic) int resolution; // @synthesize resolution=_resolution;
@property(nonatomic) int progressSeconds; // @synthesize progressSeconds=_progressSeconds;
@property(nonatomic) int durationSeconds; // @synthesize durationSeconds=_durationSeconds;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;

@end

