//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSString, NSTimer, UIButton, UILabel;

@interface WKSettingWifiViewController : BaseViewController
{
    NSTimer *countTimer;
    _Bool findDevice;
    NSString *ssidStr;
    _Bool _isPush;
    UIButton *_goNextButton;
    UIButton *_goConnnectWiFi;
    UILabel *_currentWIFILabel;
    long long _timerCount;
    NSTimer *_waitTimer;
    UILabel *_changeWiFiLabel;
    UILabel *_maintipLabel;
}

@property(nonatomic) __weak UILabel *maintipLabel; // @synthesize maintipLabel=_maintipLabel;
@property(nonatomic) __weak UILabel *changeWiFiLabel; // @synthesize changeWiFiLabel=_changeWiFiLabel;
@property(retain, nonatomic) NSTimer *waitTimer; // @synthesize waitTimer=_waitTimer;
@property(nonatomic) _Bool isPush; // @synthesize isPush=_isPush;
@property(nonatomic) long long timerCount; // @synthesize timerCount=_timerCount;
@property(nonatomic) __weak UILabel *currentWIFILabel; // @synthesize currentWIFILabel=_currentWIFILabel;
@property(nonatomic) __weak UIButton *goConnnectWiFi; // @synthesize goConnnectWiFi=_goConnnectWiFi;
@property(nonatomic) __weak UIButton *goNextButton; // @synthesize goNextButton=_goNextButton;
- (void).cxx_destruct;
- (void)dealloc;
- (void)scanDevice;
- (void)appWillEnterForeground:(id)arg1;
- (void)findDevice:(id)arg1;
- (void)countTimerAction;
- (void)waitTooLongTime;
- (void)updateWIFIMessage;
- (void)autoNext;
- (void)goNextButtonAcrion:(id)arg1;
- (void)goConnectWKwifi:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

