//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CALayer, UIImageView, UILabel;

@interface WKSearchResultHDLiveCell : UITableViewCell
{
    CALayer *_bottomLayer;
    UILabel *_channelName;
    UIImageView *_coverImage;
}

@property(nonatomic) __weak UIImageView *coverImage; // @synthesize coverImage=_coverImage;
@property(nonatomic) __weak UILabel *channelName; // @synthesize channelName=_channelName;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setCellDataSources:(id)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

