//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKSplashADModel : NSObject
{
    _Bool _hasOpen;
    long long _actionBegin;
    long long _actionEnd;
    NSString *_actionImage;
    NSString *_actionName;
    NSString *_actionUrl;
}

+ (id)replacedKeyFromPropertyName;
@property(copy, nonatomic) NSString *actionUrl; // @synthesize actionUrl=_actionUrl;
@property(copy, nonatomic) NSString *actionName; // @synthesize actionName=_actionName;
@property(copy, nonatomic) NSString *actionImage; // @synthesize actionImage=_actionImage;
@property(nonatomic) long long actionEnd; // @synthesize actionEnd=_actionEnd;
@property(nonatomic) long long actionBegin; // @synthesize actionBegin=_actionBegin;
@property(nonatomic) _Bool hasOpen; // @synthesize hasOpen=_hasOpen;
- (void).cxx_destruct;

@end

