//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class CAGradientLayer, UIImageView, UILabel, UIView, WKHDLiveTonightListModel;

@interface WKTonightBannerTableViewCell : UITableViewCell
{
    UIImageView *_bannerImageView;
    UILabel *_timeLabel;
    UIImageView *_timeIconImageView;
    UILabel *_zhiboStatusLabel;
    UILabel *_nameLabel;
    UILabel *_startTimeLabel;
    UIView *_showdowView;
    CAGradientLayer *_gradientLayer;
    id <wktonightBannerClickedDelegate> _bannerClickedDelegate;
    WKHDLiveTonightListModel *_findModel;
}

@property(retain, nonatomic) WKHDLiveTonightListModel *findModel; // @synthesize findModel=_findModel;
@property(nonatomic) __weak id <wktonightBannerClickedDelegate> bannerClickedDelegate; // @synthesize bannerClickedDelegate=_bannerClickedDelegate;
@property(retain, nonatomic) CAGradientLayer *gradientLayer; // @synthesize gradientLayer=_gradientLayer;
@property(nonatomic) __weak UIView *showdowView; // @synthesize showdowView=_showdowView;
@property(nonatomic) __weak UILabel *startTimeLabel; // @synthesize startTimeLabel=_startTimeLabel;
@property(nonatomic) __weak UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) __weak UILabel *zhiboStatusLabel; // @synthesize zhiboStatusLabel=_zhiboStatusLabel;
@property(nonatomic) __weak UIImageView *timeIconImageView; // @synthesize timeIconImageView=_timeIconImageView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UIImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
- (void).cxx_destruct;
- (void)updateZhiboStatusLabel:(id)arg1;
- (void)bannerImageViewClicked:(id)arg1;
- (void)setDataSource:(id)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;

@end

