//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface WKTonightItemsTableViewCell : UITableViewCell
{
    UILabel *_timeLabel;
    UIImageView *_timeIconImageView;
    UIView *_tvWrapView;
    id <WKtonightItemsTableviewcellDelegate> _cellDelegate;
}

@property(nonatomic) __weak id <WKtonightItemsTableviewcellDelegate> cellDelegate; // @synthesize cellDelegate=_cellDelegate;
@property(nonatomic) __weak UIView *tvWrapView; // @synthesize tvWrapView=_tvWrapView;
@property(nonatomic) __weak UIImageView *timeIconImageView; // @synthesize timeIconImageView=_timeIconImageView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
- (void).cxx_destruct;
- (void)itemViewClicked:(id)arg1;
- (void)updateZhibStatus;
- (void)setDataSource:(id)arg1;
- (void)awakeFromNib;

@end

