//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UITextView, WKVideoCommentModel;

@interface WKTuCaoTableViewCell : UITableViewCell
{
    WKVideoCommentModel *_cellModel;
    UITextView *_tucaoTextView;
    UIImageView *_userIcon;
    UILabel *_timeLabel;
    UILabel *_lineLabel;
}

@property(nonatomic) __weak UILabel *lineLabel; // @synthesize lineLabel=_lineLabel;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UIImageView *userIcon; // @synthesize userIcon=_userIcon;
@property(nonatomic) __weak UITextView *tucaoTextView; // @synthesize tucaoTextView=_tucaoTextView;
- (void).cxx_destruct;
- (id)disposeLikeCount:(long long)arg1;
- (void)setDataSource:(id)arg1;
- (id)getUserIcon:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;

@end

