//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UINavigationController, UITableView, UITableViewCell, UIView, WKUserModel;

@interface WKUserDetailViewController : WKBaseSubViewController <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate>
{
    UINavigationController *_tempNav;
    WKUserModel *_user;
    CDUnknownBlockType _logoutBlock;
    UITableView *_tvMain;
    UIView *_bgView;
    UIImageView *_blurBg;
    UIView *_headBgView;
    UILabel *_nameLbl;
    UITableViewCell *_logoutCell;
    UIButton *_logoutBtn;
}

@property(nonatomic) __weak UIButton *logoutBtn; // @synthesize logoutBtn=_logoutBtn;
@property(retain, nonatomic) UITableViewCell *logoutCell; // @synthesize logoutCell=_logoutCell;
@property(retain, nonatomic) UILabel *nameLbl; // @synthesize nameLbl=_nameLbl;
@property(retain, nonatomic) UIView *headBgView; // @synthesize headBgView=_headBgView;
@property(retain, nonatomic) UIImageView *blurBg; // @synthesize blurBg=_blurBg;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(nonatomic) __weak UITableView *tvMain; // @synthesize tvMain=_tvMain;
@property(copy, nonatomic) CDUnknownBlockType logoutBlock; // @synthesize logoutBlock=_logoutBlock;
@property(retain, nonatomic) WKUserModel *user; // @synthesize user=_user;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)logout;
- (void)didPressedLogoutBtn:(id)arg1;
- (void)buildUI;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

