//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKVideoSourceModel : NSObject
{
    NSString *_df_icon;
    NSString *_episodeUrl;
    NSString *_from;
    NSString *_icon;
    NSString *_intent;
    NSString *_name;
    NSString *_clartity;
    NSString *_contentType;
    NSString *_psid;
    NSString *_ssid;
    NSString *_pkgName;
}

@property(retain, nonatomic) NSString *pkgName; // @synthesize pkgName=_pkgName;
@property(retain, nonatomic) NSString *ssid; // @synthesize ssid=_ssid;
@property(retain, nonatomic) NSString *psid; // @synthesize psid=_psid;
@property(retain, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(retain, nonatomic) NSString *clartity; // @synthesize clartity=_clartity;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *intent; // @synthesize intent=_intent;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *episodeUrl; // @synthesize episodeUrl=_episodeUrl;
@property(retain, nonatomic) NSString *df_icon; // @synthesize df_icon=_df_icon;
- (void).cxx_destruct;

@end

