//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface WKVideoDetailReqModel : NSObject
{
    NSString *_from;
    NSString *_srcpage;
    NSString *_type;
    NSString *_vid;
    NSString *_pic;
    NSString *_title;
    NSString *_intent;
    NSString *_wkid;
    NSString *_time;
    long long _sort;
    NSNumber *_timearea;
    NSString *_ssid;
}

@property(retain, nonatomic) NSString *ssid; // @synthesize ssid=_ssid;
@property(nonatomic) NSNumber *timearea; // @synthesize timearea=_timearea;
@property(nonatomic) long long sort; // @synthesize sort=_sort;
@property(nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(retain, nonatomic) NSString *intent; // @synthesize intent=_intent;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
@property(retain, nonatomic) NSString *vid; // @synthesize vid=_vid;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *srcpage; // @synthesize srcpage=_srcpage;
@property(retain, nonatomic) NSString *from; // @synthesize from=_from;
- (void).cxx_destruct;

@end

