//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, WKDetailAD, WKVideoDetailModel;

@interface WKVideoDetailViewModel : NSObject
{
    NSString *_nextPage;
    WKVideoDetailModel *_detail;
    NSString *_adSwitch;
    WKDetailAD *_detail_ad;
}

@property(retain, nonatomic) WKDetailAD *detail_ad; // @synthesize detail_ad=_detail_ad;
@property(retain, nonatomic) NSString *adSwitch; // @synthesize adSwitch=_adSwitch;
@property(retain, nonatomic) WKVideoDetailModel *detail; // @synthesize detail=_detail;
@property(retain, nonatomic) NSString *nextPage; // @synthesize nextPage=_nextPage;
- (void).cxx_destruct;

@end

