//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface WKVideoSubitemDataModel : NSObject
{
    NSString *_id;
    NSString *_jumptype;
    NSString *_name;
    NSMutableArray *_subitems;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) NSMutableArray *subitems; // @synthesize subitems=_subitems;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *jumptype; // @synthesize jumptype=_jumptype;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;

@end

