//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray;

@interface WKVideoInfo : NSObject
{
    int _supportResolutionFlag;
    int _episodeNum;
    int _volumeMax;
    int _currentVersion;
    int _sdkrouter;
    NSMutableArray *_resolutionArr;
    NSArray *_videoEpisodes;
}

@property(retain, nonatomic) NSArray *videoEpisodes; // @synthesize videoEpisodes=_videoEpisodes;
@property(retain, nonatomic) NSMutableArray *resolutionArr; // @synthesize resolutionArr=_resolutionArr;
@property(nonatomic) int sdkrouter; // @synthesize sdkrouter=_sdkrouter;
@property(nonatomic) int currentVersion; // @synthesize currentVersion=_currentVersion;
@property(nonatomic) int volumeMax; // @synthesize volumeMax=_volumeMax;
@property(nonatomic) int episodeNum; // @synthesize episodeNum=_episodeNum;
@property(nonatomic) int supportResolutionFlag; // @synthesize supportResolutionFlag=_supportResolutionFlag;
- (void).cxx_destruct;
- (void)setEpisodes:(id)arg1;

@end

