//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubFirstViewController.h"

#import "FindTipsTableViewCellDelegate.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKViedoFindViewControllerBannerActionDelegate.h"

@class NSMutableArray, NSString, UITableView, WKDianboFindBigAdTableViewCell, WKDianboFindSmallAdTableViewCell;

@interface WKViedoFindViewController : WKBaseSubFirstViewController <UITableViewDelegate, UITableViewDataSource, WKViedoFindViewControllerBannerActionDelegate, FindTipsTableViewCellDelegate, UIGestureRecognizerDelegate>
{
    UITableView *_videoFindTableView;
    NSMutableArray *_findDataSource;
    NSMutableArray *_findHeightSource;
    WKDianboFindBigAdTableViewCell *_bigAdCell;
    WKDianboFindSmallAdTableViewCell *_smallAdCell;
}

@property(retain, nonatomic) WKDianboFindSmallAdTableViewCell *smallAdCell; // @synthesize smallAdCell=_smallAdCell;
@property(retain, nonatomic) WKDianboFindBigAdTableViewCell *bigAdCell; // @synthesize bigAdCell=_bigAdCell;
@property(retain, nonatomic) NSMutableArray *findHeightSource; // @synthesize findHeightSource=_findHeightSource;
@property(retain, nonatomic) NSMutableArray *findDataSource; // @synthesize findDataSource=_findDataSource;
@property(nonatomic) __weak UITableView *videoFindTableView; // @synthesize videoFindTableView=_videoFindTableView;
- (void).cxx_destruct;
- (void)dealloc;
- (void)tabBarSelectionDidChanged:(id)arg1;
- (void)appWillEnterForeground:(id)arg1;
- (void)calculateCellHeight;
- (void)findTipsTableViewCellClicked:(id)arg1;
- (void)wkviedoFindViewControllerBannerViewClicked:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)loadAdView;
- (void)getDataFromNet:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

