//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionReusableView.h"

@class NSTimer, UIButton, UILabel;

@interface WKVideoCategoryHeaderView : UICollectionReusableView
{
    long long _clickedCount;
    NSTimer *_timer;
    UIButton *_filterButton;
    id <WKVideoCategoryHeaderViewDelegate> _delegate;
    UILabel *_sectionTitleLabel;
}

@property(nonatomic) __weak UILabel *sectionTitleLabel; // @synthesize sectionTitleLabel=_sectionTitleLabel;
@property(nonatomic) __weak id <WKVideoCategoryHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIButton *filterButton; // @synthesize filterButton=_filterButton;
- (void).cxx_destruct;
- (void)setHeaderViewType:(long long)arg1;
- (void)filterButtonClicked:(id)arg1;
- (void)startTimer:(double)arg1;
- (void)resetCounter;

@end

