//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSString, UIImage, WKVideoEpisodeModel, WKVideoSourceModel;

@interface WKVideoDetailModel : NSObject
{
    NSString *_actors;
    NSString *_area;
    NSMutableArray *_comment;
    NSString *_cover;
    NSString *_db_url;
    NSString *_defalutfrom;
    NSString *_userSetFrom;
    NSString *_defaultSourceIcon;
    NSString *_definition;
    NSString *_desc;
    NSString *_df_icon;
    NSString *_directors;
    NSString *_grade;
    NSString *_moli_cid;
    NSString *_name;
    NSString *_operate_type;
    NSString *_over;
    NSString *_showtime;
    NSArray *_source;
    NSString *_tnum;
    NSString *_updateto;
    NSString *_vst_web;
    NSString *_wkid;
    NSString *_wktype;
    WKVideoSourceModel *_currentSourceModel;
    WKVideoEpisodeModel *_episodeModel;
    UIImage *_preImage;
}

+ (id)objectClassInArray;
@property(retain, nonatomic) UIImage *preImage; // @synthesize preImage=_preImage;
@property(retain, nonatomic) WKVideoEpisodeModel *episodeModel; // @synthesize episodeModel=_episodeModel;
@property(retain, nonatomic) WKVideoSourceModel *currentSourceModel; // @synthesize currentSourceModel=_currentSourceModel;
@property(retain, nonatomic) NSString *wktype; // @synthesize wktype=_wktype;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(retain, nonatomic) NSString *vst_web; // @synthesize vst_web=_vst_web;
@property(retain, nonatomic) NSString *updateto; // @synthesize updateto=_updateto;
@property(retain, nonatomic) NSString *tnum; // @synthesize tnum=_tnum;
@property(retain, nonatomic) NSArray *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *showtime; // @synthesize showtime=_showtime;
@property(retain, nonatomic) NSString *over; // @synthesize over=_over;
@property(retain, nonatomic) NSString *operate_type; // @synthesize operate_type=_operate_type;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *moli_cid; // @synthesize moli_cid=_moli_cid;
@property(retain, nonatomic) NSString *grade; // @synthesize grade=_grade;
@property(retain, nonatomic) NSString *directors; // @synthesize directors=_directors;
@property(retain, nonatomic) NSString *df_icon; // @synthesize df_icon=_df_icon;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *definition; // @synthesize definition=_definition;
@property(retain, nonatomic) NSString *defaultSourceIcon; // @synthesize defaultSourceIcon=_defaultSourceIcon;
@property(retain, nonatomic) NSString *userSetFrom; // @synthesize userSetFrom=_userSetFrom;
@property(retain, nonatomic) NSString *defalutfrom; // @synthesize defalutfrom=_defalutfrom;
@property(retain, nonatomic) NSString *db_url; // @synthesize db_url=_db_url;
@property(retain, nonatomic) NSString *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) NSMutableArray *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) NSString *area; // @synthesize area=_area;
@property(retain, nonatomic) NSString *actors; // @synthesize actors=_actors;
- (void).cxx_destruct;

@end

