//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKVideoCommentModel : NSObject
{
    NSString *_content;
    NSString *_create_time;
    NSString *_id;
    NSString *_parent_id;
    NSString *_praise;
    NSString *_wkid;
    double _textSizeHeight;
}

@property(nonatomic) double textSizeHeight; // @synthesize textSizeHeight=_textSizeHeight;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(retain, nonatomic) NSString *praise; // @synthesize praise=_praise;
@property(retain, nonatomic) NSString *parent_id; // @synthesize parent_id=_parent_id;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
@property(retain, nonatomic) NSString *create_time; // @synthesize create_time=_create_time;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;

@end

