//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface WKViedoCategoryModel : NSObject
{
    NSArray *_banner;
    NSArray *_types;
}

+ (void)getCategoryDataWithParams:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
+ (id)objectClassInArray;
@property(retain, nonatomic) NSArray *types; // @synthesize types=_types;
@property(retain, nonatomic) NSArray *banner; // @synthesize banner=_banner;
- (void).cxx_destruct;

@end

