//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface WKVideoDataVideoModel : NSObject
{
    NSArray *_videolist;
    NSString *_nextPage;
}

+ (id)objectClassInArray;
@property(copy, nonatomic) NSString *nextPage; // @synthesize nextPage=_nextPage;
@property(retain, nonatomic) NSArray *videolist; // @synthesize videolist=_videolist;
- (void).cxx_destruct;

@end

