//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface WKVideoHistoryModel : NSObject
{
    NSString *_wkid;
    NSString *_cover;
    NSString *_name;
    NSString *_ssid;
    NSString *_psid;
    NSString *_contentType;
    NSString *_time;
    NSString *_src;
    NSString *_intent;
    NSString *_episode;
    NSString *_subhead;
    unsigned long long _videosrc;
}

+ (id)getWebPushWkid:(id)arg1;
+ (id)videoHistoryModelWithVideoDetailModel:(id)arg1 subEpisodeModel:(id)arg2;
@property(nonatomic) unsigned long long videosrc; // @synthesize videosrc=_videosrc;
@property(retain, nonatomic) NSString *subhead; // @synthesize subhead=_subhead;
@property(retain, nonatomic) NSString *episode; // @synthesize episode=_episode;
@property(retain, nonatomic) NSString *intent; // @synthesize intent=_intent;
@property(retain, nonatomic) NSString *src; // @synthesize src=_src;
@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(retain, nonatomic) NSString *contentType; // @synthesize contentType=_contentType;
@property(retain, nonatomic) NSString *psid; // @synthesize psid=_psid;
@property(retain, nonatomic) NSString *ssid; // @synthesize ssid=_ssid;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
- (void).cxx_destruct;
- (void)saveToLocalWithBlock:(CDUnknownBlockType)arg1;

@end

