//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseSubViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WKBannerAdViewDelegate.h"
#import "WKEpisodeTableViewCellDelegate.h"
#import "WKInputTextFiledSendDelete.h"
#import "WKNavigationControllerDelegate.h"
#import "WKVideoDetailBannerViewDelegate.h"
#import "WKVideoSourceCollectionViewDelegate.h"

@class NSMutableArray, NSString, UIButton, UIImage, UITableView, UIView, WKAdModel, WKBigTreeCooperationADModel, WKEpisodeTableViewCell, WKInputTextFiled, WKReplyInputView, WKVideoDetailBannerView, WKVideoDetailViewModel, WKVideoNewCommentModel, WKVideoSourceCollectionView, WKWxShareInfoModel, WkVideoCommentData;

@interface WKVideoDetailViewController : WKBaseSubViewController <WKEpisodeTableViewCellDelegate, UITableViewDataSource, UITableViewDelegate, WKInputTextFiledSendDelete, WKVideoSourceCollectionViewDelegate, WKBannerAdViewDelegate, WKVideoDetailBannerViewDelegate, WKNavigationControllerDelegate>
{
    _Bool _alreadySendVideoReq;
    WKWxShareInfoModel *_wxShare;
    UITableView *_tableview;
    _Bool _isFold;
    WKInputTextFiled *_inputTextFiled;
    WKVideoDetailViewModel *_videoViewModel;
    WKVideoDetailBannerView *_videoBannerView;
    _Bool _toComment;
    NSString *_totalComment;
    NSString *_userSetFrom;
    UIView *_bannerAdView;
    _Bool _isShowArrow;
    WKVideoSourceCollectionView *videoSourceCollectionView;
    UIView *videoSourceCollectionMaskView;
    NSString *_wkid;
    NSString *_src;
    UIImage *_presetImage;
    NSString *_videoTitle;
    WKVideoNewCommentModel *_commentModel;
    WkVideoCommentData *_commentData;
    WKReplyInputView *_replyInputView;
    UIButton *_bgBtn;
    UIButton *_collectBtn;
    NSMutableArray *_dianZanArr;
    WKAdModel *_videoDetailADModel;
    WKAdModel *_spareDetailADModel;
    WKBigTreeCooperationADModel *_cooporationADModel;
    unsigned long long _adType;
    WKEpisodeTableViewCell *_episodeCell;
    UIView *_collectedView;
    double _introTextHeight;
}

@property(nonatomic) double introTextHeight; // @synthesize introTextHeight=_introTextHeight;
@property(nonatomic) _Bool isShowArrow; // @synthesize isShowArrow=_isShowArrow;
@property(retain, nonatomic) UIView *collectedView; // @synthesize collectedView=_collectedView;
@property(retain, nonatomic) WKEpisodeTableViewCell *episodeCell; // @synthesize episodeCell=_episodeCell;
@property(nonatomic) unsigned long long adType; // @synthesize adType=_adType;
@property(retain, nonatomic) WKBigTreeCooperationADModel *cooporationADModel; // @synthesize cooporationADModel=_cooporationADModel;
@property(retain, nonatomic) WKAdModel *spareDetailADModel; // @synthesize spareDetailADModel=_spareDetailADModel;
@property(retain, nonatomic) WKAdModel *videoDetailADModel; // @synthesize videoDetailADModel=_videoDetailADModel;
@property(retain, nonatomic) NSMutableArray *dianZanArr; // @synthesize dianZanArr=_dianZanArr;
@property(retain, nonatomic) UIButton *collectBtn; // @synthesize collectBtn=_collectBtn;
@property(retain, nonatomic) UIButton *bgBtn; // @synthesize bgBtn=_bgBtn;
@property(retain, nonatomic) WKReplyInputView *replyInputView; // @synthesize replyInputView=_replyInputView;
@property(retain, nonatomic) WkVideoCommentData *commentData; // @synthesize commentData=_commentData;
@property(retain, nonatomic) WKVideoNewCommentModel *commentModel; // @synthesize commentModel=_commentModel;
@property(retain, nonatomic) NSString *videoTitle; // @synthesize videoTitle=_videoTitle;
@property(retain, nonatomic) UIImage *presetImage; // @synthesize presetImage=_presetImage;
@property(retain, nonatomic) NSString *src; // @synthesize src=_src;
@property(retain, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(retain, nonatomic) UIView *videoSourceCollectionMaskView; // @synthesize videoSourceCollectionMaskView;
@property(retain, nonatomic) WKVideoSourceCollectionView *videoSourceCollectionView; // @synthesize videoSourceCollectionView;
- (void).cxx_destruct;
- (void)cancelInput;
- (void)showVideoSourcesView:(_Bool)arg1;
- (void)adViewWillClose:(id)arg1;
- (void)adDataDidReceived:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (long long)preferredStatusBarStyle;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)episodeScrollViewMoreButtonClickedDelegate;
- (void)episodeScrollViewButtonClickedDelegateWithTag:(unsigned long long)arg1;
- (void)collectVideoRequest;
- (void)cancelDianzan:(id)arg1;
- (void)dianZan:(id)arg1 index:(long long)arg2;
- (void)requestCommentWithId:(id)arg1 comment:(id)arg2 index:(long long)arg3;
- (void)sendCommentRequestCommentId:(id)arg1 comment:(id)arg2 index:(long long)arg3;
- (void)requestComment;
- (void)requestSDKADIfNeed;
- (void)requestSelfManageADIfNeed;
- (void)requestBigTreeCooporationADIfNeed;
- (void)reqVideoDetailV2:(id)arg1 withSrc:(id)arg2;
- (void)prepareToPlayVideoWithIndex:(long long)arg1 orSubEpisode:(id)arg2;
- (void)onVideoSourceCollectionViewDelegate:(long long)arg1;
- (void)onBannerViewSourceButtonClicked;
- (void)onBannerViewPlayButtonClicked;
- (void)scrollViewDidScroll:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)configIntroCell;
- (double)getIntroCellHeight;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)sendTuCaoText:(id)arg1;
- (void)tucaoButtonClicked;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)requestEpisodeData;
- (void)footerRereshing;
- (void)scanCollect;
- (void)collectViewHidden;
- (void)collectBtnClicked;
- (void)shareButtonClicked;
- (_Bool)hasDetailAD;
- (_Bool)hasSpareSDKAD;
- (_Bool)hasSDKAD;
- (_Bool)hasAnySdkAD;
- (_Bool)validateBigTreeADModel;
- (_Bool)hasCooporationAD;
- (void)initNavigationItem;
- (void)initTableView;
- (void)initBannerView;
- (void)initAdBannerView;
- (void)hideBottomLine;
- (void)keyboardWillHide:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (void)hideVideoSourceView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

