//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface WKWebSearchPlaceHolderHeaderView : UIView
{
    id <WKWebSearchPlaceHolderHeaderViewDelegate> _delegate;
    UIImageView *_placeHolderImageView;
}

@property(nonatomic) __weak UIImageView *placeHolderImageView; // @synthesize placeHolderImageView=_placeHolderImageView;
@property(nonatomic) __weak id <WKWebSearchPlaceHolderHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)placeHolderImageViewClick:(id)arg1;
- (void)awakeFromNib;

@end

