//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface WKWebSearchHistoryTableClearHistoryCell : UITableViewCell
{
    UILabel *_clearHistoryLabel;
}

@property(nonatomic) __weak UILabel *clearHistoryLabel; // @synthesize clearHistoryLabel=_clearHistoryLabel;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

