//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WuKongJSExport.h"

@class NSArray, NSDictionary, NSMutableArray, NSString, UIWebView;

@interface WKWebViewJSTools : NSObject <WuKongJSExport>
{
    id <WKWebViewJSToolsDeleagete> _delegate;
    NSString *_hostContent;
    UIWebView *_webview;
    NSDictionary *_cibnStatisticDic;
    NSMutableArray *_urlArray;
    NSArray *_urlStringFilerArray;
}

@property(retain) NSArray *urlStringFilerArray; // @synthesize urlStringFilerArray=_urlStringFilerArray;
@property(retain) NSMutableArray *urlArray; // @synthesize urlArray=_urlArray;
@property(retain, nonatomic) NSDictionary *cibnStatisticDic; // @synthesize cibnStatisticDic=_cibnStatisticDic;
@property(nonatomic) __weak UIWebView *webview; // @synthesize webview=_webview;
@property(retain, nonatomic) NSString *hostContent; // @synthesize hostContent=_hostContent;
@property(nonatomic) __weak id <WKWebViewJSToolsDeleagete> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webviewDidStartLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)setUrlFilter:(id)arg1;
- (id)getUserInfo;
- (id)getUserId;
- (void)update;
- (void)turnPlayBtn:(_Bool)arg1;
- (void)turnNaviBar:(_Bool)arg1;
- (void)openActivity:(id)arg1;
- (void)openFeedbackPage;
- (void)openAppDetail:(id)arg1;
- (void)openDianboDetail:(id)arg1;
- (void)setShareIconVisibility:(_Bool)arg1;
- (void)finishThis:(id)arg1;
- (void)finishThis;
- (id)getReferer;
- (id)getPrevUrl;
- (void)share:(id)arg1;
- (id)getCookie;
- (void)downloadAndPlay:(id)arg1 withHeaderJson:(id)arg2 withFileName:(id)arg3;
- (void)downloadAndPlay2:(id)arg1 withHeaderJson:(id)arg2 withFileName:(id)arg3;
- (void)sendIntentJSon:(id)arg1 withOpenRemoteControl:(_Bool)arg2;
- (id)getHostContext;
- (int)isConnected;
- (void)showmenus:(id)arg1;
- (id)getHostPlatform;
- (id)getHostChannel;
- (int)getHostVersion;
- (id)init;

@end

