//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WKBaseCollectionViewController.h"

#import "DJPhotoBrowserDelegate.h"
#import "WKPullMenuTableViewDelegate.h"

@class NSArray, NSString, UIButton, UIImage, WKPullMenuTableView, WKWebPicModel;

@interface WKWebPicCollectionViewController : WKBaseCollectionViewController <DJPhotoBrowserDelegate, WKPullMenuTableViewDelegate>
{
    int _currentIndex;
    _Bool _alreadyReq;
    NSString *_baseUrl;
    NSArray *_imageArray;
    NSArray *_menuArray;
    UIButton *_menuButton;
    WKWebPicModel *_picModel;
    WKPullMenuTableView *_pullMenuTableView;
    UIImage *_placeHolderImage;
}

+ (id)defaultWebPicCollectionViewController;
- (void).cxx_destruct;
- (id)photoBrowser:(id)arg1 placeholderImageForIndex:(long long)arg2;
- (id)photoBrowser:(id)arg1 highQualityImageURLForIndex:(long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)changeDataSource:(id)arg1;
- (void)onPullMenuTableViewDelegate:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)getImageDataSource:(id)arg1;
- (void)menuButtonClick:(id)arg1;
- (void)navigationBarMenuButton;
- (void)getSummaryDataSource;
- (void)showPullMenuTableView:(_Bool)arg1;
- (void)initMenuTableView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

