//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSTimer, UIImageView;

@interface WKWifiConnectingViewController : BaseViewController
{
    NSTimer *timer;
    long long count;
    _Bool connected;
    long long sendTime;
    UIImageView *_connectingImageView;
    NSTimer *_methodTimer;
}

@property(retain, nonatomic) NSTimer *methodTimer; // @synthesize methodTimer=_methodTimer;
@property(nonatomic) __weak UIImageView *connectingImageView; // @synthesize connectingImageView=_connectingImageView;
- (void).cxx_destruct;
- (void)clearResource;
- (void)dealConnectSuccess;
- (void)dealFail;
- (void)connetToTv;
- (void)timerAction;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)backbutAction;
- (void)viewDidLoad;

@end

