//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData, NSString;

@interface WKYunOsInstallPacket : NSObject
{
    NSString *_apkSize;
    NSString *_apkUrl;
    NSString *_appName;
    NSString *_iconUrl;
    NSString *_packageName;
    int _versionNeeded;
    NSMutableData *_buffer;
}

- (void).cxx_destruct;
- (id)encode;
- (int)length;
- (void)pre_encode;
- (id)preEncodeProperties;
- (id)initWithPkg:(id)arg1 withUrl:(id)arg2 withExtra:(id)arg3;

@end

