//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JSExport.h"

@class NSString;

@protocol WuKongJSExport <JSExport>
- (void)showmenus:(NSString *)arg1;
- (void)setUrlFilter:(NSString *)arg1;
- (NSString *)getUserInfo;
- (NSString *)getUserId;
- (void)update;
- (void)turnPlayBtn:(_Bool)arg1;
- (void)turnNaviBar:(_Bool)arg1;
- (void)openFeedbackPage;
- (void)openActivity:(NSString *)arg1;
- (void)openAppDetail:(NSString *)arg1;
- (void)openDianboDetail:(NSString *)arg1;
- (void)setShareIconVisibility:(_Bool)arg1;
- (void)finishThis:(NSString *)arg1;
- (void)finishThis;
- (NSString *)getPrevUrl;
- (void)share:(NSString *)arg1;
- (NSString *)getCookie;
- (NSString *)getHostContext;
- (int)isConnected;
- (NSString *)getHostPlatform;
- (NSString *)getHostChannel;
- (int)getHostVersion;
- (void)downloadAndPlay2:(NSString *)arg1 withHeaderJson:(NSString *)arg2 withFileName:(NSString *)arg3;
- (void)downloadAndPlay:(NSString *)arg1 withHeaderJson:(NSString *)arg2 withFileName:(NSString *)arg3;
- (void)sendIntentJSon:(NSString *)arg1 withOpenRemoteControl:(_Bool)arg2;

@optional
- (void)downloadAndPlay2:(NSString *)arg1 withHeaderJson:(NSString *)arg2 withFileName:(NSString *)arg3 __JS_EXPORT_AS__downloadAndPlay2:(id)arg4;
- (void)downloadAndPlay:(NSString *)arg1 withHeaderJson:(NSString *)arg2 withFileName:(NSString *)arg3 __JS_EXPORT_AS__downloadAndPlay:(id)arg4;
- (void)sendIntentJSon:(NSString *)arg1 withOpenRemoteControl:(_Bool)arg2 __JS_EXPORT_AS__sendIntent:(id)arg3;
@end

