//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, Target, XmPushActionNotification;

@interface XmPushActionAckNotification : NSObject <NSCoding>
{
    NSString *__debug;
    Target *__target;
    NSString *__id;
    NSString *__appId;
    NSString *__type;
    XmPushActionNotification *__request;
    long long __errorCode;
    NSString *__reason;
    NSDictionary *__extra;
    NSString *__packageName;
    NSString *__category;
    _Bool __debug_isset;
    _Bool __target_isset;
    _Bool __id_isset;
    _Bool __appId_isset;
    _Bool __type_isset;
    _Bool __request_isset;
    _Bool __errorCode_isset;
    _Bool __reason_isset;
    _Bool __extra_isset;
    _Bool __packageName_isset;
    _Bool __category_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetCategory;
- (_Bool)categoryIsSet;
@property(retain, nonatomic, getter=category, setter=setCategory:) NSString *category;
- (void)unsetPackageName;
- (_Bool)packageNameIsSet;
@property(retain, nonatomic, getter=packageName, setter=setPackageName:) NSString *packageName;
- (void)unsetExtra;
- (_Bool)extraIsSet;
@property(retain, nonatomic, getter=extra, setter=setExtra:) NSDictionary *extra;
- (void)unsetReason;
- (_Bool)reasonIsSet;
@property(retain, nonatomic, getter=reason, setter=setReason:) NSString *reason;
- (void)unsetErrorCode;
- (_Bool)errorCodeIsSet;
@property(nonatomic, getter=errorCode, setter=setErrorCode:) long long errorCode;
- (void)unsetRequest;
- (_Bool)requestIsSet;
@property(retain, nonatomic, getter=request, setter=setRequest:) XmPushActionNotification *request;
- (void)unsetType;
- (_Bool)typeIsSet;
@property(retain, nonatomic, getter=type, setter=setType:) NSString *type;
- (void)unsetAppId;
- (_Bool)appIdIsSet;
@property(retain, nonatomic, getter=appId, setter=setAppId:) NSString *appId;
- (void)unsetId;
- (_Bool)idIsSet;
@property(retain, nonatomic, getter=id, setter=setId:) NSString *id;
- (void)unsetTarget;
- (_Bool)targetIsSet;
@property(retain, nonatomic, getter=target, setter=setTarget:) Target *target;
- (void)unsetDebug;
- (_Bool)debugIsSet;
@property(retain, nonatomic, getter=debug, setter=setDebug:) NSString *debug;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDebug:(id)arg1 target:(id)arg2 id:(id)arg3 appId:(id)arg4 type:(id)arg5 request:(id)arg6 errorCode:(long long)arg7 reason:(id)arg8 extra:(id)arg9 packageName:(id)arg10 category:(id)arg11;

@end

