//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSDictionary, NSString, Target;

@interface XmPushActionPresence : NSObject <NSCoding>
{
    NSString *__debug;
    Target *__target;
    NSString *__id;
    NSString *__appId;
    NSString *__appVersion;
    NSString *__sdkVersion;
    NSDictionary *__params;
    _Bool __isOnline;
    NSString *__from;
    _Bool __debug_isset;
    _Bool __target_isset;
    _Bool __id_isset;
    _Bool __appId_isset;
    _Bool __appVersion_isset;
    _Bool __sdkVersion_isset;
    _Bool __params_isset;
    _Bool __isOnline_isset;
    _Bool __from_isset;
}

- (id)description;
- (void)write:(id)arg1;
- (void)read:(id)arg1;
- (void)unsetFrom;
- (_Bool)fromIsSet;
@property(retain, nonatomic, getter=from, setter=setFrom:) NSString *from;
- (void)unsetIsOnline;
- (_Bool)isOnlineIsSet;
@property(nonatomic, getter=isOnline, setter=setIsOnline:) _Bool isOnline;
- (void)unsetParams;
- (_Bool)paramsIsSet;
@property(retain, nonatomic, getter=params, setter=setParams:) NSDictionary *params;
- (void)unsetSdkVersion;
- (_Bool)sdkVersionIsSet;
@property(retain, nonatomic, getter=sdkVersion, setter=setSdkVersion:) NSString *sdkVersion;
- (void)unsetAppVersion;
- (_Bool)appVersionIsSet;
@property(retain, nonatomic, getter=appVersion, setter=setAppVersion:) NSString *appVersion;
- (void)unsetAppId;
- (_Bool)appIdIsSet;
@property(retain, nonatomic, getter=appId, setter=setAppId:) NSString *appId;
- (void)unsetId;
- (_Bool)idIsSet;
@property(retain, nonatomic, getter=id, setter=setId:) NSString *id;
- (void)unsetTarget;
- (_Bool)targetIsSet;
@property(retain, nonatomic, getter=target, setter=setTarget:) Target *target;
- (void)unsetDebug;
- (_Bool)debugIsSet;
@property(retain, nonatomic, getter=debug, setter=setDebug:) NSString *debug;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDebug:(id)arg1 target:(id)arg2 id:(id)arg3 appId:(id)arg4 appVersion:(id)arg5 sdkVersion:(id)arg6 params:(id)arg7 isOnline:(_Bool)arg8 from:(id)arg9;

@end

