//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XMXmppStreamDelegate.h"

@class MiPushXMPPJID, NSMutableArray, NSString, XMMulticastDelegate<XMXmppConnectionDelegate>, XMXmppStreamConfig;

@interface XMXmppConnectionManager : NSObject <XMXmppStreamDelegate>
{
    struct dispatch_queue_s *mConnectionQueue;
    NSMutableArray *mChannelList;
    id <XMXmppStreamProtocol> mXmppStream;
    XMXmppStreamConfig *mXmppStreamConfig;
    NSString *mConnectChallenge;
    XMMulticastDelegate<XMXmppConnectionDelegate> *mConnectionMultiDelegate;
    MiPushXMPPJID *mHostJid;
    _Bool isForceBreakConnect;
    id <XMXmppHostConnectProtocol> mHostConnectDelegate;
}

@property(nonatomic) id <XMXmppHostConnectProtocol> mHostConnectDelegate; // @synthesize mHostConnectDelegate;
- (void).cxx_destruct;
- (_Bool)forwardErrorInElement:(id)arg1;
- (void)disposeXmppStream_;
- (_Bool)createXmppStream_;
- (void)xmppStream:(id)arg1 bytesDisconnected:(long long)arg2;
- (void)xmppStream:(id)arg1 bytesConnected:(long long)arg2;
- (void)xmppStream:(id)arg1 bytesRecv:(long long)arg2;
- (void)xmppStream:(id)arg1 bytesSent:(long long)arg2;
- (void)xmppDidNotReceivePong:(id)arg1;
- (void)xmppDidReceivePresence:(id)arg1;
- (void)xmppStreamDidAuthenticate:(id)arg1;
- (void)xmppDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)xmppDidConnect:(id)arg1;
- (void)xmppConnectionError:(id)arg1;
- (void)xmppWillConnect:(id)arg1;
- (void)xmppNetworkNotReachable:(id)arg1;
- (void)didReceiveError:(id)arg1 error:(id)arg2;
- (_Bool)didReceiveIQ:(id)arg1 iq:(id)arg2;
- (void)didReceiveMessage:(id)arg1 message:(id)arg2;
- (void)sendWakeupPing;
- (void)sendSleepPing;
- (void)sendMessage:(id)arg1 channel:(id)arg2;
- (void)onBecomeOffline:(_Bool)arg1;
- (void)onBecomeOnline;
- (void)onServerConnected:(id)arg1;
- (void)authenticateBind:(id)arg1 error:(id *)arg2;
- (void)recordBindInfoToConfig:(id)arg1;
- (void)authenticateByBindInfo_:(id)arg1;
- (id)renewBindInfoByStreamConfig:(id)arg1;
- (void)disconnect;
- (void)connect;
- (void)removeXmppChannel:(id)arg1;
- (void)addXmppChannel:(id)arg1;
- (void)removeConnectionDelegate:(id)arg1;
- (void)addConnectionDelegate:(id)arg1 delegateQueue:(struct dispatch_queue_s *)arg2;
- (_Bool)isDisconnected;
- (_Bool)isConnected;
- (id)connectionChallenge;
- (struct dispatch_queue_s *)connectionQueue;
- (void)dealloc;
- (id)initWithHostJid:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

