//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface YMFAd : NSObject
{
    id <YMFDelegate> _ymfDelegate;
    NSString *_clickedUrl;
    NSArray *_clicktracks;
}

+ (id)getOnlineParams;
@property(retain, nonatomic) NSArray *clicktracks; // @synthesize clicktracks=_clicktracks;
@property(copy, nonatomic) NSString *clickedUrl; // @synthesize clickedUrl=_clickedUrl;
@property(nonatomic) __weak id <YMFDelegate> ymfDelegate; // @synthesize ymfDelegate=_ymfDelegate;
- (void).cxx_destruct;
- (void)requestWithURL:(id)arg1 retry:(long long)arg2 success:(CDUnknownBlockType)arg3 failture:(CDUnknownBlockType)arg4;
- (void)reportClickedEvent:(id)arg1;
- (void)reportShowEvent:(id)arg1;
- (void)requestYMFAdMsg:(CDUnknownBlockType)arg1 failture:(CDUnknownBlockType)arg2;
- (void)apxmClickedAction:(id)arg1;
- (void)createAdImageView:(id)arg1;
- (void)loadAd;
- (id)initWithDelegate:(id)arg1;

@end

