//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ZhiboIntentModel : NSObject
{
    NSString *_intent;
    NSString *_name;
    NSString *_wkicon;
    NSString *_wkid;
}

@property(copy, nonatomic) NSString *wkid; // @synthesize wkid=_wkid;
@property(copy, nonatomic) NSString *wkicon; // @synthesize wkicon=_wkicon;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *intent; // @synthesize intent=_intent;
- (void).cxx_destruct;
- (id)intentModelToSubModel;

@end

