//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIGridViewCell.h"

@class UIImageView, UILabel;

@interface ADCarCell : UIGridViewCell
{
    UIImageView *_imgView;
    UILabel *_lblText;
}

@property(nonatomic) __weak UILabel *lblText; // @synthesize lblText=_lblText;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
- (void).cxx_destruct;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;

@end

