//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface Add_Control : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSMutableArray *imageList;
    NSMutableArray *datalist;
    NSMutableArray *indexlist;
    float width;
    float height;
    float width_make;
    int w;
    id <AddBtnViewDelegate> _delegate;
    NSString *_snid;
    NSString *_snname;
    NSString *_snpass;
    NSString *_DeviceNumber;
    UITableView *_table;
}

@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) NSString *DeviceNumber; // @synthesize DeviceNumber=_DeviceNumber;
@property(retain, nonatomic) NSString *snpass; // @synthesize snpass=_snpass;
@property(retain, nonatomic) NSString *snname; // @synthesize snname=_snname;
@property(retain, nonatomic) NSString *snid; // @synthesize snid=_snid;
@property(retain) id <AddBtnViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)serviceadd:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)UIinit;
- (void)saveMainBtnInter:(int)arg1 Value:(_Bool)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

