//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class Alarm, NSIndexPath, NSString, UILabel;

@interface AlarmHistoryCell : UITableViewCell
{
    int _alarmType;
    UILabel *_deviceLabel;
    UILabel *_typeLabel;
    UILabel *_timeLabel;
    UILabel *_groupItemLabel;
    UILabel *_deviceLabelText;
    UILabel *_typeLabelText;
    Alarm *_alarm;
    NSString *_deviceId;
    NSString *_alarmTime;
    NSIndexPath *_indexPath;
    id <AlarmHistoryCellDelegate> _delegate;
}

@property(retain, nonatomic) id <AlarmHistoryCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) int alarmType; // @synthesize alarmType=_alarmType;
@property(retain, nonatomic) NSString *alarmTime; // @synthesize alarmTime=_alarmTime;
@property(retain, nonatomic) NSString *deviceId; // @synthesize deviceId=_deviceId;
@property(retain, nonatomic) Alarm *alarm; // @synthesize alarm=_alarm;
@property(retain, nonatomic) UILabel *typeLabelText; // @synthesize typeLabelText=_typeLabelText;
@property(retain, nonatomic) UILabel *deviceLabelText; // @synthesize deviceLabelText=_deviceLabelText;
@property(retain, nonatomic) UILabel *groupItemLabel; // @synthesize groupItemLabel=_groupItemLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UILabel *deviceLabel; // @synthesize deviceLabel=_deviceLabel;
- (id)groupName:(int)arg1;
- (void)gestureToLongPress:(id)arg1;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

