//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AutoReloginTask : NSObject
{
    int _autoReloginCount;
    int _currentVersion;
    int _currerntAppID;
    NSString *_currentAuthStr;
    int _keepAliveInterval;
    int _loginedCount;
}

- (void).cxx_destruct;
- (void)onLoginResponsedWithCode:(int)arg1;
- (void)doLogin;
- (void)autoReloginRightNow;
- (void)startTicksTimerWithTimeInterval:(id)arg1;
- (void)autoRelogin;
- (id)initWithLoginVersion:(int)arg1 AppID:(int)arg2 AuthStr:(id)arg3 andKeepAliveInterval:(int)arg4;

@end

