//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

@class BottomBar;

@interface AutoTabBarController : UITabBarController
{
    BottomBar *_bottomBar;
}

@property(retain, nonatomic) BottomBar *bottomBar; // @synthesize bottomBar=_bottomBar;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)didReceiveMemoryWarning;
- (void)setBottomBarHidden:(_Bool)arg1;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (void)onItemPress:(id)arg1;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

