//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "PushtoScan.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class DBhelper, DXPopover, DeviceEntity, NSMutableArray, NSString, UITableView;

@interface Bed : UITableViewController <UITableViewDelegate, UITableViewDataSource, PushtoScan>
{
    DBhelper *db;
    NSMutableArray *_deviceList;
    DeviceEntity *device;
    DXPopover *_popover;
    UITableView *_table;
}

@property(retain, nonatomic) UITableView *table; // @synthesize table=_table;
@property(retain, nonatomic) DXPopover *popover; // @synthesize popover=_popover;
- (void).cxx_destruct;
- (void)showWarningAlert:(id)arg1 didFinish:(CDUnknownBlockType)arg2;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)pushViewController:(id)arg1;
- (void)pushDeviceViewControllerWithDevice:(id)arg1 withPwd:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)pushtoaddscan;
- (void)didSelectedPopoverViewRow:(long long)arg1;
- (void)addPress:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

