//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class HFSmartLink, NSString, NSTimer, NSUserDefaults, UIImageView, UILabel, UITextFieldEx, UIView;

@interface Bed_Wifi : UIViewController <UITextFieldDelegate>
{
    NSUserDefaults *myDefault;
    NSTimer *_timer;
    HFSmartLink *smtlk;
    _Bool isconnecting;
    int mytime;
    NSString *dev_mac;
    UITextFieldEx *_textFieldPassword;
    UITextFieldEx *_textFieldSSID;
    UIView *_ViewDJS;
    UILabel *_lblTime;
    UIImageView *_gridView;
    id <PushtoScan> _delegate;
}

@property(retain) id <PushtoScan> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UIImageView *gridView; // @synthesize gridView=_gridView;
@property(nonatomic) __weak UILabel *lblTime; // @synthesize lblTime=_lblTime;
@property(retain, nonatomic) UIView *ViewDJS; // @synthesize ViewDJS=_ViewDJS;
@property(nonatomic) __weak UITextFieldEx *textFieldSSID; // @synthesize textFieldSSID=_textFieldSSID;
@property(nonatomic) __weak UITextFieldEx *textFieldPassword; // @synthesize textFieldPassword=_textFieldPassword;
- (void).cxx_destruct;
- (id)fetchSSIDInfo;
- (void)showWifiSsid;
- (id)getspwdByssid:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)btnDJSCancelTouchUpInside:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)timerOutEasy:(id)arg1;
- (void)hidDJS;
- (void)showDJS;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showAlertWithMsg:(id)arg1 title:(id)arg2;
- (void)savePswd;
- (void)btnGoTouchUpInside:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

