//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIAlertViewDelegate.h"

@class AccountController, LoginController, MBProgressHUD, NSString, UILabel, UITextField;

@interface BindPhoneController2 : UIViewController <UIAlertViewDelegate>
{
    _Bool _isCanResend;
    _Bool _isRegister;
    NSString *_countryCode;
    NSString *_phoneNumber;
    UITextField *_field1;
    MBProgressHUD *_progressAlert;
    UILabel *_resendLabel;
    AccountController *_accountController;
    LoginController *_loginController;
}

@property _Bool isRegister; // @synthesize isRegister=_isRegister;
@property(retain, nonatomic) LoginController *loginController; // @synthesize loginController=_loginController;
@property(retain, nonatomic) AccountController *accountController; // @synthesize accountController=_accountController;
@property(retain, nonatomic) UILabel *resendLabel; // @synthesize resendLabel=_resendLabel;
@property _Bool isCanResend; // @synthesize isCanResend=_isCanResend;
@property(retain, nonatomic) MBProgressHUD *progressAlert; // @synthesize progressAlert=_progressAlert;
@property(retain, nonatomic) UITextField *field1; // @synthesize field1=_field1;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) NSString *countryCode; // @synthesize countryCode=_countryCode;
- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)countDownTime;
- (void)onResendPress:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onNextPress;
- (void)normalButton:(id)arg1;
- (void)lightButton:(id)arg1;
- (void)onBackPress;
- (void)onKeyBoardDown:(id)arg1;
- (void)initComponent;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

