//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SortBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class BindPhoneController, LoginController, NSArray, NSString, NewRegisterController, UILabel, UITableView;

@interface ChooseCountryController : UIViewController <UITableViewDataSource, UITableViewDelegate, SortBarDelegate>
{
    BindPhoneController *_bindPhoneController;
    LoginController *_loginController;
    NewRegisterController *_registerController;
    UITableView *_tableView;
    NSArray *_countrys_zh;
    NSArray *_countrys_en;
    NSArray *_countrys;
    NSArray *_datas;
    UILabel *_promptView;
}

@property(retain, nonatomic) UILabel *promptView; // @synthesize promptView=_promptView;
@property(retain, nonatomic) NSArray *datas; // @synthesize datas=_datas;
@property(retain, nonatomic) NSArray *countrys; // @synthesize countrys=_countrys;
@property(retain, nonatomic) NSArray *countrys_en; // @synthesize countrys_en=_countrys_en;
@property(retain, nonatomic) NSArray *countrys_zh; // @synthesize countrys_zh=_countrys_zh;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) NewRegisterController *registerController; // @synthesize registerController=_registerController;
@property(retain, nonatomic) LoginController *loginController; // @synthesize loginController=_loginController;
@property(retain, nonatomic) BindPhoneController *bindPhoneController; // @synthesize bindPhoneController=_bindPhoneController;
- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)onSortBarTouchEnd:(id)arg1;
- (void)onSortBarChange:(id)arg1 index:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)onBackPress;
- (void)initComponent;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

