//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, UILabel;

@interface ChooseCountryCell : UITableViewCell
{
    NSString *_leftLabelText;
    UILabel *_leftLabelView;
    NSString *_rightLabelText;
    UILabel *_rightLabelView;
}

@property(retain, nonatomic) UILabel *rightLabelView; // @synthesize rightLabelView=_rightLabelView;
@property(retain, nonatomic) NSString *rightLabelText; // @synthesize rightLabelText=_rightLabelText;
@property(retain, nonatomic) UILabel *leftLabelView; // @synthesize leftLabelView=_leftLabelView;
@property(retain, nonatomic) NSString *leftLabelText; // @synthesize leftLabelText=_leftLabelText;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

