//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ContactDAO : NSObject
{
    struct sqlite3 *_db;
}

+ (void)setDBVersion:(long long)arg1;
+ (long long)getDBVersion;
@property(nonatomic) struct sqlite3 *db; // @synthesize db=_db;
- (_Bool)update:(id)arg1;
- (id)isContact:(id)arg1;
- (_Bool)delete:(id)arg1;
- (id)findAll;
- (_Bool)insert:(id)arg1;
- (_Bool)closeDB;
- (_Bool)openDB;
- (id)getCreateTableString;
- (id)dbPath;
- (void)updateDB:(long long)arg1;
- (id)init;

@end

