//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ShakeManagerDelegate.h"

@class NSMutableDictionary, NSString;

@interface FListManager : NSObject <ShakeManagerDelegate>
{
    _Bool _isReloadData;
    NSMutableDictionary *_map;
    NSMutableDictionary *_localDevices;
}

+ (id)sharedFList;
@property _Bool isReloadData; // @synthesize isReloadData=_isReloadData;
@property(retain, nonatomic) NSMutableDictionary *localDevices; // @synthesize localDevices=_localDevices;
@property(retain, nonatomic) NSMutableDictionary *map; // @synthesize map=_map;
- (void)getDefenceStates;
- (void)updatecontact:(id)arg1;
- (void)delete:(id)arg1;
- (void)insertcontact:(id)arg1;
- (void)setDefenceStateWithId:(id)arg1 type:(long long)arg2;
- (_Bool)getIsClickDefenceStateBtn:(id)arg1;
- (void)setIsClickDefenceStateBtnWithId:(id)arg1 isClick:(_Bool)arg2;
- (void)setStateWithId:(id)arg1 state:(long long)arg2;
- (long long)getState:(id)arg1;
- (void)setMessageCountWithId:(id)arg1 count:(long long)arg2;
- (long long)getMessageCount:(id)arg1;
- (void)setTypeWithId:(id)arg1 type:(long long)arg2;
- (long long)getType:(id)arg1;
- (id)getContacts;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

