//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITabBarController.h"

#import "GKBaseViewControllerDelegate.h"
#import "RwWaitViewDelegate.h"

@class AppDelegate, DBhelper, GKBaseViewController, GKDeviceManager, NSMutableArray, NSString, RwWaitView, UIButton, UIImageView;

@interface GK_menu : UITabBarController <GKBaseViewControllerDelegate, RwWaitViewDelegate>
{
    DBhelper *helper;
    _Bool _isLan;
    _Bool message;
    _Bool _isCon;
    GKDeviceManager *_deviceManager;
    NSMutableArray *_viewControllers;
    GKBaseViewController *_curViewController;
    RwWaitView *rw;
    AppDelegate *delegate;
    UIButton *_btnPower;
    UIImageView *_imageViewFlag;
}

@property(nonatomic) __weak UIImageView *imageViewFlag; // @synthesize imageViewFlag=_imageViewFlag;
@property(nonatomic) __weak UIButton *btnPower; // @synthesize btnPower=_btnPower;
- (void).cxx_destruct;
- (void)MessageBack:(id)arg1;
- (void)waitView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)btnPowerTouchUpInside:(id)arg1;
- (void)uIConnectState:(id)arg1;
- (void)rfcodeStudy:(id)arg1;
- (id)getPowerData;
- (void)UIUpData;
- (void)Updata;
- (void)SubUpData:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)btnLong:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

