//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIButton, UIImageView, UILabel, UIView;

@interface GKWindowTableViewCell : UITableViewCell
{
    int _deviceType;
    int _type;
    int _flag;
    UILabel *_lblTitle;
    UIButton *_title;
    UIImageView *_gridView;
    UIView *_btn_three;
    UIImageView *_btn_close;
    UIImageView *_btn_open;
    id <GKWindowTableViewCellDelegate> _delegate;
    UIButton *_btnClose;
    UIButton *_btnPas;
    UIButton *_btnOpen;
}

@property(nonatomic) __weak UIButton *btnOpen; // @synthesize btnOpen=_btnOpen;
@property(nonatomic) __weak UIButton *btnPas; // @synthesize btnPas=_btnPas;
@property(nonatomic) __weak UIButton *btnClose; // @synthesize btnClose=_btnClose;
@property(retain) id <GKWindowTableViewCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UIImageView *btn_open; // @synthesize btn_open=_btn_open;
@property(retain, nonatomic) UIImageView *btn_close; // @synthesize btn_close=_btn_close;
@property(retain, nonatomic) UIView *btn_three; // @synthesize btn_three=_btn_three;
@property(nonatomic) UIImageView *gridView; // @synthesize gridView=_gridView;
@property(nonatomic) __weak UIButton *title; // @synthesize title=_title;
@property(nonatomic) UILabel *lblTitle; // @synthesize lblTitle=_lblTitle;
@property int flag; // @synthesize flag=_flag;
@property int type; // @synthesize type=_type;
@property int deviceType; // @synthesize deviceType=_deviceType;
- (void).cxx_destruct;
- (void)btnLong3:(id)arg1;
- (void)btnLong2:(id)arg1;
- (void)btnLong1:(id)arg1;
- (void)changetitle:(id)arg1;
- (void)cellInit;
- (void)initwidth:(int)arg1;
- (void)btnOpenTouchUpInside:(id)arg1;
- (void)btnCloseTouchUpInside:(id)arg1;
- (void)btnPaTouchUpInside:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

