//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UILabel;

@interface GroupHead : UIControl
{
    _Bool _isStatusLabelHidden;
    UILabel *_statusLabel;
    UILabel *_groupNameLabel;
    UIImageView *_backImageView;
}

@property _Bool isStatusLabelHidden; // @synthesize isStatusLabelHidden=_isStatusLabelHidden;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
@property(retain, nonatomic) UILabel *groupNameLabel; // @synthesize groupNameLabel=_groupNameLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
- (void)setStatusLabelHidden:(_Bool)arg1;
- (void)refreshUIWithDictionary:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

