//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString, Udpproxy2;

@interface HFSmartLink : NSObject
{
    CDUnknownBlockType processBlock;
    CDUnknownBlockType successBlock;
    CDUnknownBlockType failBlock;
    CDUnknownBlockType stopBlock;
    CDUnknownBlockType endBlock;
    NSString *pswd;
    char cont[200];
    int cont_len;
    _Bool isconnnecting;
    _Bool userStoping;
    long long sendTime;
    NSMutableDictionary *deviceDic;
    Udpproxy2 *udp;
    _Bool withV3x;
    _Bool _isConfigOneDevice;
    long long _waitTimers;
}

+ (id)shareInstence;
@property(nonatomic) long long waitTimers; // @synthesize waitTimers=_waitTimers;
@property(nonatomic) _Bool isConfigOneDevice; // @synthesize isConfigOneDevice=_isConfigOneDevice;
- (void).cxx_destruct;
- (void)recvNewModule;
- (void)sendOnePackageByLen:(long long)arg1;
- (void)sendSmtlkV30:(int)arg1;
- (void)connectV70;
- (void)closeWithBlock:(CDUnknownBlockType)arg1;
- (void)stopWithBlock:(CDUnknownBlockType)arg1;
- (void)doProcess;
- (void)startWithSSID:(id)arg1 Key:(id)arg2 withV3x:(_Bool)arg3 processblock:(CDUnknownBlockType)arg4 successBlock:(CDUnknownBlockType)arg5 failBlock:(CDUnknownBlockType)arg6 endBlock:(CDUnknownBlockType)arg7;
- (id)init;

@end

