//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "KTPhotoViewDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, NSTimer, UIBarButtonItem, UIScrollView, UIToolbar;

@interface KTPhotoScrollViewController : UIViewController <UIScrollViewDelegate, UIActionSheetDelegate, KTPhotoViewDelegate>
{
    id <KTPhotoBrowserDataSource> dataSource_;
    UIScrollView *scrollView_;
    UIToolbar *toolbar_;
    unsigned long long startWithIndex_;
    long long currentIndex_;
    long long photoCount_;
    NSMutableArray *photoViews_;
    int firstVisiblePageIndexBeforeRotation_;
    double percentScrolledIntoFirstVisiblePage_;
    long long statusBarStyle_;
    _Bool statusbarHidden_;
    _Bool isChromeHidden_;
    _Bool rotationInProgress_;
    _Bool viewDidAppearOnce_;
    _Bool navbarWasTranslucent_;
    NSTimer *chromeHideTimer_;
    UIBarButtonItem *nextButton_;
    UIBarButtonItem *previousButton_;
}

@property(nonatomic, getter=isStatusbarHidden) _Bool statusbarHidden; // @synthesize statusbarHidden=statusbarHidden_;
@property(nonatomic) long long statusBarStyle; // @synthesize statusBarStyle=statusBarStyle_;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)exportPhoto;
- (void)trashPhoto;
- (void)previousPhoto;
- (void)nextPhoto;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)cancelChromeDisplayTimer;
- (void)startChromeDisplayTimer;
- (void)showChrome;
- (void)hideChrome;
- (void)toggleChrome:(_Bool)arg1;
- (void)toggleChromeDisplay;
- (id)rotatingFooterView;
- (void)didRotateFromInterfaceOrientation:(long long)arg1;
- (void)willAnimateRotationToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (void)layoutScrollViewSubviews;
- (void)updateToolbarWithOrientation:(long long)arg1;
- (void)setCurrentIndex:(long long)arg1;
- (void)unloadPhoto:(long long)arg1;
- (void)reLoadPhoto:(long long)arg1;
- (void)KTPhotoViewDeleteImage:(long long)arg1;
- (void)loadPhoto:(long long)arg1;
- (struct CGRect)frameForPageAtIndex:(unsigned long long)arg1;
- (struct CGRect)frameForPagingScrollView;
- (void)toggleNavButtons;
- (void)deleteCurrentPhoto;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)setScrollViewContentSize;
- (void)scrollToIndex:(long long)arg1;
- (void)setTitleWithCurrentPhotoIndex;
- (void)loadView;
- (id)initWithDataSource:(id)arg1 andStartWithPhotoAtIndex:(unsigned long long)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

