//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "KTThumbsViewDataSource.h"

@class KTThumbsView, NSString;

@interface KTThumbsViewController : UIViewController <KTThumbsViewDataSource>
{
    id <KTPhotoBrowserDataSource> dataSource_;
    KTThumbsView *scrollView_;
    _Bool viewDidAppearOnce_;
    _Bool navbarWasTranslucent_;
}

@property(retain, nonatomic) id <KTPhotoBrowserDataSource> dataSource; // @synthesize dataSource=dataSource_;
- (id)thumbsView:(id)arg1 thumbForIndex:(long long)arg2;
- (long long)thumbsViewNumberOfThumbs:(id)arg1;
- (void)didSelectThumbAtIndex:(unsigned long long)arg1;
- (void)reloadThumbs;
- (void)didLoadThumbs;
- (void)willLoadThumbs;
- (void)viewDidUnload;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)loadView;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

