//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class KTThumbsViewController, NSMutableSet, NSString;

@interface KTThumbsView : UIScrollView <UIScrollViewDelegate>
{
    id <KTThumbsViewDataSource> dataSource_;
    KTThumbsViewController *controller_;
    _Bool thumbsHaveBorder_;
    long long thumbsPerRow_;
    struct CGSize thumbSize_;
    NSMutableSet *reusableThumbViews_;
    long long firstVisibleIndex_;
    long long lastVisibleIndex_;
    long long lastItemsPerRow_;
}

@property(nonatomic) struct CGSize thumbSize; // @synthesize thumbSize=thumbSize_;
@property(nonatomic) long long thumbsPerRow; // @synthesize thumbsPerRow=thumbsPerRow_;
@property(nonatomic) _Bool thumbsHaveBorder; // @synthesize thumbsHaveBorder=thumbsHaveBorder_;
@property(nonatomic) KTThumbsViewController *controller; // @synthesize controller=controller_;
@property(nonatomic) id <KTThumbsViewDataSource> dataSource; // @synthesize dataSource=dataSource_;
- (void)layoutSubviews;
- (void)reloadData;
- (void)queueReusableThumbViews;
- (id)dequeueReusableThumbView;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

