//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class AppDelegate, GKDeviceManager, GKSubDevice, NSMutableArray, UIButton, UITextFieldEx;

@interface Light_add : UIViewController
{
    int deviceType;
    GKSubDevice *sub;
    AppDelegate *delegate;
    _Bool message;
    GKDeviceManager *_manager;
    NSMutableArray *_dataList;
    _Bool _isLan;
    UITextFieldEx *_light_name;
    UIButton *_one;
    UIButton *_two;
    UIButton *_three;
    UIButton *_four;
    UIButton *_light_80;
    UIButton *_light_62;
    UIButton *_light_63;
}

@property(retain, nonatomic) UIButton *light_63; // @synthesize light_63=_light_63;
@property(retain, nonatomic) UIButton *light_62; // @synthesize light_62=_light_62;
@property(retain, nonatomic) UIButton *light_80; // @synthesize light_80=_light_80;
@property(retain, nonatomic) UIButton *four; // @synthesize four=_four;
@property(retain, nonatomic) UIButton *three; // @synthesize three=_three;
@property(retain, nonatomic) UIButton *two; // @synthesize two=_two;
@property(retain, nonatomic) UIButton *one; // @synthesize one=_one;
@property(retain, nonatomic) UITextFieldEx *light_name; // @synthesize light_name=_light_name;
@property _Bool isLan; // @synthesize isLan=_isLan;
- (void).cxx_destruct;
- (void)MessageBack:(id)arg1;
- (void)add;
- (void)didReceiveMemoryWarning;
- (void)typetouch:(id)arg1;
- (void)ontouch:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)viewDidLoad;

@end

