//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol LightRFTableViewCellDelegate <NSObject>
- (void)lightRFStydybtnLongTouchNum:(int)arg1;
- (void)lightRFTbtnLongTouchNum:(int)arg1;
- (void)lightRFTbtnTouchUpInside:(int)arg1;
@end

