//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UINavigationController.h"

#import "P2PClientDelegate.h"

@class Contact, ContactController, NSString;

@interface MainController : UINavigationController <P2PClientDelegate>
{
    ContactController *contactController;
    _Bool _isShowP2PView;
    NSString *_contactName;
    Contact *_contact;
    id <MainControllerDelegate> _mainControllerDelegate;
}

@property(nonatomic) id <MainControllerDelegate> mainControllerDelegate; // @synthesize mainControllerDelegate=_mainControllerDelegate;
@property(retain, nonatomic) Contact *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) NSString *contactName; // @synthesize contactName=_contactName;
@property(nonatomic) _Bool isShowP2PView; // @synthesize isShowP2PView=_isShowP2PView;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)P2PClientReady:(id)arg1;
- (void)P2PClientAccept:(id)arg1;
- (void)P2PClientReject:(id)arg1;
- (void)dismissP2PView:(CDUnknownBlockType)arg1;
- (void)dismissP2PView;
- (void)P2PClientCalling:(id)arg1;
- (void)presentMonitorInterface;
- (void)setUpCallWithId:(id)arg1 password:(id)arg2 callType:(int)arg3;
- (void)initComponent;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

