//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MBSliderLabel, NSString, NSTimer, UIColor, UISlider;

@interface MBSliderView : UIView
{
    UISlider *_slider;
    MBSliderLabel *_label;
    id <MBSliderViewDelegate> delegate;
    _Bool _sliding;
    NSTimer *timer;
    id <MBSliderViewDelegate> _delegate;
}

@property(nonatomic) id <MBSliderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)clearPixel;
- (void)dealloc;
- (void)setThumbColor:(int)arg1;
- (void)sliderChanged:(id)arg1;
- (void)sliderDown:(id)arg1;
- (void)timerFired:(id)arg1;
- (void)sliderUp:(id)arg1;
@property(nonatomic) UIColor *labelColor;
@property(nonatomic) NSString *text;
@property(nonatomic) _Bool enabled;
- (void)loadContent;
- (void)awakeFromNib;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

