//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MD5Manager : NSObject
{
}

+ (_Bool)GetMD5PasswordWithSrc:(const char *)arg1 Dst:(char *)arg2;
+ (unsigned int)GetTreatedPassword:(const char *)arg1;

@end

