//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIImageView, UILabel, UIScrollView;

@interface MJRefreshBaseView : UIView
{
    UIScrollView *_scrollView;
    id <MJRefreshBaseViewDelegate> _delegate;
    CDUnknownBlockType _beginRefreshingBlock;
    UILabel *_lastUpdateTimeLabel;
    UILabel *_statusLabel;
    UIImageView *_arrowImage;
    UIActivityIndicatorView *_activityView;
    int _state;
    unsigned int _normalId;
    unsigned int _pullId;
    unsigned int _refreshingId;
    unsigned int _endRefreshId;
}

@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <MJRefreshBaseViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType beginRefreshingBlock; // @synthesize beginRefreshingBlock=_beginRefreshingBlock;
@property(readonly, nonatomic) __weak UIImageView *arrowImage; // @synthesize arrowImage=_arrowImage;
@property(readonly, nonatomic) __weak UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(readonly, nonatomic) __weak UILabel *lastUpdateTimeLabel; // @synthesize lastUpdateTimeLabel=_lastUpdateTimeLabel;
- (void).cxx_destruct;
- (void)endRefreshing;
- (void)beginRefreshing;
@property(readonly, nonatomic, getter=isRefreshing) _Bool refreshing;
- (void)setState:(int)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)free;
- (void)setFrame:(struct CGRect)arg1;
- (unsigned int)loadId:(id)arg1;
- (id)labelWithFontSize:(double)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)awakeFromNib;
- (void)initial;
- (id)initWithScrollView:(id)arg1;

@end

