//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class Contact, MBProgressHUD, NSString, UILabel, UITextField, UIView;

@interface ModifyDevicePasswordController : UIViewController <UITextFieldDelegate>
{
    _Bool _isIntoHereOfClickWeakPwd;
    Contact *_contact;
    UITextField *_field1;
    UITextField *_field2;
    UITextField *_field3;
    NSString *_lastSetOriginPassowrd;
    NSString *_lastSetNewPassowrd;
    MBProgressHUD *_progressAlert;
    UIView *_pwdStrengthView;
    UILabel *_redLabelPrompt;
    UIView *_contentView;
}

@property _Bool isIntoHereOfClickWeakPwd; // @synthesize isIntoHereOfClickWeakPwd=_isIntoHereOfClickWeakPwd;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UILabel *redLabelPrompt; // @synthesize redLabelPrompt=_redLabelPrompt;
@property(retain, nonatomic) UIView *pwdStrengthView; // @synthesize pwdStrengthView=_pwdStrengthView;
@property(retain, nonatomic) MBProgressHUD *progressAlert; // @synthesize progressAlert=_progressAlert;
@property(retain, nonatomic) NSString *lastSetNewPassowrd; // @synthesize lastSetNewPassowrd=_lastSetNewPassowrd;
@property(retain, nonatomic) NSString *lastSetOriginPassowrd; // @synthesize lastSetOriginPassowrd=_lastSetOriginPassowrd;
@property(retain, nonatomic) UITextField *field3; // @synthesize field3=_field3;
@property(retain, nonatomic) UITextField *field2; // @synthesize field2=_field2;
@property(retain, nonatomic) UITextField *field1; // @synthesize field1=_field1;
@property(retain, nonatomic) Contact *contact; // @synthesize contact=_contact;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)textFieldChanged:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)onSavePress;
- (void)onKeyBoardWillHide:(id)arg1;
- (void)onKeyBoardWillShow:(id)arg1;
- (void)onBackPress;
- (void)initComponent;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)ack_receiveRemoteMessage:(id)arg1;
- (void)receiveRemoteMessage:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

