//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Utilcamera)
- (_Bool)isValidateP2PVerifyCode1OrP2PVerifyCode2;
- (_Bool)isValidateNumber;
- (id)getMd5_32Bit_String;
@end

