//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableArray, NSString, UIActivityIndicatorView, UILabel, UIView;

@interface P2PDefenceAreaCell : UITableViewCell
{
    _Bool _isShowCustomView;
    _Bool _isProgressViewHidden;
    NSString *_leftLabelText;
    UILabel *_leftLabelView;
    UIView *_customView;
    id <DefenceAreaDelegate> _delegate;
    long long _group;
    NSMutableArray *_status;
    UIActivityIndicatorView *_progressView;
}

@property _Bool isProgressViewHidden; // @synthesize isProgressViewHidden=_isProgressViewHidden;
@property(retain, nonatomic) UIActivityIndicatorView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) NSMutableArray *status; // @synthesize status=_status;
@property long long group; // @synthesize group=_group;
@property(nonatomic) id <DefenceAreaDelegate> delegate; // @synthesize delegate=_delegate;
@property _Bool isShowCustomView; // @synthesize isShowCustomView=_isShowCustomView;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(retain, nonatomic) UILabel *leftLabelView; // @synthesize leftLabelView=_leftLabelView;
@property(retain, nonatomic) NSString *leftLabelText; // @synthesize leftLabelText=_leftLabelText;
- (void)setProgressViewHidden:(_Bool)arg1;
- (void)onButtonPress:(id)arg1;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

