//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "P2PPlaybackDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, OpenGLView, UIImageView, UILabel, UISlider, UIView;

@interface P2PPlayingbackController : UIViewController <UIGestureRecognizerDelegate, P2PPlaybackDelegate>
{
    _Bool _isReject;
    _Bool _isTouchSlider;
    _Bool _isFullScreen;
    _Bool _isShowControllerBar;
    OpenGLView *_remoteView;
    UIView *_controllerView;
    UIImageView *_pauseIconView;
    UILabel *_leftTimeLabel;
    UILabel *_rightTimeLabel;
    UISlider *_slider;
}

@property(retain, nonatomic) UISlider *slider; // @synthesize slider=_slider;
@property(retain, nonatomic) UILabel *rightTimeLabel; // @synthesize rightTimeLabel=_rightTimeLabel;
@property(retain, nonatomic) UILabel *leftTimeLabel; // @synthesize leftTimeLabel=_leftTimeLabel;
@property(retain, nonatomic) UIImageView *pauseIconView; // @synthesize pauseIconView=_pauseIconView;
@property(retain, nonatomic) UIView *controllerView; // @synthesize controllerView=_controllerView;
@property(nonatomic) _Bool isShowControllerBar; // @synthesize isShowControllerBar=_isShowControllerBar;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(nonatomic) _Bool isTouchSlider; // @synthesize isTouchSlider=_isTouchSlider;
@property(nonatomic) _Bool isReject; // @synthesize isReject=_isReject;
@property(retain, nonatomic) OpenGLView *remoteView; // @synthesize remoteView=_remoteView;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)prefersStatusBarHidden;
- (void)P2PPlaybackReject:(id)arg1;
- (void)onDoubleTap;
- (void)onSingleTap;
- (void)onButtonPress:(id)arg1;
- (void)onSliderEnd:(id)arg1;
- (void)onSlider:(id)arg1;
- (void)initComponent;
- (void)didReceiveMemoryWarning;
- (void)renderView;
- (void)viewDidLoad;
- (void)viewDidAppear:(_Bool)arg1;
- (void)receivePlayingCommand:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

