//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class RadioButton;

@protocol P2PRecordTimeCellDelegate <NSObject>
- (void)onRecordTimeCellRadioClick:(RadioButton *)arg1 index:(long long)arg2;
@end

