//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, OpenGLView, UIImageView, UIView;

@interface P2PVideoController : UIViewController <AVCaptureVideoDataOutputSampleBufferDelegate, UIGestureRecognizerDelegate>
{
    _Bool _isReject;
    _Bool _isFullScreen;
    _Bool _isShowControllerBar;
    _Bool _isVideoModeHD;
    _Bool _isScreenShotting;
    OpenGLView *_remoteView;
    UIView *_remoteMaskView;
    UIImageView *_localView;
    UIView *_controllerBar;
}

@property(retain, nonatomic) UIView *controllerBar; // @synthesize controllerBar=_controllerBar;
@property(nonatomic) _Bool isScreenShotting; // @synthesize isScreenShotting=_isScreenShotting;
@property(nonatomic) _Bool isVideoModeHD; // @synthesize isVideoModeHD=_isVideoModeHD;
@property(nonatomic) _Bool isShowControllerBar; // @synthesize isShowControllerBar=_isShowControllerBar;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(nonatomic) _Bool isReject; // @synthesize isReject=_isReject;
@property(retain, nonatomic) UIImageView *localView; // @synthesize localView=_localView;
@property(retain, nonatomic) UIView *remoteMaskView; // @synthesize remoteMaskView=_remoteMaskView;
@property(retain, nonatomic) OpenGLView *remoteView; // @synthesize remoteView=_remoteView;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)prefersStatusBarHidden;
- (void)onDoubleTap;
- (void)onSingleTap;
- (void)onControllerBtnPress:(id)arg1;
- (void)initComponent;
- (id)getControllerButton;
- (void)didReceiveMemoryWarning;
- (void)renderView;
- (void)receivePlayingCommand:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

