//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSString, RadioButton, UIActivityIndicatorView, UILabel, UIView;

@interface P2PVideoFormatSettingCell : UITableViewCell
{
    _Bool _isCustomViewHidden;
    _Bool _isLeftLabelHidden;
    _Bool _isRightLabelHidden;
    _Bool _isProgressViewHidden;
    NSString *_leftLabelText;
    NSString *_rightLabelText;
    UILabel *_leftLabelView;
    UILabel *_rightLabelView;
    UIView *_customView;
    RadioButton *_radio1;
    RadioButton *_radio2;
    UIActivityIndicatorView *_progressView;
    long long _selectedIndex;
}

@property long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property _Bool isProgressViewHidden; // @synthesize isProgressViewHidden=_isProgressViewHidden;
@property _Bool isRightLabelHidden; // @synthesize isRightLabelHidden=_isRightLabelHidden;
@property _Bool isLeftLabelHidden; // @synthesize isLeftLabelHidden=_isLeftLabelHidden;
@property _Bool isCustomViewHidden; // @synthesize isCustomViewHidden=_isCustomViewHidden;
@property(retain, nonatomic) UIActivityIndicatorView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) RadioButton *radio2; // @synthesize radio2=_radio2;
@property(retain, nonatomic) RadioButton *radio1; // @synthesize radio1=_radio1;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(retain, nonatomic) UILabel *rightLabelView; // @synthesize rightLabelView=_rightLabelView;
@property(retain, nonatomic) UILabel *leftLabelView; // @synthesize leftLabelView=_leftLabelView;
@property(retain, nonatomic) NSString *rightLabelText; // @synthesize rightLabelText=_rightLabelText;
@property(retain, nonatomic) NSString *leftLabelText; // @synthesize leftLabelText=_leftLabelText;
- (void)setCustomViewHidden:(_Bool)arg1;
- (void)setRightLabelHidden:(_Bool)arg1;
- (void)setLeftLabelHidden:(_Bool)arg1;
- (void)setProgressViewHidden:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

