//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "IDJPickerViewDelegate.h"

@class IDJPickerView, NSString;

@interface PlanTimePickView : UIView <IDJPickerViewDelegate>
{
    IDJPickerView *_picker;
    struct DeviceDate _date;
}

@property(nonatomic) struct DeviceDate date; // @synthesize date=_date;
@property(retain, nonatomic) IDJPickerView *picker; // @synthesize picker=_picker;
- (void).cxx_destruct;
- (void)selectedCellFromPlanTimePickView:(unsigned long long)arg1 minCell:(unsigned long long)arg2;
- (void)didSelectCell:(unsigned long long)arg1 inScroll:(unsigned long long)arg2;
- (unsigned long long)selectionPosition;
- (void)viewForCell:(unsigned long long)arg1 inScroll:(unsigned long long)arg2 reusingCell:(id)arg3;
- (unsigned long long)numberOfCellsInVisible;
- (id)scrollWidthProportion;
- (unsigned long long)numberOfCellsInScroll:(unsigned long long)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

