//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class GCDAsyncUdpSocket, NSString, UIButton, UIImageView, UIView;

@interface QRCodeSetWIFINextController : UIViewController
{
    _Bool _isWaiting;
    _Bool _isFinish;
    _Bool _isRun;
    _Bool _isShowSuccessAlert;
    _Bool _isPrepared;
    NSString *_uuidString;
    NSString *_wifiPwd;
    UIImageView *_qrcodeImageView;
    UIView *_smartKeyPromptView;
    UIButton *_promptButton;
    GCDAsyncUdpSocket *_socket;
}

@property _Bool isPrepared; // @synthesize isPrepared=_isPrepared;
@property(nonatomic) _Bool isShowSuccessAlert; // @synthesize isShowSuccessAlert=_isShowSuccessAlert;
@property _Bool isRun; // @synthesize isRun=_isRun;
@property(retain, nonatomic) GCDAsyncUdpSocket *socket; // @synthesize socket=_socket;
@property(nonatomic) _Bool isFinish; // @synthesize isFinish=_isFinish;
@property(nonatomic) _Bool isWaiting; // @synthesize isWaiting=_isWaiting;
@property(retain, nonatomic) UIButton *promptButton; // @synthesize promptButton=_promptButton;
@property(retain, nonatomic) UIView *smartKeyPromptView; // @synthesize smartKeyPromptView=_smartKeyPromptView;
@property(retain, nonatomic) UIImageView *qrcodeImageView; // @synthesize qrcodeImageView=_qrcodeImageView;
@property(retain, nonatomic) NSString *wifiPwd; // @synthesize wifiPwd=_wifiPwd;
@property(retain, nonatomic) NSString *uuidString; // @synthesize uuidString=_uuidString;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)udpSocket:(id)arg1 didReceiveData:(id)arg2 fromAddress:(id)arg3 withFilterContext:(id)arg4;
- (void)udpSocketDidClose:(id)arg1 withError:(id)arg2;
- (void)udpSocket:(id)arg1 didSendDataWithTag:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onBottomButtom1Press;
- (void)dismissView;
- (void)onHelpPress;
- (void)onBackPress;
- (void)initComponent;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (_Bool)prepareSocket;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

@end

