//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ConnectFailurePromptViewDelegate.h"
#import "QRGuardDelegate.h"
#import "tabviewDelegate.h"

@class ConnectFailurePromptView, NSString, QRCodeGuardFirst, QRCodeGuardSecond, UIImageView, UILabel, UITextField, UIView;

@interface QRCodeController : UIViewController <QRGuardDelegate, tabviewDelegate, ConnectFailurePromptViewDelegate>
{
    _Bool _bShowTip;
    int _tipIndex;
    QRCodeGuardFirst *_guardView00;
    QRCodeGuardSecond *_guardView01;
    UIView *_guardView02;
    UILabel *_textLable;
    UIImageView *_imageView;
    int _conectType;
    _Bool _bQuit;
    _Bool _bInitWif;
    _Bool _isFailForConnectingWIFI;
    _Bool _isSetWifiToAddDeviceByQR;
    UITextField *_ssidField;
    UITextField *_pwdField;
    UIImageView *_qrcodeImage;
    ConnectFailurePromptView *_connectFailurePromptView;
}

@property(nonatomic) _Bool isSetWifiToAddDeviceByQR; // @synthesize isSetWifiToAddDeviceByQR=_isSetWifiToAddDeviceByQR;
@property(retain, nonatomic) ConnectFailurePromptView *connectFailurePromptView; // @synthesize connectFailurePromptView=_connectFailurePromptView;
@property(nonatomic) _Bool isFailForConnectingWIFI; // @synthesize isFailForConnectingWIFI=_isFailForConnectingWIFI;
@property(retain, nonatomic) UIImageView *qrcodeImage; // @synthesize qrcodeImage=_qrcodeImage;
@property(retain, nonatomic) UITextField *pwdField; // @synthesize pwdField=_pwdField;
@property(retain, nonatomic) UITextField *ssidField; // @synthesize ssidField=_ssidField;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (_Bool)shouldAutorotate;
- (void)tabViewSetPage:(int)arg1;
- (void)setQRGuard:(_Bool)arg1;
- (void)onMakePress;
- (void)onBackPress;
- (void)onKeyBoardDown:(id)arg1;
- (void)connectFailurePromptViewSetWifiToAddDeviceByQR;
- (void)connectOnceAgainButtonClick;
- (void)initComponent;
- (id)fetchSSIDInfo;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)getWifiLoop;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

