//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface Recent : NSObject
{
    int _row;
    int _callType;
    int _callState;
    NSString *_contactId;
    NSString *_time;
}

@property(retain, nonatomic) NSString *time; // @synthesize time=_time;
@property(nonatomic) int callState; // @synthesize callState=_callState;
@property(nonatomic) int callType; // @synthesize callType=_callType;
@property(retain, nonatomic) NSString *contactId; // @synthesize contactId=_contactId;
@property(nonatomic) int row; // @synthesize row=_row;

@end

