//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RegisterResult : NSObject
{
    int _error_code;
    NSString *_contactId;
}

@property(nonatomic) int error_code; // @synthesize error_code=_error_code;
@property(retain, nonatomic) NSString *contactId; // @synthesize contactId=_contactId;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

