//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface SetACKPacket : NSObject
{
    NSMutableData *_packetData;
    struct {
        unsigned int _messageID_offset:8;
        unsigned int _messageID_len:8;
        unsigned int _flag_offset:8;
        unsigned int _flag_len:8;
        unsigned int _port_offset:8;
        unsigned int _port_len:8;
        unsigned int _accessKey_offset:8;
        unsigned int _accessKey_len:8;
    } _packetFlag;
}

- (void).cxx_destruct;
- (id)getPacketData;
- (int)getPacketSize;
- (id)initWithMessageID:(unsigned short)arg1 andAppListenPort:(unsigned short)arg2 andAccessKey:(unsigned int)arg3 andFlag:(unsigned char)arg4;
- (id)init;
- (void)initProtocolLayout;

@end

