//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableData;

@interface SetACKReturnPacket : NSObject
{
    NSMutableData *_packetData;
    CDStruct_022e7b76 _packetFlag;
}

+ (int)getPacketSize;
- (void).cxx_destruct;
- (int)getCode;
- (int)getMessageID;
- (id)getPacketData;
- (id)initWithData:(id)arg1;
- (void)initProtocolLayout;

@end

