//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SubKeyReturnHeader : NSObject
{
    BOOL _code;
    unsigned short _messageID;
    int _subKey;
}

@property(nonatomic) int subKey; // @synthesize subKey=_subKey;
@property(nonatomic) BOOL code; // @synthesize code=_code;
@property(nonatomic) unsigned short messageID; // @synthesize messageID=_messageID;
- (id)initWithData:(id)arg1;

@end

