//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface SyncRetHeaderPacket : NSObject
{
    BOOL _flag;
    NSData *_mac;
    NSString *_name;
    NSData *_dataPoint;
}

@property(retain, nonatomic) NSData *dataPoint; // @synthesize dataPoint=_dataPoint;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) BOOL flag; // @synthesize flag=_flag;
@property(retain, nonatomic) NSData *mac; // @synthesize mac=_mac;
- (void).cxx_destruct;
- (id)getDataPointArr;
- (id)initWithData:(id)arg1 withVersion:(unsigned char)arg2;

@end

