//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class IDJPickerView;

@interface TimezoneView : UIView
{
    IDJPickerView *_picker;
    long long _timezone;
    id <TimezoneViewDelegate> _delegate;
}

@property(nonatomic) id <TimezoneViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long timezone; // @synthesize timezone=_timezone;
@property(retain, nonatomic) IDJPickerView *picker; // @synthesize picker=_picker;
- (void).cxx_destruct;
- (void)selectedCellFromTimezoneView:(unsigned long long)arg1;
- (void)didSelectCell:(unsigned long long)arg1 inScroll:(unsigned long long)arg2;
- (unsigned long long)selectionPosition;
- (void)viewForCell:(unsigned long long)arg1 inScroll:(unsigned long long)arg2 reusingCell:(id)arg3;
- (unsigned long long)numberOfCellsInVisible;
- (id)scrollWidthProportion;
- (unsigned long long)numberOfCellsInScroll:(unsigned long long)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

