//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Udpproxy2 : NSObject
{
    int sockfd;
    int sockMCast;
    struct sockaddr_in localAdd;
    struct sockaddr_in clientAdd;
    struct sockaddr_in remoteAdd;
    struct sockaddr_in findAdd;
    unsigned int remote_addr_len;
    unsigned int find_addr_len;
    int num;
    char recvmsg[100];
    char sendmsg[100];
}

+ (id)shareInstence;
- (id)localBroadCastIP;
- (void)close;
- (id)recv;
- (void)sendSmartLinkFind;
- (void)sendMCast:(char *)arg1 withAddr:(char *)arg2 andSN:(int)arg3;
- (void)send:(char *)arg1;
- (void)CreateBindSocket;

@end

