//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexPath, UIPopoverListView, UITableViewCell;

@protocol UIPopoverListViewDataSource <NSObject>
- (long long)popoverListView:(UIPopoverListView *)arg1 numberOfRowsInSection:(long long)arg2;
- (UITableViewCell *)popoverListView:(UIPopoverListView *)arg1 cellForIndexPath:(NSIndexPath *)arg2;
@end

