//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@class SVPullToRefresh;

@interface UIScrollView (SVPullToRefresh)
@property(retain, nonatomic) SVPullToRefresh *pullToRefreshView; // @dynamic pullToRefreshView;
- (void)addPullToRefreshWithActionHandler:(CDUnknownBlockType)arg1;
@end

