//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableView.h"

@interface UITableView (DelegateBlocks)
- (void)onWillSelectRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onWillDisplayCell:(CDUnknownBlockType)arg1;
- (void)onWillDeselectRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onWillBeginEditingRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onViewForHeaderInSection:(CDUnknownBlockType)arg1;
- (void)onViewForFooterInSection:(CDUnknownBlockType)arg1;
- (void)onTitleForDeleteConfirmationButtonForRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onTargetIndexPathForMoveFromRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onShouldIndentWhileEditingRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onHeightForRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onHeightForHeaderInSection:(CDUnknownBlockType)arg1;
- (void)onHeightForFooterInSection:(CDUnknownBlockType)arg1;
- (void)onEditingStyleForRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onDidSelectRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onDidEndEditingRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onDidDeselectRowAtIndexPath:(CDUnknownBlockType)arg1;
- (void)onAccessoryButtonTappedForRowWithIndexPath:(CDUnknownBlockType)arg1;
- (id)useBlocksForDelegate;
@end

