//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UITableViewDataSource.h"

@class NSString;

@interface UITableViewDataSourceBlocks : NSObject <UITableViewDataSource>
{
    CDUnknownBlockType _numberOfSectionsInTableViewBlock;
    CDUnknownBlockType _sectionIndexTitlesForTableViewBlock;
    CDUnknownBlockType _canEditRowAtIndexPathBlock;
    CDUnknownBlockType _canMoveRowAtIndexPathBlock;
    CDUnknownBlockType _cellForRowAtIndexPathBlock;
    CDUnknownBlockType _commitEditingStyleBlock;
    CDUnknownBlockType _moveRowAtIndexPathBlock;
    CDUnknownBlockType _numberOfRowsInSectionBlock;
    CDUnknownBlockType _sectionForSectionIndexTitleBlock;
    CDUnknownBlockType _titleForFooterInSectionBlock;
    CDUnknownBlockType _titleForHeaderInSectionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType titleForHeaderInSectionBlock; // @synthesize titleForHeaderInSectionBlock=_titleForHeaderInSectionBlock;
@property(copy, nonatomic) CDUnknownBlockType titleForFooterInSectionBlock; // @synthesize titleForFooterInSectionBlock=_titleForFooterInSectionBlock;
@property(copy, nonatomic) CDUnknownBlockType sectionForSectionIndexTitleBlock; // @synthesize sectionForSectionIndexTitleBlock=_sectionForSectionIndexTitleBlock;
@property(copy, nonatomic) CDUnknownBlockType numberOfRowsInSectionBlock; // @synthesize numberOfRowsInSectionBlock=_numberOfRowsInSectionBlock;
@property(copy, nonatomic) CDUnknownBlockType moveRowAtIndexPathBlock; // @synthesize moveRowAtIndexPathBlock=_moveRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType commitEditingStyleBlock; // @synthesize commitEditingStyleBlock=_commitEditingStyleBlock;
@property(copy, nonatomic) CDUnknownBlockType cellForRowAtIndexPathBlock; // @synthesize cellForRowAtIndexPathBlock=_cellForRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType canMoveRowAtIndexPathBlock; // @synthesize canMoveRowAtIndexPathBlock=_canMoveRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType canEditRowAtIndexPathBlock; // @synthesize canEditRowAtIndexPathBlock=_canEditRowAtIndexPathBlock;
@property(copy, nonatomic) CDUnknownBlockType sectionIndexTitlesForTableViewBlock; // @synthesize sectionIndexTitlesForTableViewBlock=_sectionIndexTitlesForTableViewBlock;
@property(copy, nonatomic) CDUnknownBlockType numberOfSectionsInTableViewBlock; // @synthesize numberOfSectionsInTableViewBlock=_numberOfSectionsInTableViewBlock;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (long long)numberOfSectionsInTableView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

