//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class AsyncUdpSocket, EASYLINK, NSString, NSThread, NSTimer, NSUserDefaults, Reachability, UIImageView, UILabel, UITextFieldEx, UIView;

@interface Wifi_Setting : UIViewController <UITextFieldDelegate>
{
    NSTimer *_timer;
    EASYLINK *_easylink_config;
    Reachability *_wifiReachability;
    NSUserDefaults *myDefault;
    AsyncUdpSocket *_udpSocket;
    UITextFieldEx *_textFieldPassword;
    UITextFieldEx *_textFieldSSID;
    NSThread *_waitForAckThread;
    UIView *_ViewDJS;
    UILabel *_lblTime;
    UIImageView *_gridView;
}

@property(nonatomic) __weak UIImageView *gridView; // @synthesize gridView=_gridView;
@property(nonatomic) __weak UILabel *lblTime; // @synthesize lblTime=_lblTime;
@property(retain, nonatomic) UIView *ViewDJS; // @synthesize ViewDJS=_ViewDJS;
@property(retain, nonatomic) NSThread *waitForAckThread; // @synthesize waitForAckThread=_waitForAckThread;
@property(nonatomic) __weak UITextFieldEx *textFieldSSID; // @synthesize textFieldSSID=_textFieldSSID;
@property(nonatomic) __weak UITextFieldEx *textFieldPassword; // @synthesize textFieldPassword=_textFieldPassword;
@property(retain, nonatomic) AsyncUdpSocket *udpSocket; // @synthesize udpSocket=_udpSocket;
- (void).cxx_destruct;
- (void)onEasyLinkSoftApStageChanged:(int)arg1;
- (void)onDisconnectFromFTC:(id)arg1;
- (void)onFoundByFTC:(id)arg1 withConfiguration:(id)arg2;
- (void)onUdpSocketDidClose:(id)arg1;
- (void)onUdpSocket:(id)arg1 didSendDataWithTag:(long long)arg2;
- (void)onUdpSocket:(id)arg1 didNotSendDataWithTag:(long long)arg2 dueToError:(id)arg3;
- (void)onUdpSocket:(id)arg1 didNotReceiveDataWithTag:(long long)arg2 dueToError:(id)arg3;
- (_Bool)onUdpSocket:(id)arg1 didReceiveData:(id)arg2 withTag:(long long)arg3 fromHost:(id)arg4 port:(unsigned short)arg5;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (int)UDPBackdispose:(id)arg1;
- (void)conect:(id)arg1;
- (void)easyLink:(id)arg1;
- (void)sendMassage:(id)arg1;
- (void)openUDPServer;
- (void)UDPBroadcastBegin;
- (void)startTransmitting:(int)arg1;
- (void)stopAction;
- (void)sendAction;
- (void)didReceiveMemoryWarning;
- (void)btnGoTouchUpInside:(id)arg1;
- (void)btnDJSCancelTouchUpInside:(id)arg1;
- (void)updateInterfaceWithReachability:(id)arg1;
- (void)reachabilityChanged:(id)arg1;
- (void)timerOutEasy:(id)arg1;
- (void)hidDJS;
- (void)showDJS;
- (void)initEasyLink;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

