//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface XGSetting : NSObject
{
    NSString *Channel;
    NSString *GameServer;
}

+ (id)getInstance;
@property(retain, nonatomic) NSString *GameServer; // @synthesize GameServer;
@property(retain, nonatomic) NSString *Channel; // @synthesize Channel;
- (_Bool)isEnableDebug;
- (void)enableDebug:(_Bool)arg1;
- (id)init;

@end

