//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface XGTpnsUnregisterDelegate : NSObject
{
    CDUnknownBlockType _unRegisterSuccessCallback;
    CDUnknownBlockType _unRegisterErrorCallback;
}

@property(copy, nonatomic) CDUnknownBlockType unRegisterErrorCallback; // @synthesize unRegisterErrorCallback=_unRegisterErrorCallback;
@property(copy, nonatomic) CDUnknownBlockType unRegisterSuccessCallback; // @synthesize unRegisterSuccessCallback=_unRegisterSuccessCallback;
- (void)sendSecond:(id)arg1;
- (void)socket:(id)arg1 didReadData:(id)arg2 withTag:(long long)arg3;
- (void)dealloc;
- (void)socketDidDisconnect:(id)arg1 withError:(id)arg2;
- (void)socket:(id)arg1 didConnectToHost:(id)arg2 port:(unsigned short)arg3;

@end

