//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class XGAsyncSocket, XGTpnsRegisterDelegate;

@interface XGTpnsRegister : NSObject
{
    XGAsyncSocket *_socket;
    CDUnknownBlockType _registerSuccessCallback;
    CDUnknownBlockType _registerErrorCallback;
    XGTpnsRegisterDelegate *_delegate;
}

+ (void)load;
@property(retain, nonatomic) XGTpnsRegisterDelegate *delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) CDUnknownBlockType registerErrorCallback; // @synthesize registerErrorCallback=_registerErrorCallback;
@property(copy, nonatomic) CDUnknownBlockType registerSuccessCallback; // @synthesize registerSuccessCallback=_registerSuccessCallback;
@property(retain, nonatomic) XGAsyncSocket *socket; // @synthesize socket=_socket;
- (void)dealloc;
- (void)send:(id)arg1 appID:(unsigned int)arg2 appkey:(id)arg3 account:(id)arg4;
- (_Bool)connect;
- (id)initWithSuccessCallback:(CDUnknownBlockType)arg1 errorCallback:(CDUnknownBlockType)arg2;

@end

