//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DeviceEntity, NSArray, NSData, NSNumber;

@protocol XlinkExportObjectDelegate <NSObject>

@optional
- (void)onSetCloudDataPoint:(DeviceEntity *)arg1 withResult:(int)arg2 withMsgID:(unsigned short)arg3;
- (void)onSetLocalDataPoint:(DeviceEntity *)arg1 withResult:(int)arg2 withMsgID:(unsigned short)arg3;
- (void)onNotifyWithFlag:(unsigned char)arg1 withMessageData:(NSData *)arg2 fromID:(int)arg3 messageID:(int)arg4;
- (void)onSubscription:(DeviceEntity *)arg1 withResult:(int)arg2 withMessageID:(int)arg3;
- (void)onGotSubKeyWithDevice:(DeviceEntity *)arg1 withSubKey:(NSNumber *)arg2;
- (void)onHandShakeWithDevice:(DeviceEntity *)arg1 withResult:(int)arg2;
- (void)onDeviceStatusChanged:(DeviceEntity *)arg1;
- (void)onConnectDevice:(DeviceEntity *)arg1 andResult:(int)arg2 andTaskID:(int)arg3;
- (void)onNetStateChanged:(int)arg1;
- (void)onCloudDataPoint2Update:(DeviceEntity *)arg1 withDataPoints:(NSArray *)arg2;
- (void)onLocalDataPoint2Update:(DeviceEntity *)arg1 withDataPoints:(NSArray *)arg2;
- (void)onDataPointUpdata:(DeviceEntity *)arg1 withIndex:(int)arg2 withDataBuff:(NSData *)arg3 withChannel:(int)arg4;
- (void)onSetDeviceAccessKey:(DeviceEntity *)arg1 withResult:(unsigned char)arg2 withMessageID:(unsigned short)arg3;
- (void)onDeviceProbe:(DeviceEntity *)arg1 withResult:(int)arg2 withMessageID:(int)arg3;
- (void)onRecvPipeSyncData:(DeviceEntity *)arg1 withPayload:(NSData *)arg2;
- (void)onRecvPipeData:(DeviceEntity *)arg1 withMsgID:(unsigned short)arg2 withPayload:(NSData *)arg3;
- (void)onSendPipeData:(DeviceEntity *)arg1 withResult:(int)arg2 withMessageID:(int)arg3;
- (void)onSetDeviceAuthorizeCode:(DeviceEntity *)arg1 withResult:(int)arg2 withMessageID:(int)arg3;
- (void)onLogin:(int)arg1;
- (void)onRecvLocalPipeData:(DeviceEntity *)arg1 withPayload:(NSData *)arg2;
- (void)onSendLocalPipeData:(DeviceEntity *)arg1 withResult:(int)arg2 withMessageID:(int)arg3;
- (void)onSetLocalDeviceAuthorizeCode:(DeviceEntity *)arg1 withResult:(int)arg2 withMessageID:(int)arg3;
- (void)onGotDeviceByScan:(DeviceEntity *)arg1;
- (void)onStart;
@end

