//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface YAudioStreamPlayer : NSObject
{
    struct OpaqueAudioComponentInstance *_audioUnit;
    struct AudioBufferList *_m_inBufferList;
    double recordSampleRate;
    struct AudioStreamBasicDescription audioFormat;
    _Bool _isPlay;
}

+ (id)sharedDefault;
@property(nonatomic) _Bool isPlay; // @synthesize isPlay=_isPlay;
- (void)checkSpeaker;
- (_Bool)isHeadphone;
- (void)stop;
- (_Bool)start;
- (_Bool)stopAudio;
- (_Bool)startAudio;
- (_Bool)uninitAudio;
- (_Bool)initAudio;
- (_Bool)uninitSession;
- (_Bool)initSession;
- (void)playWIFI:(id)arg1 wifiPassword:(id)arg2 devicePassword:(id)arg3;
- (void)playCmd:(long long)arg1;

@end

