//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString;

@interface YButton : UIButton
{
    NSString *_image;
    NSString *_image_p;
    id <YButtonDelegate> _delegate;
}

@property id <YButtonDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *image_p; // @synthesize image_p=_image_p;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
- (void)normalButton:(id)arg1;
- (void)lightButton:(id)arg1;
- (void)onButtonPress:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

