//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface YProgressView : UIView
{
    _Bool _isStartAnim;
    double _angle;
    UIImageView *_backgroundView;
}

@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(nonatomic) _Bool isStartAnim; // @synthesize isStartAnim=_isStartAnim;
@property(nonatomic) double angle; // @synthesize angle=_angle;
- (void)stop;
- (void)start;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

