//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CategoryMedia, NSData, NSString, UIImage;

@interface AbstractMedia : NSObject
{
    NSString *_key;
    NSString *_name;
    CategoryMedia *_fatherCategory;
    BOOL _isDir;
    NSString *_alassetUrl;
    NSData *thumbnailData;
    UIImage *thumbnailImage;
    NSString *_mediaType;
    NSString *_assetId;
}

@property(retain, nonatomic) NSString *assetId; // @synthesize assetId=_assetId;
@property(retain, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(retain, nonatomic) UIImage *thumbnailImage; // @synthesize thumbnailImage;
@property(retain, nonatomic) NSData *thumbnailData; // @synthesize thumbnailData;
@property(retain, nonatomic) NSString *alassetUrl; // @synthesize alassetUrl=_alassetUrl;
@property(nonatomic) BOOL isDir; // @synthesize isDir=_isDir;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) CategoryMedia *fatherCategory; // @synthesize fatherCategory=_fatherCategory;
- (id)getName;
- (id)getFullName;
- (id)getFatherKey;
- (id)initWithKey:(id)arg1 withName:(id)arg2 withUrl:(id)arg3 withMediaType:(id)arg4;

@end

