//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AQGridView, AQGridViewCell;

@protocol AQGridViewDataSource <NSObject>
- (AQGridViewCell *)gridView:(AQGridView *)arg1 cellForItemAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfItemsInGridView:(AQGridView *)arg1;

@optional
- (struct CGSize)portraitGridCellSizeForGridView:(AQGridView *)arg1;
@end

