//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"
#import "NSMutableCopying.h"

@class AQGridView;

@interface AQGridViewData : NSObject <NSCopying, NSMutableCopying>
{
    AQGridView *_gridView;
    struct CGSize _boundsSize;
    int _layoutDirection;
    struct CGSize _desiredCellSize;
    struct CGSize _actualCellSize;
    float _topPadding;
    float _bottomPadding;
    float _leftPadding;
    float _rightPadding;
    unsigned int _numberOfItems;
    unsigned int _reorderedIndex;
}

@property(nonatomic) int layoutDirection; // @synthesize layoutDirection=_layoutDirection;
@property(nonatomic) float rightPadding; // @synthesize rightPadding=_rightPadding;
@property(nonatomic) float leftPadding; // @synthesize leftPadding=_leftPadding;
@property(nonatomic) float bottomPadding; // @synthesize bottomPadding=_bottomPadding;
@property(nonatomic) float topPadding; // @synthesize topPadding=_topPadding;
@property(nonatomic) unsigned int numberOfItems; // @synthesize numberOfItems=_numberOfItems;
@property(nonatomic) unsigned int reorderedIndex; // @synthesize reorderedIndex=_reorderedIndex;
- (id)indicesOfCellsInRect:(struct CGRect)arg1;
- (struct CGRect)cellRectAtIndex:(unsigned int)arg1;
- (unsigned int)numberOfItemsPerRow;
- (struct CGSize)sizeForEntireGrid;
- (struct CGRect)rectForEntireGrid;
- (struct CGSize)cellSize;
- (void)setDesiredCellSize:(struct CGSize)arg1;
- (struct CGRect)cellRectForPoint:(struct CGPoint)arg1;
- (BOOL)pointIsInLastRow:(struct CGPoint)arg1;
- (unsigned int)itemIndexForPoint:(struct CGPoint)arg1;
- (void)gridViewDidChangeBoundsSize:(struct CGSize)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithGridView:(id)arg1;
- (void)fixDesiredCellSizeForWidth:(float)arg1;

@end

