//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class BaseAudioPlayer;

@protocol AudioPlayerDelegate
- (void)onFinished:(BaseAudioPlayer *)arg1;
- (void)onPaused:(BaseAudioPlayer *)arg1;
- (void)onPlayError:(BaseAudioPlayer *)arg1 errorCode:(int)arg2;
- (void)onPlaying:(BaseAudioPlayer *)arg1;
- (void)onProgress:(BaseAudioPlayer *)arg1 progress:(float)arg2;
- (void)onBuffering:(BaseAudioPlayer *)arg1;
@end

