//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface CandidateWord : NSObject
{
    NSString *wordString;
    int score;
}

@property int score; // @synthesize score;
@property(retain) NSString *wordString; // @synthesize wordString;

@end

