//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CJSONSerializer : NSObject
{
}

+ (id)serializer;
- (id)serializeDictionary:(id)arg1;
- (id)serializeArray:(id)arg1;
- (id)serializeString:(id)arg1;
- (id)serializeNumber:(id)arg1;
- (id)serializeNull:(id)arg1;
- (id)serializeObject:(id)arg1;

@end

