//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor, UILabel;

@interface CustomAlert : UIView
{
    UILabel *messageLabel;
    UIView *viewToShowIn;
    UIColor *viewColor;
    UIColor *borderColor;
    UIColor *messageColor;
    UIColor *confirmTextColor;
    UIColor *cancelTextColor;
}

- (void)dealloc;
- (void)dismissAnimated;
- (void)show;
- (id)initWithMessage:(id)arg1 inView:(id)arg2;

@end

