//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCopying.h"

@interface CXMLNode : NSObject <NSCopying>
{
    struct _xmlNode *_node;
    BOOL _freeNodeOnRelease;
}

+ (id)nodeWithLibXMLNode:(struct _xmlNode *)arg1 freeOnDealloc:(BOOL)arg2;
+ (id)processingInstructionWithName:(id)arg1 stringValue:(id)arg2;
+ (id)namespaceWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1 stringValue:(id)arg2;
+ (id)elementWithName:(id)arg1 URI:(id)arg2;
+ (id)elementWithName:(id)arg1;
+ (id)documentWithRootElement:(id)arg1;
+ (id)document;
@property(readonly, nonatomic) struct _xmlNode *node; // @dynamic node;
- (id)numberValueForXPath:(id)arg1;
- (id)stringValueForXPath:(id)arg1;
- (id)initWithLibXMLNode:(struct _xmlNode *)arg1 freeOnDealloc:(BOOL)arg2;
- (id)nodesForXPath:(id)arg1 error:(id *)arg2;
- (id)XMLStringWithOptions:(unsigned int)arg1;
- (id)XMLString;
- (id)description;
- (id)URI;
- (id)prefix;
- (id)localName;
- (id)nextSibling;
- (id)previousSibling;
- (id)childAtIndex:(unsigned int)arg1;
- (id)children;
- (unsigned int)childCount;
- (id)parent;
- (id)rootDocument;
- (unsigned int)level;
- (unsigned int)index;
- (id)stringValue;
- (id)name;
- (int)kind;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (void)setStringValue:(id)arg1;
- (id)nodeForXPath:(id)arg1 error:(id *)arg2;
- (id)nodesForXPath:(id)arg1 namespaceMappings:(id)arg2 error:(id *)arg3;
- (id)numberValueForXPath:(id)arg1;
- (id)stringValueForXPath:(id)arg1;

@end

