//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabase, NSString;

@interface DBConnectionManager : NSObject
{
    NSString *writableDBPath;
    FMDatabase *db;
}

+ (id)sharedInstance;
+ (id)getInstance;
@property(retain, nonatomic) FMDatabase *db; // @synthesize db;
- (BOOL)databaseCheckAndCopy;
- (id)getDB;
- (id)init;

@end

