//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class DownLoadAdvertiseEngine, IFlyAdvertiseData;

@protocol DownLoadAdvertiseEngineDelegate
- (void)versionNotChange:(DownLoadAdvertiseEngine *)arg1;
- (void)downLoadFail:(DownLoadAdvertiseEngine *)arg1;
- (void)downLoadSuccess:(DownLoadAdvertiseEngine *)arg1 theData:(IFlyAdvertiseData *)arg2;
@end

