//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IFlyAnimationImage, NSMutableArray, NSString;

@interface IFlyAdvertiseData : NSObject
{
    NSString *_version;
    struct NSMutableArray *_adLinksArray;
    struct NSMutableArray *_lsTextsArray;
    IFlyAnimationImage *_animationImage;
}

@property(retain, nonatomic) IFlyAnimationImage *animationImage; // @synthesize animationImage=_animationImage;
@property(retain, nonatomic) NSMutableArray *lsTextsArray; // @synthesize lsTextsArray=_lsTextsArray;
@property(retain, nonatomic) NSMutableArray *adLinksArray; // @synthesize adLinksArray=_adLinksArray;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;

@end

