//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ISRAudioPlayerDelegate.h"
#import "ISRMSCEngineDelegate.h"
#import "ISRRecorderDelegate.h"

@class ISRAudioPlayer, ISRLogManager, ISRMSCEngine, ISRQueue, ISRRecorder, NSMutableArray, NSString, NSTimer, iFlyReachability;

@interface IFlyRecognizerImp : NSObject <ISRRecorderDelegate, ISRMSCEngineDelegate, ISRAudioPlayerDelegate>
{
    ISRRecorder *_recorder;
    ISRMSCEngine *_mscEngine;
    ISRAudioPlayer *_isrAudioPlayer;
    NSMutableArray *_recorderDataArray;
    ISRLogManager *_logManager;
    int _vrCurrentState;
    int _endCode;
    NSString *_engineType;
    NSString *_engineParam;
    NSString *_grammarID;
    int _sampleRate;
    ISRQueue *_dataQueue;
    NSString *_appID;
    NSTimer *_recordMonitorTimer;
    id <IFlyRecognizerImpDelegate> _delegate;
    iFlyReachability *reachability;
    int remoteHostStatus;
}

@property id <IFlyRecognizerImpDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)reSpeak;
- (void)reGetData;
- (void)stopPrevRecord;
- (void)resumePrevRecord;
- (void)pausePrevRecord;
- (void)playPrevRecord;
- (int)getDownflow;
- (int)getUpflow;
- (float)getPower;
- (void)stop;
- (void)cancel;
- (BOOL)start;
- (void)setSampleRate:(int)arg1;
- (void)setEngine:(id)arg1 theEngineParam:(id)arg2 theGrammarID:(id)arg3;
- (id)initWithParam:(id)arg1;
- (void)onPlayError:(id)arg1 error:(id)arg2;
- (void)onProgress:(id)arg1 progress:(int)arg2;
- (void)onFinished:(id)arg1;
- (void)onStopped:(id)arg1;
- (void)onResumed:(id)arg1;
- (void)onPaused:(id)arg1;
- (void)onStarted:(id)arg1;
- (void)onUploadSuccess:(id)arg1;
- (void)onUploadFail:(id)arg1 theEndcode:(int)arg2;
- (void)onResult:(id)arg1 theParams:(id)arg2;
- (void)onISRComplete:(id)arg1;
- (void)onCancel:(id)arg1 theISREndCode:(int)arg2;
- (void)onStop:(id)arg1;
- (void)onIFlyGetPower:(float)arg1;
- (void)onReturnBuffer:(char *)arg1 bufferSize:(int)arg2;
- (void)setVRState:(int)arg1;
- (void)errorHander:(int)arg1;
- (void)endRecordStore;
- (void)startRecordStore;
- (void)initMSCEngineThread;
- (void)submitDataThread;
- (void)startISR;
- (void)reGetDataThread;
- (BOOL)writeData;
- (void)stopRecord;
- (void)stopRecordTimeMonitor;
- (void)recordTimeMonitorEnd;
- (void)startRecordTimeMonitor;
- (BOOL)isConnectedToNetwork;
- (void)removeNetworkChangeNotifier;
- (void)addNetworkChangeNotifier;
- (void)handleNetworkChange:(id)arg1;

@end

