//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ISRBaseView.h"

#import "IFlyISRStateDelegate.h"
#import "IFlyRecognizerDelegate.h"

@class AdvertiseControl, AdvertiseManager, IFlyAdvertiseData, IFlyRecognizeControlAudioPauseState, IFlyRecognizeControlAudioPlayState, IFlyRecognizeControlBaseState, IFlyRecognizeControlCancelState, IFlyRecognizeControlFinishMoreState, IFlyRecognizeControlFinishState, IFlyRecognizeControlHelpState, IFlyRecognizeControlRecordingState, IFlyRecognizeControlUploadingState, IFlyRecognizeControlWaittingResultState, IFlyRecognizer, NSDictionary, NSString, RegulateAdversiteControl, UIImage;

@interface IFlyRecognizeControlImp : ISRBaseView <IFlyRecognizerDelegate, IFlyISRStateDelegate>
{
    UIImage *_backgroundImage;
    IFlyRecognizer *_iFlyRecognizer;
    IFlyRecognizeControlBaseState *_curState;
    IFlyRecognizeControlRecordingState *_recordingState;
    IFlyRecognizeControlWaittingResultState *_waitingState;
    IFlyRecognizeControlFinishMoreState *_finishMoreState;
    IFlyRecognizeControlCancelState *_cancelState;
    IFlyRecognizeControlUploadingState *_uploadState;
    IFlyRecognizeControlFinishState *_finishState;
    IFlyRecognizeControlAudioPlayState *_audioPlayState;
    IFlyRecognizeControlAudioPauseState *_audioPauseState;
    IFlyRecognizeControlHelpState *_helpState;
    AdvertiseControl *_advertiseControl;
    RegulateAdversiteControl *_regulateAdversiteControl;
    IFlyAdvertiseData *_advertiseData;
    NSDictionary *_description;
    NSString *_engineType;
    int _error;
    NSString *_initParam;
    BOOL _isShowUI;
    AdvertiseManager *_advertiseManager;
    id <IFlyRecognizeControlImpDelegate> _delegate;
}

@property id <IFlyRecognizeControlImpDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)onFinish:(id)arg1;
- (void)onIFlyRecognizerProgress:(float)arg1;
- (void)onIFlyRecognizerISREndState:(int)arg1;
- (void)onIFlyRecognizerState:(int)arg1;
- (void)onIFlyRecognizerResult:(id)arg1;
- (int)getDownflow;
- (int)getUpflow;
- (void)cancel;
- (void)rePlay;
- (BOOL)start;
- (void)setSampleRate:(int)arg1;
- (void)setEngine:(id)arg1 theEngineParam:(id)arg2 theGrammarID:(id)arg3;
- (id)initWithFrame:(struct CGRect)arg1 theInitParam:(id)arg2;
- (void)setAdvertise:(id)arg1;
- (void)initAdvertise;
- (void)finish;
- (void)setShowUI:(BOOL)arg1;
- (void)selfShow;
- (void)selfHiddden;
- (void)setState:(id)arg1;

@end

