//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TTSBaseView.h"

#import "BaseStateViewDelegate.h"
#import "IFlySynthesizerDelegate.h"

@class AdvertiseControl, AudioPauseStataView, AudioPlayStataView, BaseStateView, CancelStateView, FinishStateView, IFlySynthesizer, SynthesizingStateView, UIImage;

@interface IFlySynthesizerControlImp : TTSBaseView <BaseStateViewDelegate, IFlySynthesizerDelegate>
{
    AdvertiseControl *_advertiseControl;
    UIImage *_backgroundImage;
    IFlySynthesizer *_iFlySynthesizer;
    BaseStateView *_currentStateView;
    SynthesizingStateView *_synthesizingStateView;
    AudioPlayStataView *_audioPlayStataView;
    AudioPauseStataView *_audioPauseStateView;
    CancelStateView *_cancelStateView;
    FinishStateView *_finishStateView;
    int _bufferProgress;
    int _playProgress;
    BOOL _isShowUI;
    int _error;
    id <IFlySynthesizerControlImpDelegate> _delegate;
}

@property id <IFlySynthesizerControlImpDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)onIFlySynthesizerPlayProgress:(float)arg1;
- (void)onIFlySynthesizerBufferProgress:(float)arg1;
- (void)onFinish:(id)arg1;
- (void)onIFlySynthesizerTTSEndState:(int)arg1;
- (void)onIFlySynthesizerState:(int)arg1;
- (void)onEnd;
- (void)finish;
- (void)selfShow;
- (void)selfHiddden;
- (void)setState:(id)arg1;
- (int)getDownflow;
- (int)getUpflow;
- (void)replay;
- (void)resume;
- (void)pause;
- (void)cancel;
- (BOOL)start;
- (void)setVolume:(unsigned int)arg1;
- (void)setSpeed:(unsigned int)arg1;
- (void)setVoiceName:(id)arg1;
- (void)setBackgroundSound:(id)arg1;
- (void)setShowUI:(BOOL)arg1;
- (void)setSampleRate:(int)arg1;
- (void)setText:(id)arg1 theParams:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 theInitParam:(id)arg2;
- (void)initAdvertise;

@end

