//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AudioPlayerDelegate.h"
#import "TTSEngineDelegate.h"

@class AudioPlayerManager, NSMutableArray, NSString, TTSEngine, TTSLogManager, iFlyReachability;

@interface IFlySynthesizerImp : NSObject <AudioPlayerDelegate, TTSEngineDelegate>
{
    AudioPlayerManager *_audioPlayer;
    TTSEngine *_ttsEngine;
    int _ttsCurrentState;
    int _endCode;
    NSString *_text;
    TTSLogManager *_logManager;
    NSString *_appID;
    float _bufferProgress;
    float _playProgress;
    int _playingBufferProgress;
    int _willPlayBufferProgress;
    NSMutableArray *_willPlayBufferData1;
    NSMutableArray *_willPlayBufferData2;
    BOOL _isBufferData1;
    id <IFlySynthesizerImpDelegate> _delegate;
    int _synthesizeSpeed;
    iFlyReachability *reachability;
    int remoteHostStatus;
}

@property id <IFlySynthesizerImpDelegate> delegate; // @synthesize delegate=_delegate;
- (void)dealloc;
- (int)getDownflow;
- (int)getUpflow;
- (void)setVolume:(unsigned int)arg1;
- (void)setSpeed:(unsigned int)arg1;
- (void)setVoiceName:(id)arg1;
- (void)setBackgroundSound:(id)arg1;
- (void)setSampleRate:(int)arg1;
- (void)setText:(id)arg1 theParams:(id)arg2;
- (void)cancel;
- (BOOL)isAudioPlayNeedToStop;
- (BOOL)isAudioPlayFinish;
- (BOOL)start;
- (void)stop;
- (void)resume;
- (void)pause;
- (void)rePlay;
- (id)initWithParam:(id)arg1;
- (void)onPlayError:(id)arg1 errorCode:(int)arg2;
- (void)onFinished:(id)arg1;
- (void)onStopped:(id)arg1;
- (void)onPaused:(id)arg1;
- (void)onPlaying:(id)arg1;
- (void)onProgress:(id)arg1 progress:(float)arg2;
- (void)onBuffering:(id)arg1;
- (void)onSynthesizerProgress:(id)arg1 progress:(float)arg2;
- (void)submitDataToAudioPlay;
- (void)onAudioBuffer:(const void *)arg1 withValue:(unsigned int)arg2;
- (void)storeAudioBuffer:(const void *)arg1 withValue:(unsigned int)arg2;
- (void)onTTSComplete:(id)arg1;
- (void)onTTSEngineError:(id)arg1 errorCode:(int)arg2;
- (void)errorHander:(int)arg1;
- (void)setTTSState:(int)arg1;
- (void)startTTS;
- (void)initTTSEngineThread;
- (BOOL)isConnectedToNetwork;
- (void)addNetworkChangeNotifier;
- (void)handleNetworkChange:(id)arg1;

@end

