//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class ISRAudioPlayer, NSString;

@protocol ISRAudioPlayerDelegate
- (void)onPlayError:(ISRAudioPlayer *)arg1 error:(NSString *)arg2;
- (void)onProgress:(ISRAudioPlayer *)arg1 progress:(int)arg2;
- (void)onFinished:(ISRAudioPlayer *)arg1;
- (void)onStopped:(ISRAudioPlayer *)arg1;
- (void)onResumed:(ISRAudioPlayer *)arg1;
- (void)onPaused:(ISRAudioPlayer *)arg1;
- (void)onStarted:(ISRAudioPlayer *)arg1;
@end

