//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LogManager.h"

@class NSArray, NSDate, NSMutableArray;

@interface ISRLogManager : LogManager
{
    NSDate *_startRecognizeDate;
    NSDate *_startRecordDate;
    NSDate *_endRecordDate;
    NSDate *_sessionEndDate;
    NSMutableArray *_resultArray;
    NSMutableArray *_allArray;
    NSArray *_pcmDataArray;
}

- (void)writeLogFileOnMainThread;
- (void)writeLogFile;
- (void)setPcmDataArray:(id)arg1;
- (void)addAllResult:(id)arg1;
- (void)addResult:(id)arg1;
- (void)sessionEnd;
- (void)endRecord;
- (void)startRecord;
- (void)startRecognize;
- (void)generateInfo;
- (void)writePcmData;
- (void)dealloc;
- (id)init;

@end

