//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UIGestureRecognizerDelegate.h"

@class UIView;

@interface JASidePanelController : UIViewController <UIGestureRecognizerDelegate>
{
    struct CGRect _centerPanelRestingFrame;
    struct CGPoint _locationBeforePan;
    BOOL _panningLimitedToTopViewController;
    BOOL _recognizesPanGesture;
    BOOL _canUnloadRightPanel;
    BOOL _canUnloadLeftPanel;
    BOOL _shouldResizeLeftPanel;
    BOOL _shouldResizeRightPanel;
    BOOL _allowLeftOverpan;
    BOOL _allowRightOverpan;
    BOOL _bounceOnSidePanelOpen;
    BOOL _bounceOnSidePanelClose;
    BOOL _shouldDelegateAutorotateToVisiblePanel;
    BOOL _centerPanelHidden;
    BOOL _allowLeftSwipe;
    BOOL _allowRightSwipe;
    UIView *_leftPanelContainer;
    UIView *_rightPanelContainer;
    UIView *_centerPanelContainer;
    UIView *_tapView;
    int _style;
    int _state;
    UIViewController *_leftPanel;
    UIViewController *_centerPanel;
    UIViewController *_rightPanel;
    float _leftGapPercentage;
    float _leftFixedWidth;
    float _rightGapPercentage;
    float _rightFixedWidth;
    float _minimumMovePercentage;
    float _maximumAnimationDuration;
    float _bounceDuration;
    float _bouncePercentage;
    UIViewController *_visiblePanel;
}

+ (id)defaultImage;
@property(nonatomic) BOOL allowRightSwipe; // @synthesize allowRightSwipe=_allowRightSwipe;
@property(nonatomic) BOOL allowLeftSwipe; // @synthesize allowLeftSwipe=_allowLeftSwipe;
@property(nonatomic) BOOL centerPanelHidden; // @synthesize centerPanelHidden=_centerPanelHidden;
@property(nonatomic) BOOL shouldDelegateAutorotateToVisiblePanel; // @synthesize shouldDelegateAutorotateToVisiblePanel=_shouldDelegateAutorotateToVisiblePanel;
@property(nonatomic) __weak UIViewController *visiblePanel; // @synthesize visiblePanel=_visiblePanel;
@property(nonatomic) BOOL bounceOnSidePanelClose; // @synthesize bounceOnSidePanelClose=_bounceOnSidePanelClose;
@property(nonatomic) BOOL bounceOnSidePanelOpen; // @synthesize bounceOnSidePanelOpen=_bounceOnSidePanelOpen;
@property(nonatomic) BOOL allowRightOverpan; // @synthesize allowRightOverpan=_allowRightOverpan;
@property(nonatomic) BOOL allowLeftOverpan; // @synthesize allowLeftOverpan=_allowLeftOverpan;
@property(nonatomic) BOOL shouldResizeRightPanel; // @synthesize shouldResizeRightPanel=_shouldResizeRightPanel;
@property(nonatomic) BOOL shouldResizeLeftPanel; // @synthesize shouldResizeLeftPanel=_shouldResizeLeftPanel;
@property(nonatomic) BOOL canUnloadLeftPanel; // @synthesize canUnloadLeftPanel=_canUnloadLeftPanel;
@property(nonatomic) BOOL canUnloadRightPanel; // @synthesize canUnloadRightPanel=_canUnloadRightPanel;
@property(nonatomic) BOOL recognizesPanGesture; // @synthesize recognizesPanGesture=_recognizesPanGesture;
@property(nonatomic) BOOL panningLimitedToTopViewController; // @synthesize panningLimitedToTopViewController=_panningLimitedToTopViewController;
@property(nonatomic) float bouncePercentage; // @synthesize bouncePercentage=_bouncePercentage;
@property(nonatomic) float bounceDuration; // @synthesize bounceDuration=_bounceDuration;
@property(nonatomic) float maximumAnimationDuration; // @synthesize maximumAnimationDuration=_maximumAnimationDuration;
@property(nonatomic) float minimumMovePercentage; // @synthesize minimumMovePercentage=_minimumMovePercentage;
@property(nonatomic) float rightFixedWidth; // @synthesize rightFixedWidth=_rightFixedWidth;
@property(nonatomic) float rightGapPercentage; // @synthesize rightGapPercentage=_rightGapPercentage;
@property(nonatomic) float leftFixedWidth; // @synthesize leftFixedWidth=_leftFixedWidth;
@property(nonatomic) float leftGapPercentage; // @synthesize leftGapPercentage=_leftGapPercentage;
@property(retain, nonatomic) UIViewController *rightPanel; // @synthesize rightPanel=_rightPanel;
@property(retain, nonatomic) UIViewController *centerPanel; // @synthesize centerPanel=_centerPanel;
@property(retain, nonatomic) UIViewController *leftPanel; // @synthesize leftPanel=_leftPanel;
@property(nonatomic) int state; // @synthesize state=_state;
@property(nonatomic) int style; // @synthesize style=_style;
@property(retain, nonatomic) UIView *tapView; // @synthesize tapView=_tapView;
@property(retain, nonatomic) UIView *centerPanelContainer; // @synthesize centerPanelContainer=_centerPanelContainer;
@property(retain, nonatomic) UIView *rightPanelContainer; // @synthesize rightPanelContainer=_rightPanelContainer;
@property(retain, nonatomic) UIView *leftPanelContainer; // @synthesize leftPanelContainer=_leftPanelContainer;
- (void).cxx_destruct;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)setCenterPanelHidden:(BOOL)arg1 animated:(BOOL)arg2 duration:(double)arg3;
- (void)toggleRightPanel:(id)arg1;
- (void)toggleLeftPanel:(id)arg1;
- (void)showCenterPanelAnimated:(BOOL)arg1;
- (void)showRightPanelAnimated:(BOOL)arg1;
- (void)showLeftPanelAnimated:(BOOL)arg1;
- (void)showCenterPanel:(BOOL)arg1;
- (void)showRightPanel:(BOOL)arg1;
- (void)showLeftPanel:(BOOL)arg1;
- (id)leftButtonForCenterPanel;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (BOOL)_toggleScrollsToTop:(BOOL)arg1 forView:(id)arg2;
- (void)_toggleScrollsToTopForCenter:(BOOL)arg1 left:(BOOL)arg2 right:(BOOL)arg3;
- (void)_unhideCenterPanel;
- (void)_hideCenterPanel;
- (void)_showCenterPanel:(BOOL)arg1 bounce:(BOOL)arg2;
- (void)_showRightPanel:(BOOL)arg1 bounce:(BOOL)arg2;
- (void)_showLeftPanel:(BOOL)arg1 bounce:(BOOL)arg2;
@property(readonly, nonatomic) float rightVisibleWidth;
@property(readonly, nonatomic) float leftVisibleWidth;
- (struct CGRect)_adjustCenterFrame;
- (void)_animateCenterPanel:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (float)_calculatedDuration;
- (void)_unloadPanels;
- (void)_loadRightPanel;
- (void)_loadLeftPanel;
- (void)_loadCenterPanel;
- (BOOL)_isOnTopLevelViewController:(id)arg1;
- (BOOL)_validateThreshold:(float)arg1;
- (float)_correctMovement:(float)arg1;
- (void)_centerPanelTapped:(id)arg1;
- (void)_addTapGestureToView:(id)arg1;
- (void)_undoPan;
- (void)_completePan:(float)arg1;
- (void)_handlePan:(id)arg1;
- (void)_addPanGestureToView:(id)arg1;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)_placeButtonForLeftPanel;
- (void)_swapCenter:(id)arg1 with:(id)arg2;
- (void)_layoutSidePanels;
- (void)_layoutSideContainers:(BOOL)arg1 duration:(double)arg2;
- (void)_configureContainers;
- (void)stylePanel:(id)arg1;
- (void)styleContainer:(id)arg1 animate:(BOOL)arg2 duration:(double)arg3;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (void)_baseInit;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;

@end

