//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "MMGridViewDataSource.h"
#import "MMGridViewDelegate.h"

@class MMGridView, NSString;

@interface MediaPartyView : UIView <MMGridViewDataSource, MMGridViewDelegate>
{
    MMGridView *_listGridView;
    NSString *_type;
    id <MediaDelegate> _mediaDelegate;
}

@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) id <MediaDelegate> mediaDelegate; // @synthesize mediaDelegate=_mediaDelegate;
@property(retain, nonatomic) MMGridView *listGridView; // @synthesize listGridView=_listGridView;
- (void)gridView:(id)arg1 didSelectCell:(id)arg2 atIndex:(unsigned int)arg3;
- (void)gridview:(id)arg1 didTouchCellInImg:(id)arg2 atIndex:(int)arg3 withPoint:(struct CGPoint)arg4 withTouchState:(int)arg5;
- (void)gridView:(id)arg1 didSelectCellInImg:(id)arg2 atIndex:(unsigned int)arg3 withPoint:(struct CGPoint)arg4;
- (void)reloadData;
- (id)gridView:(id)arg1 cellAtIndex:(unsigned int)arg2;
- (int)numberOfCellsInGridView:(id)arg1;
- (id)init:(struct CGRect)arg1 withMediaDelegate:(id)arg2 withTyp:(id)arg3;

@end

