//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMGridViewCell, NSString, NsMedia;

@protocol MediaDelegate <NSObject>

@optional
- (void)didSelectMedia:(NsMedia *)arg1 withIndex:(int)arg2 withMediaTyp:(NSString *)arg3 didTouchCellInImg:(MMGridViewCell *)arg4 withPoint:(struct CGPoint)arg5 withTouchState:(int)arg6;
- (void)didSelectMedia:(NsMedia *)arg1 withIndex:(int)arg2 withMediaTyp:(NSString *)arg3 didSelectCellInImg:(MMGridViewCell *)arg4 withPoint:(struct CGPoint)arg5;
- (int)gridViewNumberOfRows;
- (int)gridViewNumberOfColumns;
@end

