//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMGridViewCell.h"

#import "EGOImageViewDelegate.h"

@class EGOImageView, UIImage, UILabel, UIView;

@interface MMGridViewDefaultCell : MMGridViewCell <EGOImageViewDelegate>
{
    UILabel *textLabel;
    UIView *textLabelBackgroundView;
    EGOImageView *_backgroundView;
    unsigned int labelHeight;
    unsigned int labelInset;
    UIImage *_placeholderImage;
    BOOL _ifCheckSelf;
    BOOL _isCategory;
}

@property(nonatomic) BOOL isCategory; // @synthesize isCategory=_isCategory;
@property(retain, nonatomic) EGOImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImage *placeholderImage; // @synthesize placeholderImage=_placeholderImage;
@property(retain, nonatomic) UIView *textLabelBackgroundView; // @synthesize textLabelBackgroundView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel;
- (void)imageViewFailedToLoadImage:(id)arg1 error:(id)arg2;
- (void)imageViewLoadedImage:(id)arg1;
- (void)layoutSubviews;
- (void)handleLongPress:(id)arg1;
- (void)showCheckBox;
- (void)deselectedAllItems;
- (void)selectedAllItems;
- (void)btnCheckClicked;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

