//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMGridView, MMGridViewCell;

@protocol MMGridViewDelegate <NSObject>

@optional
- (void)pullUpToRequestNextData;
- (void)pullDownToRequestLastData;
- (void)gridView:(MMGridView *)arg1 reachMaxSelectCount:(int)arg2;
- (void)gridview:(MMGridView *)arg1 didTouchCellInImg:(MMGridViewCell *)arg2 atIndex:(int)arg3 withPoint:(struct CGPoint)arg4 withTouchState:(int)arg5;
- (void)gridView:(MMGridView *)arg1 didSelectCellInImg:(MMGridViewCell *)arg2 atIndex:(unsigned int)arg3 withPoint:(struct CGPoint)arg4;
- (void)gridView:(MMGridView *)arg1 didSelectCellInCheck:(MMGridViewCell *)arg2 atIndex:(unsigned int)arg3;
- (void)gridView:(MMGridView *)arg1 changedPageToIndex:(unsigned int)arg2;
- (void)gridView:(MMGridView *)arg1 didDoubleTapCell:(MMGridViewCell *)arg2 atIndex:(unsigned int)arg3;
- (void)gridView:(MMGridView *)arg1 didSelectCell:(MMGridViewCell *)arg2 atIndex:(unsigned int)arg3;
@end

