//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSString, NSTimer;

@interface MSAlertView : UIView
{
    NSTimer *_timer;
    id <AlertDelegate> _delegate;
    UIView *_tostView;
    BOOL _isTost;
    NSString *_message;
    NSString *_leftStr;
    NSString *_rightStr;
}

@property(nonatomic) NSString *rightStr; // @synthesize rightStr=_rightStr;
@property(nonatomic) NSString *leftStr; // @synthesize leftStr=_leftStr;
@property(nonatomic) BOOL isTost; // @synthesize isTost=_isTost;
@property(nonatomic) NSString *message; // @synthesize message=_message;
@property(retain, nonatomic) UIView *tostView; // @synthesize tostView=_tostView;
@property(nonatomic) id <AlertDelegate> delegate; // @synthesize delegate=_delegate;
- (void)rightBtnClick;
- (void)leftBtnClick;
- (void)drawRect:(struct CGRect)arg1;
- (void)timerEnd;
- (void)createTostView:(id)arg1 withMessage:(id)arg2;
- (void)createAlertView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

