//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIResponder.h"

#import "MBProgressHUDDelegate.h"
#import "MsEngineDelegate.h"
#import "UIApplicationDelegate.h"

@class JASidePanelController, MSFunctionViewController, NSTimer, Reachability, UINavigationController, UIWindow;

@interface MSAppDelegate : UIResponder <UIApplicationDelegate, MsEngineDelegate, MBProgressHUDDelegate>
{
    JASidePanelController *_jasPanelController;
    Reachability *hostReach;
    Reachability *internetReach;
    Reachability *wifiReach;
    NSTimer *_timer;
    MSFunctionViewController *_functionVC;
    UIWindow *_window;
    UINavigationController *_rootNav;
}

@property(retain, nonatomic) UINavigationController *rootNav; // @synthesize rootNav=_rootNav;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (id)fetchSSIDInfo;
- (void)applicationWillResignActive:(id)arg1;
- (void)loadAssetFinished;
- (void)timer1End;
- (void)timerEnd;
- (void)timerOffEnd;
- (void)offLine1;
- (BOOL)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)showNoWifiAlert;
- (void)dealloc;

@end

