//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@interface MSMainBtnItem : UIButton
{
    struct CGPoint _startPoint;
    struct CGPoint _endPoint;
    struct CGPoint _nearPoint;
    struct CGPoint _farPoint;
    id <MSButtonDelegate> _btnDelegate;
    BOOL isMove;
}

@property(nonatomic) id <MSButtonDelegate> btnDelegate; // @synthesize btnDelegate=_btnDelegate;
@property(nonatomic) struct CGPoint farPoint; // @synthesize farPoint=_farPoint;
@property(nonatomic) struct CGPoint nearPoint; // @synthesize nearPoint=_nearPoint;
@property(nonatomic) struct CGPoint endPoint; // @synthesize endPoint=_endPoint;
@property(nonatomic) struct CGPoint startPoint; // @synthesize startPoint=_startPoint;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

