//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MyListViewController.h"

@interface MyList_iPadViewController : MyListViewController
{
}

- (id)getSection1Image;
- (id)getSection0Imag;
- (struct CGRect)getBtnIRect;
- (void)gotoMyListViewController:(id)arg1;
- (struct CGRect)getBgImageRect;
- (struct CGRect)getbtnAddRect;
- (struct CGRect)gettableViewRect;
- (id)getBgImage;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

