//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NEUGlobalMethod : NSObject
{
}

+ (id)makeMetaDataWithName:(id)arg1 mediaUrl:(id)arg2 withPath:(id)arg3 withAlbumArtUrl:(id)arg4 withDuration:(unsigned int)arg5 withSize:(id)arg6 withMediaObjType:(int)arg7;
+ (id)NSStringDateToNSDate:(id)arg1;
+ (int)convertToInt:(id)arg1;
+ (BOOL)isEmptyObj:(id)arg1;
+ (SEL)getGetterSelWithAttibuteName:(id)arg1;
+ (SEL)getSetterSelWithAttibuteName:(id)arg1;
+ (int)getIndexFromArray:(id)arg1 withString:(id)arg2;
+ (BOOL)isSizeHeightTooLong:(id)arg1 forSize:(struct CGSize)arg2 constrainedToSize:(struct CGSize)arg3;
+ (BOOL)isSizeWidthTooLong:(id)arg1 forSize:(struct CGSize)arg2 constrainedToSize:(struct CGSize)arg3;
+ (BOOL)ifStringIsEmpty:(id)arg1;
+ (int)getDeviceVer;
+ (id)randomColor;
+ (id)encodeURL:(id)arg1;

@end

