//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NEUGlobalData : NSObject
{
    int _deviceVersion;
}

+ (id)sharedGlobalData;
@property(nonatomic) int deviceVersion; // @synthesize deviceVersion=_deviceVersion;
- (void)dealloc;
- (void)restore;
- (id)init;

@end

