//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PlayListViewController.h"

@interface PlayList_iPadViewController : PlayListViewController
{
}

- (void)hideTabBar:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (id)getBGImage;
- (struct CGRect)getBGimageRect;
- (struct CGRect)getPaoMaRect;
- (struct CGRect)getCellBtnRect;
- (struct CGRect)getCellLabRect;
- (struct CGRect)getTableViewRect;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

