//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PPMediaObject.h"

@class NSMutableArray;

@interface PPMediaContainer : PPMediaObject
{
    struct PLT_MediaContainer *container;
    unsigned int childCount;
    NSMutableArray *list;
}

@property(retain, nonatomic) NSMutableArray *list; // @synthesize list;
- (void)dealloc;
- (void)updateDataWithBrowseInfo:(CDStruct_d889f7fa *)arg1;
- (BOOL)updateChildCount:(unsigned int)arg1;
- (void)setChildCount:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int childCount;
- (id)initWithContainer:(struct PLT_MediaContainer *)arg1;

@end

