//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PPMediaObject.h"

@class NSString;

@interface PPMediaItem : PPMediaObject
{
    struct PLT_MediaItem *item;
}

@property(readonly, nonatomic) unsigned int duration;
@property(readonly, nonatomic) NSString *artistName;
@property(readonly, nonatomic) NSString *albumName;
@property(readonly, nonatomic) NSString *trackName;
@property(readonly, nonatomic) NSString *metaData;
- (void)dealloc;
- (id)init;
- (id)initWithMetaData:(id)arg1;
- (id)initWithItem:(struct PLT_MediaItem *)arg1;

@end

