//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImage;

@interface ProgressControl : UIView
{
    UIImage *_bufferImage;
    UIImage *_backgroundImage;
    UIImage *_playImage;
    int _bufferProgress;
    int _playProgress;
}

- (void)dealloc;
- (void)setPlay:(float)arg1;
- (void)setBuffer:(float)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)drawPicByImage:(id)arg1 theRect:(struct CGRect)arg2;
- (id)imageFromImage:(id)arg1 inRect:(struct CGRect)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

