//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PushMediaCtrl.h"

#import "connectedDeviceDelegate.h"

@class UIAlertView, UIView;

@interface PushVideoCtrl : PushMediaCtrl <connectedDeviceDelegate>
{
    UIView *playerView;
    UIView *titleViewCtrl;
    id playerObserverId;
    UIAlertView *alert;
    UIAlertView *alert1;
    BOOL ctrlViewShow;
}

- (void)dealloc;
- (void)showAletView:(id)arg1;
- (void)lastMethod:(id)arg1;
- (void)nextMethod:(id)arg1;
- (void)playMethod:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)createLocalPlay:(int)arg1;
- (void)setSeekTime:(int)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)showCtrlViewMethod;
- (void)viewDidLoad;

@end

