//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSPushMediaCtrl.h"

#import "AlertDelegate.h"
#import "UIScrollViewDelegate.h"

@class MSAlertView, NSMutableArray, NSTimer, UIAlertView, UIButton, UIDevice, UIImageView, UIScrollView;

@interface PushImageCtrl : MSPushMediaCtrl <UIScrollViewDelegate, AlertDelegate>
{
    UIScrollView *_scrollView;
    UIImageView *_currentImageView;
    NSTimer *time;
    BOOL _isTcase;
    BOOL _isplay;
    UIButton *_startBtn;
    UIButton *_TcastBtn;
    UIAlertView *_reminderAlert;
    UIButton *_rotatePadBtn;
    UIButton *_sdPadBtn;
    UIButton *_leftBut;
    UIButton *_rightBut;
    MSAlertView *_alertView;
    UIDevice *device;
    int deviceOri;
    NSMutableArray *_nextImage;
    NSTimer *_getPlayTimer;
    MSAlertView *tempAlert;
    BOOL alertShow;
    NSTimer *statusTimer;
    int tempActions;
    int backTimer;
    int backView;
    BOOL SliderCtrl;
    id _temp;
}

@property(retain, nonatomic) id temp; // @synthesize temp=_temp;
@property(retain, nonatomic) MSAlertView *alertView; // @synthesize alertView=_alertView;
- (void)sendRetmoteUrl:(id)arg1;
- (void)dealloc;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)backBefore;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)loadScrollViewWithPage:(int)arg1;
- (void)createScrollView;
- (void)setSelectedPushMedia:(int)arg1;
- (void)initScrollerContent;
- (int)scrollViewWidth;
- (void)testAlertmeshod:(id)arg1;
- (void)showAlertView:(id)arg1 withMessage:(id)arg2;
- (void)sdBtn:(id)arg1;
- (void)TcastBtn:(id)arg1;
- (void)goBack;
- (void)rightBtnClick;
- (void)leftBtnClick;
- (void)showAlertViewImage:(id)arg1 withMessage:(id)arg2;
- (void)abstractcontrolPrevious;
- (void)abstractcontrolNext;
- (void)abstractControlPlayStatus:(id)arg1;
- (void)statusTimerMethod;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (id)initWithNibName:(id)arg1 withPage:(int)arg2 withType:(id)arg3 withIsPush:(BOOL)arg4;

@end

