//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PushVideoCtrl.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class UIButton;

@interface PushVideoCtrl_iPad : PushVideoCtrl <UITableViewDataSource, UITableViewDelegate>
{
    UIButton *listHidden;
    BOOL listCtrl;
}

- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)changeUI;
- (void)viewDidLoad;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)shareMusicMethod:(id)arg1;
- (void)goBack;
- (void)listHiddenMethod:(id)arg1;
- (void)lastMethod:(id)arg1;
- (void)nextMethod:(id)arg1;
- (void)playButtonUI;

@end

