//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MSPushMediaCtrl.h"

#import "AVAudioPlayerDelegate.h"
#import "TLMediaRenderDelegate.h"

@class AVAudioPlayer, AVPlayer, AVPlayerItem, AVPlayerLayer, CustomAlert, MPVolumeView, NSTimer, UIButton, UIImageView, UILabel, UISlider, UITableView, UIView;

@interface PushMediaCtrl : MSPushMediaCtrl <TLMediaRenderDelegate, AVAudioPlayerDelegate>
{
    UITableView *_mediaTableView;
    UIView *tableViewCtrl;
    UIView *playControlView;
    UIButton *lastButton;
    UIButton *playButton;
    UIButton *nextButton;
    UISlider *playSlider;
    UILabel *nowTimeLable;
    UILabel *totalTimeLable;
    UIButton *musicShareBut;
    UIImageView *shareImageView;
    UILabel *showLable;
    UILabel *showShareLable;
    UILabel *titleLable;
    NSTimer *_playDurationTimer;
    int circulation;
    int nowtime;
    int seekTime;
    AVAudioPlayer *musicPlayer;
    BOOL _isSharing;
    BOOL _cirlation;
    CustomAlert *transitionAlert;
    AVPlayer *player;
    AVPlayerItem *playerItem;
    AVPlayerLayer *playerLayer;
    int transition;
    int timeout;
    BOOL isBack;
    float tempVolume;
    MPVolumeView *volumeView;
    int tempActions;
    id mediaShareDelegate;
}

@property(retain, nonatomic) id mediaShareDelegate; // @synthesize mediaShareDelegate;
- (void)dealloc;
- (void)setTableViewIndexPath;
- (void)abstractControlPlayStatus:(id)arg1;
- (void)abstractControlTransportActions:(id)arg1;
- (void)abstractControlPlayState:(id)arg1;
- (void)abstraceControlPicureExit;
- (void)OnPauseResult:(id)arg1;
- (void)OnStopResult:(id)arg1;
- (void)OnPlayResult:(id)arg1;
- (void)speakerUpdated:(id)arg1;
- (void)abstraceControlSetMucisMode:(int)arg1;
- (void)abstractControlDuration:(int)arg1;
- (void)hiddenShowLable;
- (void)showLableMethod:(id)arg1;
- (void)musicCirculationPrevious;
- (void)musicCirculationNext;
- (void)abstractcontrolPrevious;
- (void)abstractcontrolNext;
- (void)abstractControlCurrentPosition:(int)arg1;
- (void)playSliderChange:(id)arg1;
- (void)sendRetmoteUrl:(id)arg1;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)setMediaTitle;
- (void)viewDidAppear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)getDurationTime:(int)arg1;
- (void)volumeChanged:(id)arg1;
- (void)viewDidLoad;
- (void)getPlayDuration:(id)arg1;
- (void)backClick;
- (id)initWithNibName:(id)arg1 withPage:(int)arg2 withType:(id)arg3;

@end

