//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseAudioPlayer.h"

@class NSTimer;

@interface StreamAudioPlayer : BaseAudioPlayer
{
    struct PlayData *playData;
    NSTimer *timer;
    float _volume;
}

- (void)startProc;
- (void)initMediaParam;
- (void)onTimer:(id)arg1;
- (void)errorOccurred:(int)arg1;
- (void)setPlayStatus:(int)arg1;
- (void)setAudioFileType:(id)arg1;
- (float)getDuration;
- (_Bool)appendData:(const char *)arg1 size:(unsigned long)arg2;
- (int)setVolume:(float)arg1;
- (void)setTotalSize:(float)arg1;
- (int)getStatus;
- (int)getPlayerFailed;
- (void)resume;
- (void)pause;
- (void)stop;
- (void)play;
- (void)dealloc;
- (id)init;

@end

