//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ThumbnailPickerView, UIImage;

@protocol ThumbnailPickerViewDataSource <NSObject>
- (UIImage *)thumbnailPickerView:(ThumbnailPickerView *)arg1 imageAtIndex:(unsigned int)arg2;
- (unsigned int)numberOfImagesForThumbnailPickerView:(ThumbnailPickerView *)arg1;
@end

