//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@interface TLBaseUIViewController : UIViewController
{
    unsigned long _tag;
}

@property(nonatomic) unsigned long tag; // @synthesize tag=_tag;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidUnload;
- (void)hideProgressHUD;
- (void)viewWillAppear:(BOOL)arg1;
- (void)viewDidLoad;
- (struct CGRect)getBGImageRect;
- (void)didReceiveMemoryWarning;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

