//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface TTSBaseView : UIView
{
}

- (void)drawPicByQuartz:(struct CGContext *)arg1 thePic:(id)arg2 theLocation:(struct CGRect)arg3;
- (void)drawPicByImage:(id)arg1 theRect:(struct CGRect)arg2;
- (void)drawPicByImage:(id)arg1 theLocation:(struct CGPoint)arg2;
- (void)drawTextByString:(id)arg1 theRect:(struct CGRect)arg2;
- (void)drawTextByString:(id)arg1 thePoisition:(struct CGPoint)arg2;
- (void)setFillColor:(struct CGContext *)arg1 theRed:(float)arg2 theGreen:(float)arg3 theBlue:(float)arg4;
- (id)addButton:(struct CGRect)arg1 theTitle:(id)arg2 theNormalImageName:(id)arg3 thePressedImageName:(id)arg4 theDisabledImageName:(id)arg5 theAction:(SEL)arg6 theActionObj:(id)arg7;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

