//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Util : NSObject
{
}

+ (id)createSendOnLineCmdTxt:(id)arg1;
+ (id)getCachImageView:(id)arg1;
+ (id)getUICallMetohodName:(id)arg1;
+ (id)parseBodyContentList:(id)arg1 withHeaderLength:(int)arg2;
+ (id)parseBodyContent:(id)arg1 withHeaderLength:(int)arg2;
+ (void)appendXml:(id)arg1 withData:(id)arg2 withStartPoint:(int)arg3 withLength:(int)arg4;
+ (id)createSocketCmd:(id)arg1;
+ (void)nsRelease:(id)arg1;
+ (id)converNSDataWithInt4:(int)arg1;
+ (id)converNSDataWithInt:(int)arg1;
+ (long)getXmlLegth4:(char *)arg1;
+ (long)getXmlLegth:(char *)arg1;
+ (id)xmlSimpleEscape:(id)arg1;
+ (id)getGDataXMLElement:(id)arg1 withTag:(id)arg2;
+ (id)parseMediaPath:(id)arg1;
+ (id)encodeURL:(id)arg1;
+ (id)encodeFullPathURL:(id)arg1;
+ (BOOL)getIPFromPath:(char *)arg1 outputIP:(char *)arg2 withOutPutIPSize:(int)arg3 outputContxt:(char *)arg4 withOutContextSize:(int)arg5;
+ (id)getBaseUrlFromPath:(id)arg1;
+ (id)md5_32:(id)arg1;
+ (id)md5_16:(id)arg1;

@end

