//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel;

@interface VideoCell_iPad : UITableViewCell
{
    UIImageView *videoImageView;
    UILabel *videoName;
}

@property(retain, nonatomic) UILabel *videoName; // @synthesize videoName;
@property(retain, nonatomic) UIImageView *videoImageView; // @synthesize videoImageView;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

