//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VLCAudio : NSObject
{
    void *instance;
}

@property unsigned int volume;
- (void)volumeDown;
- (void)volumeUp;
@property(setter=setMute:) BOOL isMuted;
- (void)dealloc;
- (id)initWithMediaPlayer:(id)arg1;
- (id)init;
- (struct libvlc_media_player_t *)instance;

@end

