//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface VLCLibrary : NSObject
{
    void *instance;
}

+ (id)sharedLibrary;
+ (void *)sharedInstance;
- (void)dealloc;
@property(readonly) NSString *changeset;
@property(readonly) NSString *version;
- (id)init;
@property(readonly) void *instance;

@end

