//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class MPVolumeView, NSMutableArray, UISlider;

@interface VolumeView : UIView
{
    NSMutableArray *_aryTimer;
    UISlider *_volumeSlider;
    MPVolumeView *_volume;
}

@property(retain, nonatomic) MPVolumeView *volume; // @synthesize volume=_volume;
@property(retain, nonatomic) UISlider *volumeSlider; // @synthesize volumeSlider=_volumeSlider;
@property(retain, nonatomic) NSMutableArray *aryTimer; // @synthesize aryTimer=_aryTimer;
- (void)hiddenVolume;
- (void)hiddenTime;
- (void)lessVolume;
- (void)addVolume;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

